### ISSUE TITLE
warn about non-ascii chars in abspath of .psyexp files

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1088]
It looks like pyglet (or maybe OSX cocoa something) does not properly handle non-ascii characters in paths. This can lead to obscure failure-to-run conditions.

``` python
############# Running: /Users/jgray/Acadêmico/untitled_lastrun.py #############
Traceback (most recent call last):
  File "/Users/jgray/Acadêmico/untitled_lastrun.py", line 14, in <module>
    from psychopy import locale_setup, visual, core, data, event, logging, sound, gui
  File "/Users/jgray/code/psychopy/psychopy/visual/__init__.py", line 16, in <module>
    from .window import Window, getMsPerFrame, openWindows
  File "/Users/jgray/code/psychopy/psychopy/visual/window.py", line 53, in <module>
    from psychopy import core, platform_specific, logging, prefs, monitors, event
  File "/Users/jgray/code/psychopy/psychopy/event.py", line 39, in <module>
    from pyglet.window.mouse import LEFT, MIDDLE, RIGHT  # takes ~250ms, so do it now
  File "/Users/jgray/anaconda/lib/python2.7/site-packages/pyglet/window/__init__.py", line 1817, in <module>
    gl._create_shadow_window()
  File "/Users/jgray/anaconda/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/Users/jgray/anaconda/lib/python2.7/site-packages/pyglet/window/__init__.py", line 559, in __init__
    self._create()
  File "/Users/jgray/anaconda/lib/python2.7/site-packages/pyglet/window/cocoa/__init__.py", line 206, in _create
    self.set_caption(self._caption)
  File "/Users/jgray/anaconda/lib/python2.7/site-packages/pyglet/window/cocoa/__init__.py", line 329, in set_caption
    self._nswindow.setTitle_(get_NSString(caption))
  File "/Users/jgray/anaconda/lib/python2.7/site-packages/pyglet/libs/darwin/cocoapy/cocoalibs.py", line 52, in get_NSString
    return CFSTR(string).autorelease()
  File "/Users/jgray/anaconda/lib/python2.7/site-packages/pyglet/libs/darwin/cocoapy/cocoalibs.py", line 43, in CFSTR
    None, string.encode('utf8'), kCFStringEncodingUTF8)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 18: ordinal not in range(128)
```

**Comment by TEParsons** [comment]
I've put in a draft PR to address this, but I'm worried this could get very annoying for non-English users - is running an experiment with non-ASCII characters in the file path still an issue? I don't want to bombard users with warnings if their experiments would run fine

**Comment by peircej** [comment]
I believe this was handled by the switch to Py3 which made unicode strings the default (and therefore allowed)
