### ISSUE TITLE
Loop cannot be inserted (Builder)

### ISSUE THREAD

**Issue by hsogo** [psychopy/psychopy#1170]
I'm sorry not for responding to @psychopy/translators messages.  I haven't been well since last year and now I am slow with my work.

Recently I pulled the latest codes from main branch to update translation and found that new loop could not be inserted in the Builder because "OK" button of the Loop Property Dialog was disabled.  Error message is following. (on Ubuntu 14.04 LTS / Windows10)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PsychoPy-1.84.0-py2.7.egg/psychopy/app/builder/validators.py", line 46, in Validate
    message, valid = self.check(parent)
  File "/usr/local/lib/python2.7/dist-packages/PsychoPy-1.84.0-py2.7.egg/psychopy/app/builder/validators.py", line 143, in check
    isCodeField = bool(parent.params[self.fieldName].valType == 'code')
KeyError: 'min value'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PsychoPy-1.84.0-py2.7.egg/psychopy/app/builder/validators.py", line 46, in Validate
    message, valid = self.check(parent)
  File "/usr/local/lib/python2.7/dist-packages/PsychoPy-1.84.0-py2.7.egg/psychopy/app/builder/validators.py", line 143, in check
    isCodeField = bool(parent.params[self.fieldName].valType == 'code')
KeyError: 'random seed'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PsychoPy-1.84.0-py2.7.egg/psychopy/app/builder/validators.py", line 46, in Validate
    message, valid = self.check(parent)
  File "/usr/local/lib/python2.7/dist-packages/PsychoPy-1.84.0-py2.7.egg/psychopy/app/builder/validators.py", line 143, in check
    isCodeField = bool(parent.params[self.fieldName].valType == 'code')
KeyError: 'nReps'

Using 'git bisect', I found that the following commit is the first bad commit.

[30ee241d2810b5cb5f141115a51d3f5499bc2966] RF: check syntax in code snippets; closes #1132

I examined this commit and found that this error occurs because parameters are not set to self.params before calling self.show() at line 1087 of app/builder/dialogs/__init__.py.  I guess that this error can be fixed by setting necessary parameters to self.params, but I don't have good idea how to do that.  Do you have any good ideas?

--
Hiroyuki

**Comment by hsogo** [comment]
Thank you for the quick response!
