### ISSUE TITLE
Core dump on linux

### ISSUE THREAD

**Issue by vrossum** [psychopy/psychopy#1185]
I run psychopyApp.py for the first time (as root or as user).
After the initial tests (with warnings about memory, refresh, and avbin), I press cancel.
Then it core-dumps.

```
gdb gives as backtrace:
#1  0x00007fffb3234b51 in _wrap_RichTextCtrl_MoveEnd () at /usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_richtext.so
#2  0x00007ffff7aedb65 in PyEval_EvalFrameEx () at /lib64/libpython2.7.so.1.0
#3  0x00007ffff7af144c in PyEval_EvalCodeEx () at /lib64/libpython2.7.so.1.0
#4  0x00007ffff7aed42f in PyEval_EvalFrameEx () at /lib64/libpython2.7.so.1.0
#5  0x00007ffff7af144c in PyEval_EvalCodeEx () at /lib64/libpython2.7.so.1.0
#6  0x00007ffff7a750bc in function_call () at /lib64/libpython2.7.so.1.0
#7  0x00007ffff7a50033 in PyObject_Call () at /lib64/libpython2.7.so.1.0
#8  0x00007ffff7a5f2ac in instancemethod_call () at /lib64/libpython2.7.so.1.0
#9  0x00007ffff7a50033 in PyObject_Call () at /lib64/libpython2.7.so.1.0
#10 0x00007ffff7ae59e7 in PyEval_CallObjectWithKeywords () at /lib64/libpython2.7.so.1.0
#11 0x00007ffff7a6dd72 in PyFile_WriteObject () at /lib64/libpython2.7.so.1.0
#12 0x00007ffff7ae6cfd in PyEval_EvalFrameEx () at /lib64/libpython2.7.so.1.0
#13 0x00007ffff7af144c in PyEval_EvalCodeEx () at /lib64/libpython2.7.so.1.0
#14 0x00007ffff7a750bc in function_call () at /lib64/libpython2.7.so.1.0
#15 0x00007ffff7a50033 in PyObject_Call () at /lib64/libpython2.7.so.1.0
#16 0x00007ffff7ae59e7 in PyEval_CallObjectWithKeywords () at /lib64/libpython2.7.so.1.0
#17 0x00007ffff7b0d13a in Py_Finalize () at /lib64/libpython2.7.so.1.0
#18 0x00007ffff7b1f4cb in Py_Main () at /lib64/libpython2.7.so.1.0
#19 0x00007ffff6d36731 in __libc_start_main (main=0x5555555547b0 <main>, argc=2, argv=0x7fffffffe2a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe298) at ../csu/libc-start.c:289
#20 0x00005555555547e9 in _start ()
```

This is version 1.82.1 with Python 2.7 on Fedora 24.
I also tried on a Fedora 23 system. Same result.

**Comment by hoechenberger** [comment]
Does the problem still occur with the most recent releases of PsychoPy?

**Comment by hoechenberger** [comment]
Closing for now due to lack of response. Feel free to re-open at any time if the problem persists!
