### ISSUE TITLE
Standalone Psychopy won’t start – Scipy / minpack2 issues?

### ISSUE THREAD

**Issue by zhouluke** [psychopy/psychopy#1363]
Hi,

I'm running a 64 bit version of Windows 10.

I recently installed Standalone Psychopy 1.85.0 (32 bit) to replace an older version (downloaded in Dec 2016) because that version suddenly stopped working on my computer. It turns out that this new version doesn't work either.

What was happening was that after clicking on the icon, the splash screen would appear, and then disappear with no application launched. This happens for both versions of Psychopy.

The Command Prompt gives the following output when ran from there:

I entered: "D:\Program Files (x86)\PsychoPy2\python.exe" "D:\Program Files (x86)\PsychoPy2\Lib\site-packages\psychopy\app\psychopyApp.py"

And got:
Traceback (most recent call last):
File "D:\Program Files (x86)\PsychoPy2\Lib\site-packages\psychopy\app\psychopyApp.py", line 62, in 
app = PsychoPyApp(0, showSplash=showSplash)
File "D:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\app_psychopyApp.py", line 118, in init
self.onInit(**kwargs)
File "D:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\app_psychopyApp.py", line 163, in onInit
from psychopy.compatibility import checkCompatibility
File "D:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\compatibility.py", line 4, in 
import psychopy.data
File "D:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\data.py", line 18, in 
from scipy import optimize, special
File "D:\Program Files (x86)\PsychoPy2\lib\site-packages\scipy\optimize__init__.py", line 232, in 
from .optimize import *
File "D:\Program Files (x86)\PsychoPy2\lib\site-packages\scipy\optimize\optimize.py", line 37, in 
from .linesearch import (line_search_wolfe1, line_search_wolfe2,
File "D:\Program Files (x86)\PsychoPy2\lib\site-packages\scipy\optimize\linesearch.py", line 18, in 
from scipy.optimize import minpack2
ImportError: DLL load failed: La procédure spécifiée est introuvable.

This problem persists when I do a clean install of Standalone Psychopy 1.85.0 on a different laptop with a totally new installation of Windows 10 having no other Python setups on it. It also persists when I install Psychopy in Anaconda.

If someone could point me to whatever packages I ought to install, I would greatly appreciate it!

I've also tried clearing out my .cfg files, but that hasn't worked either T_T

Thanks,
WhoaPanda / Luke.

**Comment by peircej** [comment]
I can't reproduce this problem on my machine right now, so can't debug it.

**Comment by hoechenberger** [comment]
> It also persists when I install Psychopy in Anaconda.

Now this is *really* odd. Could you post the exact steps you use to install PsychoPy in an Anaconda environment?

**Comment by hoechenberger** [comment]
Closing due to inactivity.
