### ISSUE TITLE
access violation when drawing a text stimulus

### ISSUE THREAD

**Issue by piotx** [psychopy/psychopy#1387]
Hi, 

I'm at loss with a strange problem. Our cooperation partners get the following error, when drawing a rating scale in a more complicated experiment (Windows 7, Psychopy 1.83.4):

 File "C:\Daten\DFG_Schmerz\main.py", line 417, in <module>
    imagination.rate_scripts()
  File "C:\Daten\DFG_Schmerz\imagination.py", line 624, in rate_scripts
    ratings = present_rating()
  File "C:\Daten\DFG_Schmerz\imagination.py", line 447, in present_rating
    ratings.append(rating.analogue_rating(rating_questions[i], labels = rating_label))
  File "C:\Daten\DFG_Schmerz\rating.py", line 285, in analogue_rating
    rat.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.04-py2.7.egg\psychopy\visual\ratingscale.py", line 962, in draw
    visualElement.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.04-py2.7.egg\psychopy\visual\text.py", line 603, in draw
    self._pygletTextObj.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\font\__init__.py", line 565, in draw
    self._layout.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\text\layout.py", line 852, in draw
    self.batch.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\graphics\__init__.py", line 544, in draw
    func()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\graphics\__init__.py", line 476, in <lambda>
    (lambda d, m: lambda: d.draw(m))(domain, mode))
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\graphics\vertexdomain.py", line 313, in draw
    glDrawArrays(mode, starts[0], sizes[0])
WindowsError: exception: access violation writing 0x00000004

I have run the experiment in our department many many times without any problems. Any ideas how to approach / solve this problem would be highly appreciated! Maybe we should try out a more recent psychopy version (1.85?).

Cheers
Piotr

**Comment by hoechenberger** [comment]
Hi @piotx, is this issue reliably reproducible on your collaborators' system? Or does it only happen once in a while? If it is indeed reproducible, could you try to provide a minimal working example which would _the developers_ allow to possibly reproduce the issue? Thanks!

**Comment by hoechenberger** [comment]
And yes, please do try to find out whether the problem still occurs with a recent release of PsychoPy.

**Comment by piotx** [comment]
Dear Richard,

unfortunately it happens only once in a while. It never happened at any of
my systems (windows 8, windows 7, linux), that's why I don't know, how to
approach it...

Piotr

2017-04-10 22:02 GMT+02:00 Richard Höchenberger <notifications@github.com>:

**Comment by hoechenberger** [comment]
Could you try updating the graphics drivers and see if that already helps?

**Comment by piotx** [comment]
sure, good idea.

**Comment by piotx** [comment]
Hi, the newest drivers were already installed;

it's really strange; I'm attaching here the last error message. I have no idea, what to do about it, to be honest...

Traceback (most recent call last):
  File "C:\Daten\DFG_Schmerz\main.py", line 404, in <module>
    repeat = instructions.ask_for_questions(custom.win, click_text = True)
  File "C:\Daten\DFG_Schmerz\instructions.py", line 114, in ask_for_questions
    return draw_text(win, ask_questions, mouse_click_stim)
  File "C:\Daten\DFG_Schmerz\instructions.py", line 76, in draw_text
    stimulus.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.04-py2.7.egg\psychopy\visual\text.py", line 603, in draw
    self._pygletTextObj.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\font\__init__.py", line 565, in draw
    self._layout.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\text\layout.py", line 852, in draw
    self.batch.draw()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\graphics\__init__.py", line 544, in draw
    func()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\graphics\__init__.py", line 476, in <lambda>
    (lambda d, m: lambda: d.draw(m))(domain, mode))
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\graphics\vertexdomain.py", line 313, in draw
    glDrawArrays(mode, starts[0], sizes[0])
WindowsError: exception: access violation writing 0x00000004
()

**Comment by peircej** [comment]
No, nor do I without being able to tweak the experiment on-site and see what breaks/fixes it. From this amount of info we can't debug it remotely. Text rendering problems I've seen have been caused by a) flakey graphics cards b) built-in windows drivers rather than manufacturer drivers or c) lack of graphics memory combined with the pyglet memory leak that we believe is now fixed. Minimising text updating is probably useful if you can but that's all I can suggest.

**Comment by piotx** [comment]
Ok, thabks for the hints... I'll try to play around with it remotely..

On May 10, 2017 21:28, "Jon Peirce" <notifications@github.com> wrote:

No, nor do I without being able to tweak the experiment on-site and see
what breaks/fixes it. From this amount of info we can't debug it remotely.
Text rendering problems I've seen have been caused by a) flakey graphics
cards b) built-in windows drivers rather than manufacturer drivers or c)
lack of graphics memory combined with the pyglet memory leak that we
believe is now fixed. Minimising text updating is probably useful if you
can but that's all I can suggest.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/psychopy/psychopy/issues/1387#issuecomment-300587935>,
or mute the thread

**Comment by piotx** [comment]
Dear Jon,
I didn't have the opportunity to check the experiment remotely. We would like to use a different graphics card, if things don't work out. Could you recommend a good graphics card, that works with pyglet very well and is rather cheap? Could I send you our code, so that you have a look at it. The study consists of two parts and the problem occurs only in one part. I was wondering, if it could have something to do with the nested functions.. I can't post the code publicly, because I didn't develop the paradigm. 
Cheers,
Piotr

**Comment by piotx** [comment]
I don't know much about memory in python, but would it make a difference if one removed some variables in the experiment, once they are not needed any longer. The problem occurs only if the experiment runs for a longer period of time. There is no problem, if we cut the experiment into pieces...

**Comment by piotx** [comment]
Dear Jon,
It seems, that the problem was based on windows drivers; our cooperation partners updated the drivers with windows update. After installing up to date drivers from the hardware vendor and updating to psychopy 1.85.1the issues could be resolved.
thanks!
