### ISSUE TITLE
missing labjack support in Win standalone >1.83.4

### ISSUE THREAD

**Issue by cjayb** [psychopy/psychopy#1551]
On the latest (indeed: post-1.83.4) Windows standalone, on a Win 10 machine, I'm unable to import the U3 device controller (see full trace below). I wonder if this is related an old MANIFEST issue reported here #399 ?

Some more context:
* works on Win standalone until and including 1.83.4
* works fine on the OS X standalone (tested until 1.85.2)
* Windows is a plague
* the `LabJackUD` drivers are installed
```python
ctypes.windll.LoadLibrary("labjackud")
<WinDLL 'labjackud', handle 1370000 at 33c4a50>
```

`# begin trace`
```python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
from labjack import u3
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: No module named labjack
from psychopy.hardware.labjacks import U3
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\hardware\labjacks.py", line 14, in <module>
    import u3
ImportError: No module named u3
```

**Comment by peircej** [comment]
This was fixed (not sure when)
