### ISSUE TITLE
pyglet.gl.ContextException: Unable to share contexts

### ISSUE THREAD

**Issue by claylacefield** [psychopy/psychopy#1579]
Just installed PsyPy 1.85.4 standalone on Win7 pc and getting error when trying to run stim scripts in coder (see below). Is this the Pyglet problem mentioned in release notes, or maybe problem with openGL drivers?
Thanks for your help!
```
Traceback (most recent call last):
  File "C:\Users\orion\Documents\PsychoPy\gratingArdSerial_103117_copy.py", line 22, in <module>
    mywin = visual.Window([800,600],monitor="testMonitor", units="deg")
  File "C:\Users\orion\Documents\PsychoPy\PsychoPy2\lib\site-packages\psychopy\visual\window.py", line 364, in __init__
    self._setupGL()
  File "C:\Users\orion\Documents\PsychoPy\PsychoPy2\lib\site-packages\psychopy\visual\window.py", line 1645, in _setupGL
    self._setupPyglet()
  File "C:\Users\orion\Documents\PsychoPy\PsychoPy2\lib\site-packages\psychopy\visual\window.py", line 1499, in _setupPyglet
    style=style)
  File "C:\Users\orion\Documents\PsychoPy\PsychoPy2\lib\site-packages\pyglet\window\win32\__init__.py", line 133, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Users\orion\Documents\PsychoPy\PsychoPy2\lib\site-packages\pyglet\window\__init__.py", line 572, in __init__
    self._create()
  File "C:\Users\orion\Documents\PsychoPy\PsychoPy2\lib\site-packages\pyglet\window\win32\__init__.py", line 265, in _create
    self.context.attach(self.canvas)
  File "C:\Users\orion\Documents\PsychoPy\PsychoPy2\lib\site-packages\pyglet\gl\win32.py", line 267, in attach
    super(Win32ARBContext, self).attach(canvas)
  File "C:\Users\orion\Documents\PsychoPy\PsychoPy2\lib\site-packages\pyglet\gl\win32.py", line 212, in attach
    raise gl.ContextException('Unable to share contexts')
pyglet.gl.ContextException: Unable to share contexts
Exception AttributeError: "'Window' object has no attribute 'useNativeGamma'" in <bound method Window.__del__ of <psychopy.visual.window.Window object at 0x0B36B1B0>> ignored
()
```

**Comment by peircej** [comment]
`Unable to share contexts` is generally a driver issue. Please update your graphics card drivers from the manufacturer and try again.

**Comment by lanstonchu** [comment]
I have this error when I call `pyrender.OffscreenRenderer()`.

The first time I called this function, there is no error. But if I run the code the second time, I will have this "`ContextException: Unable to share contexts`" error as well.

If I restarted my Python kernel, I can run the first time of my code again.

Is it the intended behavior, or is that something I need to check further regarding my driver?

**Comment by mirh** [comment]
Mentioning what that is wouldn't hurt. 

https://discourse.psychopy.org/t/bugfixes-for-unable-to-share-contexts-and-portaudio-not-initialized/3537
https://discourse.psychopy.org/t/unable-to-share-contexts-error-when-creating-window/9853/2
Also, are you using the last version and did you try the usual workarounds?
