### ISSUE TITLE
socket Error at starting

### ISSUE THREAD

**Issue by xxxspy** [psychopy/psychopy#1583]
```cmd
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\PsychoPy2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\PsychoPy2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\app\connections.py", line 43, in makeConnections
    web.setupProxy()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\web.py", line 251, in setupProxy
    if tryProxy(proxies) is True:
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\web.py", line 109, in tryProxy
    opener.open(req, timeout=2).read(5)  # open and read a few characters
  File "C:\Program Files (x86)\PsychoPy2\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\PsychoPy2\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Program Files (x86)\PsychoPy2\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\PsychoPy2\lib\urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Program Files (x86)\PsychoPy2\lib\urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Program Files (x86)\PsychoPy2\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "C:\Program Files (x86)\PsychoPy2\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files (x86)\PsychoPy2\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Program Files (x86)\PsychoPy2\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
```

*system info*: win10 64bit
*psychopy*: 1.85.4 (installed with *.exe)
*description*: This error happened when psychopy starting up in the cmd.
I reinstalled psychopy , the problem still exists.

**Comment by peircej** [comment]
This looks like an unusual connection scenario to do with your web connection (that most users aren't having)

Can you tell us anything about your internet connection? Are you behind a firewall or anything? e.g. does your institution require you to have a proxy setting in your internet browser? I assume the browser is retrieving google.com happily?

**Comment by TEParsons** [comment]
Closing due to lack of response, please reopen if this is still an issue
