### ISSUE TITLE
Error when loading video

### ISSUE THREAD

**Issue by xxxspy** [psychopy/psychopy#1584]
```cmd
欢迎来到 PsychoPy2！
v1.85.4
()
##### Running: E:\programs\shop\psychopy\Cognitive Reappraisal&expression suppression\test.py #####
pyo version 0.8.7 (uses single precision)
Traceback (most recent call last):
  File "E:\programs\shop\psychopy\Cognitive Reappraisal&expression suppression\test.py", line 80, in <module>
    depth=-1.0,
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\visual\movie3.py", line 129, in __init__
    self.loadMovie(self.filename)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\visual\movie3.py", line 175, in loadMovie
    self._mov = VideoFileClip(filename, audio=(1 - self.noAudio))
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 81, in __init__
    fps_source=fps_source)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 32, in __init__
    fps_source)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 256, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "C:\Program Files (x86)\PsychoPy2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Program Files (x86)\PsychoPy2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 不是有效的 Win32
```
The chinese at the last line means "invalid win32".
System info: win10 64bit
psychopy: 1.85.4 (installed via *.exe)

Any suggestions for the problem?

**Comment by hoechenberger** [comment]
@xxxspy I see that there's a special character (`&`) in your path, could that be related the issue by any chance?

**Comment by TEParsons** [comment]
Closing this as `movie3` is now deprecated in favour of a single `MovieStim` class (which @mdcutone has made a lot of fixes to, compared with movie3). Please reopen if you find this same bug in the new class.
