### ISSUE TITLE
Builder demos don't run in Python3

### ISSUE THREAD

**Issue by hsogo** [psychopy/psychopy#1617]
I tested Builder's keyNameFinder demo on the latest Builder and found this demo doesn't start with following error.

```
Traceback (most recent call last):
  File "C:\Users\Hiroyuki\Desktop\PsychoPy2 Demos\keyNameFinder\keyNameFinder_lastrun.py", line 66, in <module>
    ISI = clock.StaticPeriod(win=win, screenHz=expInfo['frameRate'], name='ISI')
NameError: name 'clock' is not defined
```
StaticPeriod has moved from psychopy.core to psychpy.clock, and StaticComponent follows this change.  However, psychopy.clock is not imported in the compiled script.  I think that 'clock' should be added to line 173-175 of psychopyLibs in app/builder/experiment.py.

```
        # What libs are needed (make sound come first)
        self.psychopyLibs = ['sound', 'gui', 'visual', 'core',
                             'data', 'event', 'logging']    # <- add 'clock' here!
```

**Comment by hsogo** [comment]
I changed title of this issue because I found many other problems in compatibility of Builder demos with Python 3.

At first, as reported at PsychoPy Discourse, branchedExp Demo doesn't start in Python 3 due to initial value of ExpInfo dialog. 

Next, branching Demo fails to save data due to error in TrialHander.

```
Traceback (most recent call last):
  File "C:\Users\Hiroyuki\Desktop\PsychoPy2 Demos\branchedExp\branching.py", line 270, in <module>
    dataOut=['n','all_mean','all_std', 'all_raw'])
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\data\base.py", line 324, in saveAsExcel
    matrixOnly=matrixOnly)
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\data\trial.py", line 406, in _createOutputArray
    for heading in stimOut + dataHead:
TypeError: unsupported operand type(s) for +: 'odict_keys' and 'list'
```

Converting `stimOut` to list object, the code works both Python 2 and 3.

**Comment by hsogo** [comment]
In Python3, ratingScales demo shows "You pressed None" when response is made by mouse button press.  `psychopy.visual.RatingScale.getRating()` is used to get response in this demo, and `getRating()` returns None at this if-statement (line1346-1347) in Python 3.

```
        if not type(self.markerPlacedAt) in [float, int]:
            return None  # eg, if skipped a response
```

I found that value of `self.markerPlacedAt` is float in Python 2, while numpy.float64 in Python 3.  When RatingScale is clicked, `self.markerPlacedAt` is updated at `_getMarkerFromPos()`.  `round()` is used to calculate marker position there.  `round(x)` returns float if x is numpy.float64 in Python 2.  On the other hand, `round(x)` returns numpy.float64 in Python 3.  This can be confirmed by following script both in Python 2 and 3.

```
import numpy as np
array = np.array([1.0])
print(type(round(array[0])))
```

Return value of `round()` should be converted to float to fix this problem.
