### ISSUE TITLE
pyglet combined with iohub crashes on startup

### ISSUE THREAD

**Issue by ariekahn** [psychopy/psychopy#1667]
When creating a new window with both iohub and pyglet, window.py references registerPygletWindowHandles which was previously renamed to registerWindowHandles.

This causes psychopy to crash on startup.

Issue appears to affect 1.85.6 upwards.

``` python
Traceback (most recent call last):
  File "experiment.py", line 403, in <module>
    win = visual.Window([1920, 1080], fullscr=True)
  File "/Users/ari/anaconda/envs/psychopy/lib/python2.7/site-packages/psychopy/visual/window.py", line 379, in __init__
    self._setupGL()
  File "/Users/ari/anaconda/envs/psychopy2/lib/python2.7/site-packages/psychopy/visual/window.py", line 1636, in _setupGL
    self._setupPyglet()
  File "/Users/ari/anaconda/envs/psychopy2/lib/python2.7/site-packages/psychopy/visual/window.py", line 1572, in _setupPyglet
    conn.registerPygletWindowHandles(*winhwnds)
AttributeError: 'ioHubConnection' object has no attribute 'registerPygletWindowHandles'
Exception
```

**Comment by ariekahn** [comment]
#1666
