### ISSUE TITLE
Psychopy does not start

### ISSUE THREAD

**Issue by andreagrusso** [psychopy/psychopy#1706]
Hi, I've installed psychopy but it is not working. If I open a python terminal it does not recognize any module named psychopy. 
This is the error displayed in terminal:
"Traceback (most recent call last):
  File "/usr/bin/psychopy", line 62, in <module>
    app = PsychoPyApp(0, showSplash=showSplash)
  File "/usr/lib/python2.7/dist-packages/psychopy/app/_psychopyApp.py", line 118, in __init__
    self.onInit(**kwargs)
  File "/usr/lib/python2.7/dist-packages/psychopy/app/_psychopyApp.py", line 163, in onInit
    from psychopy.compatibility import checkCompatibility
  File "/usr/lib/python2.7/dist-packages/psychopy/compatibility.py", line 4, in <module>
    import psychopy.data
  File "/usr/lib/python2.7/dist-packages/psychopy/data.py", line 30, in <module>
    if StrictVersion(openpyxl.__version__) >= StrictVersion('2.4.0'):
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '2.3.0-b2'
"

I've tried to uninstall and to install again psychopy, but nothing has changed

**Comment by peircej** [comment]
How did you do the installation? Which version did you try to install?

**Comment by peircej** [comment]
But looking at the error I think you'll be able to fix it by changing line 6 of psychopy/data.py from this:
```
from distutils.version import StrictVersion
```
to
```
from pkg_resources import parse_version
```

and then change line 30 from
```
if StrictVersion(openpyxl.version) >= StrictVersion('2.4.0'):
```
to
```
if parse_version(openpyxl.version) >= parse_version('2.4.0'):
```

**Comment by andreagrusso** [comment]
I installed the tool as follows : "apt-get install psychopy". 
I changed the code of psychopy/data.py, as you told, but it didn't worked

**Comment by andreagrusso** [comment]
This is the error now:
"Traceback (most recent call last):
  File "/usr/bin/psychopy", line 62, in <module>
    app = PsychoPyApp(0, showSplash=showSplash)
  File "/usr/lib/python2.7/dist-packages/psychopy/app/_psychopyApp.py", line 118, in __init__
    self.onInit(**kwargs)
  File "/usr/lib/python2.7/dist-packages/psychopy/app/_psychopyApp.py", line 163, in onInit
    from psychopy.compatibility import checkCompatibility
  File "/usr/lib/python2.7/dist-packages/psychopy/compatibility.py", line 4, in <module>
    import psychopy.data
  File "/usr/lib/python2.7/dist-packages/psychopy/data.py", line 16
    from __future__ import absolute_import
SyntaxError: from __future__ imports must occur at the beginning of the file
"

**Comment by JunSapporo** [comment]
Hi, 
I have the same problem. I installed from neurodebian, by 
sudo apt-get install --install-suggests psychopy
The version is psychopy 1.85.3.dfsg-1~nd14.04+1 .

I changed the code of psychopy/data.py, as peircej suggested. Now the message in the terminal reads as follows:
Traceback (most recent call last):
  File "/usr/bin/psychopy", line 62, in <module>
    app = PsychoPyApp(0, showSplash=showSplash)
  File "/usr/lib/python2.7/dist-packages/psychopy/app/_psychopyApp.py", line 118, in __init__
    self.onInit(**kwargs)
  File "/usr/lib/python2.7/dist-packages/psychopy/app/_psychopyApp.py", line 163, in onInit
    from psychopy.compatibility import checkCompatibility
  File "/usr/lib/python2.7/dist-packages/psychopy/compatibility.py", line 4, in <module>
    import psychopy.data
  File "/usr/lib/python2.7/dist-packages/psychopy/data.py", line 30, in <module>
    if parse_version(openpyxl.version) >= parse_version('2.4.0'):
AttributeError: 'module' object has no attribute 'version'

Thank you,

**Comment by peircej** [comment]
Oh, sorry I think that should be 
```
if parse_version(openpyxl.__version__) >= parse_version('2.4.0'):
```
(i.e. note the underscores around version)

**Comment by JunSapporo** [comment]
Great! It worked!!
Thank you,
