### ISSUE TITLE
importing event before visual causes stack underflow error in moviestim3

### ISSUE THREAD

**Issue by hgrotzinger** [psychopy/psychopy#1755]
I'm running psychopy2 (version 1.85.4) on mac high sierra (10.13.1).

I'm trying to use psychopy to play a .mov video clip and I noticed that if I import event before importing visual I get a stack underflow error. However, if I import visual first then the video clip plays without error. See the code below for an example:

```python
from psychopy import prefs

prefs.general['audioLib'] = ['pygame']
prefs.general['audioDevice'] = ['Built-in Output']

import psychopy.event  # stack underflow error
import psychopy.visual
# import psychopy.event  # works

win = psychopy.visual.Window()
filepath = "stimuli/test.mov"
movie = psychopy.visual.MovieStim3(win=win, filename=filepath)

while True:
    movie.draw()
    win.flip()
```

```
2018-03-01 16:02:16.248 python[60875:2597459] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "/Users/gablab/Desktop/affinities project/affinities_task/movie.py", line 15, in <module>
    movie.draw()
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/visual/movie3.py", line 417, in draw
    GL.glPopAttrib()
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/pyglet/gl/lib.py", line 104, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: stack underflow
```

**Comment by peircej** [comment]
I've just been exploring this in the latest versions and it seems fixed. Many things have changed (that was py2.7, pyglet 1.14 I expect whereas currently py3.6+ and pyglet 1.5.11) so presumably it was a bug elsewhere that has been fixed! 🚀
