### ISSUE TITLE
PsychoPy2_PY3 Error starting ioHub server

### ISSUE THREAD

**Issue by stfnrpplngr** [psychopy/psychopy#1811]
Hi,

trying to start the ioHub server, I get the following `RuntimeError`:

```
Traceback (most recent call last):
  File "C:\Users\User\GitHub\Experiment\VisualOddball.py", line 49, in <module>
    io = launchHubServer()
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\iohub\lazy_import.py", line 278, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server
ioHub Server Process Completed With Code:  1
```

This seems to be the same es in  #1760. I am using the latest standalone release 1.90.1.
@tjwilli58 Do you still have this problem?

**Comment by peircej** [comment]
@dvbridges you are able to run iohub demos on standard Py3 install, right?

**Comment by tjwilli58** [comment]
@stfnrpplngr , I'm not having this problem anymore. I believe what fixed this for me was installing pyHook using the wheel found [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook).

`python.exe -m pip install .\pyHook-1.5.1-cp36-cp36m-win_amd64.whl`

**Comment by stfnrpplngr** [comment]
No, I get exactly the same error message:

```
##### Running: C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\demos\coder\iohub\keyboard.py #####
Traceback (most recent call last):
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\demos\coder\iohub\keyboard.py", line 19, in <module>
    io = launchHubServer()
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server
ioHub Server Process Completed With Code:  1
```

**Comment by tjwilli58** [comment]
Not sure then. I haven't kept track of what I installed/uninstalled in tinkering with this to get things to work. Sorry, That was definitely part of it though. I broke iohub when I uninstalled pyHook to check.

I was also tinkering with various versions of pyglet, so you may want to try that. I'm currently using version 1.30b1, since that what worked to get a visual.Window() in Spyder.

**Comment by stfnrpplngr** [comment]
For me it was also version 1.30b1 of pyglet to make the initialisation of a window work.

Installing pyhook appears to be problematic:
```
python -m pip install pyHook-1.5.1-cp37-cp37m-win32.whl
pyHook-1.5.1-cp37-cp37m-win32.whl is not a supported wheel on this platform.
```

**Comment by tjwilli58** [comment]
Do you have a 32-bit or 64-bit Windows? I see you're running a 32-bit wheel.

**Comment by stfnrpplngr** [comment]
First, I tried the 64bit version, but have an Intel processor.
```
python -m pip install .\pyHook-1.5.1-cp37-cp37m-win_amd64.whl
pyHook-1.5.1-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by tjwilli58** [comment]
What version of python are you using? Python 2.7, or 3.x?

**Comment by stfnrpplngr** [comment]
```
python -V
Python 3.6.3 :: Anaconda custom (64-bit)
```

**Comment by tjwilli58** [comment]
You need to make sure the wheel you download matches your version of python and architecture.
amd64 also works with intel.  You want
 `pyHook-1.5.1-cp36-cp36m-win_amd64.whl`

**Comment by stfnrpplngr** [comment]
Yes, of course. Sorry :sweat_smile:
I installed it, but the problem persists. I tried starting the ioHub server in PsychoPy Standalone and via Spyder.

**Comment by tjwilli58** [comment]
Since pyHook is installed now, you could try uninstalling PsychoPy and reinstalling. Pip may do some version checking that may fic it, or at least give some insight.  I have a mix of conda pkgs and python pip pkgs. I've tried to conda install as many pkgs as I could before installing psychopy. Not sure if that makes a difference.

**Comment by hoechenberger** [comment]
In the conda directory of the PsychoPy repo, we have two environment files (for Python 2.7 and 3.6) that we we use create conda environments for continuous integration testing on Linux. You can use that as a starting point.

--

**Comment by hoechenberger** [comment]
But generally it shouldn’t make a difference. The approach to install as many packages a possible via conda is good, since conda does proper dependency management, unlike pip.

--

**Comment by dvbridges** [comment]
@peircej , the launchHub.py demo worked, but only after I installed pyHook

**Comment by tjwilli58** [comment]
I had a problem with a couple of the tests, but I don't have time to look into it right now.

```
PS C:\Users\timothy.j.williams1\demos.py3\coder\iohub> C:\Users\timothy.j.williams1\Anaconda3\python.exe .\launchHub.py
```

(first 2 tests passed)

```
------------------------------------

Running testEnabledDataStore Test:
Error during ioDataStore creation....
Traceback (most recent call last):
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\server.py", line 556, in _initDataStore
    self.createDataStoreFile(hdf_name, ds_dir, 'a', ds_conf)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\server.py", line 849, in createDataStoreFile
    self.dsfile = DataStoreFile(fname, fpath, fmode, iohub_settings)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\datastore\__init__.py", line 96, in __init__
    self.loadTableMappings()
AttributeError: 'DataStoreFile' object has no attribute 'loadTableMappings'
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'width': 300.0, 'height': 187.5, 'unit_type': b'mm'}
Experiment Metadata:
{'code': 'gap_endo_que',
 'description': '',
 'experiment_id': False,
 'title': '',
 'total_sessions_to_run': 0,
 'version': ''}

Session Metadata:
{'code': 'S_24_04_2018_11_19',
 'comments': '',
 'name': '',
 'session_id': False,
 'user_variables': {}}
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testEnabledDataStoreAutoSessionCode Test:
Current Session Code will be:  S_1524583166
Error during ioDataStore creation....
Traceback (most recent call last):
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\server.py", line 556, in _initDataStore
    self.createDataStoreFile(hdf_name, ds_dir, 'a', ds_conf)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\server.py", line 849, in createDataStoreFile
    self.dsfile = DataStoreFile(fname, fpath, fmode, iohub_settings)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\datastore\__init__.py", line 93, in __init__
    self.buildOutTemplate()
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\datastore\__init__.py", line 107, in buildOutTemplate
    self.TABLES['CLASS_TABLE_MAPPINGS'] = self.emrtFile.createTable(froot,
AttributeError: 'File' object has no attribute 'createTable'
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'width': 300.0, 'height': 187.5, 'unit_type': b'mm'}
Experiment Metadata:
{'code': 'gap_endo_que',
 'description': '',
 'experiment_id': False,
 'title': '',
 'total_sessions_to_run': 0,
 'version': ''}

Session Metadata:
{'code': 'S_1524583166',
 'comments': '',
 'name': '',
 'session_id': False,
 'user_variables': {}}
ioHub Server Process Completed With Code:  0
Test Result:  None

```

Running from within Spyder however, I get the error starting ioHub server.

```
------------------------------------

Running testEnabledDataStore Test:
Traceback (most recent call last):

  File "<ipython-input-1-6e1b568c7b53>", line 1, in <module>
    runfile('C:/Users/timothy.j.williams1/demos.py3/coder/iohub/launchHub.py', wdir='C:/Users/timothy.j.williams1/demos.py3/coder/iohub')

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/timothy.j.williams1/demos.py3/coder/iohub/launchHub.py", line 158, in <module>
    result = namespace[test]()

  File "C:/Users/timothy.j.williams1/demos.py3/coder/iohub/launchHub.py", line 89, in testEnabledDataStore
    experiment_code=exp_code)

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')

RuntimeError: Error starting ioHub server


```

I'm going to have to look into this further later, when I get some time.

**Comment by stfnrpplngr** [comment]
Today, I reinstalled PsychoPy2_PY3 v1.90.1 after installing PyHook as described above.

The error message stays the same.

```
##### Running: C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\demos\coder\iohub\launchHub.py #####

------------------------------------

Running testWithNoKwargs Test:
ioHub Server Process Completed With Code:  1
Traceback (most recent call last):
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\demos\coder\iohub\launchHub.py", line 158, in <module>
    result = namespace[test]()
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\demos\coder\iohub\launchHub.py", line 27, in testWithNoKwargs
    io = launchHubServer()
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server
```

**Comment by hoechenberger** [comment]
How do you run the script, and which version of Spyder are you using?

**Comment by stfnrpplngr** [comment]
From the beginning on, the problem was present in standalone and Spyder. My last post shows the error message from the standalone session.
Using Spyder I simply run the script [launchHub.py](https://github.com/psychopy/psychopy/blob/master/psychopy/demos/coder/iohub/launchHub.py) appending the PYTHONPATH to include the dependencies for PsychoPy as described in Issue #1813:

```
from sys import path

path.append("C:\\Continuum\\anaconda3\\envs\\anaconda-py3\\Lib\\site-packages")
path.append("C:\\Users\\User\\Documents\\GitHub\\psychopy")

runfile('C:/Program Files (x86)/PsychoPy2_PY3/Lib/site-packages/psychopy/demos/coder/iohub/launchHub.py', wdir='C:/Program Files (x86)/PsychoPy2_PY3/Lib/site-packages/psychopy/demos/coder/iohub')

------------------------------------

Running testWithNoKwargs Test:
Traceback (most recent call last):

  File "<ipython-input-2-33f7587e14c6>", line 1, in <module>
    runfile('C:/Program Files (x86)/PsychoPy2_PY3/Lib/site-packages/psychopy/demos/coder/iohub/launchHub.py', wdir='C:/Program Files (x86)/PsychoPy2_PY3/Lib/site-packages/psychopy/demos/coder/iohub')

  File "C:\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Program Files (x86)/PsychoPy2_PY3/Lib/site-packages/psychopy/demos/coder/iohub/launchHub.py", line 158, in <module>
    result = namespace[test]()

  File "C:/Program Files (x86)/PsychoPy2_PY3/Lib/site-packages/psychopy/demos/coder/iohub/launchHub.py", line 27, in testWithNoKwargs
    io = launchHubServer()

  File "C:\Users\User\Documents\GitHub\psychopy\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)

  File "C:\Users\User\Documents\GitHub\psychopy\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)

  File "C:\Users\User\Documents\GitHub\psychopy\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')

RuntimeError: Error starting ioHub server
```
___
Python 3.6.5 |Anaconda custom (64-bit)| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
IPython 6.1.0 -- An enhanced Interactive Python.
Spyder 3.2.8
PsychoPy-1.90.1-py3.6

**Comment by hoechenberger** [comment]
Does it work with the Python 2 release?

**Comment by tjwilli58** [comment]
@hoechenberger , just so you have a little more info, I'm also using Spyder 3.2.8, but my Python is 3.6.4. I run launchHub.py by opening the file in Spyder and running it with a dedicated IPython console. 
That's when I get the error starting ioHub server on the testEnabledDataStore test. 
When I run it from withing Spyder in an external system terminal, and from a PowerShell terminal, I get the error
`AttributeError: 'File' object has no attribute 'createTable'`

Yesterday I updated setuptools to see if that would help any. It didn't

(I'm getting ready to go on travel, so I may not be replying for awhile.)

**Comment by peircej** [comment]
Yes, one problem was pyHook installation (solved) and the other appears to be specific to use of Spyder (which also fits into my "I'm not personally trying to fix it" category, I'm afraid). 

ioHub does (necessarily) create a further process. I wonder if Spyder doesn't like that (because of its debugger system). 

If you don't want to run scripts from the PsychoPy app you could try PyCharm instead of Spyder? (It's actually far superior and free for the community edition)

**Comment by stfnrpplngr** [comment]
That is what comes out starting `launchHub.py` from the freshly installed Python 2 release:

```
##### Running: C:\Program Files (x86)\PsychoPy2_PY3\lib\site-packages\psychopy\demos\coder\iohub\launchHub.py #####

------------------------------------

Running testWithNoKwargs Test:
Warning: msgpack_numpy could not be imported. This may cause issues for iohub.
Warning: msgpack_numpy could not be imported. This may cause issues for iohub.

 ** PRESS A KEY TO CONTINUE.....
A Keyboard Event was Detected; exiting Test.
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testUsingPsychoPyMonitorConfig Test:
Warning: msgpack_numpy could not be imported. This may cause issues for iohub.
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'unit_type': 'mm', 'width': 300.0, 'height': 168.75}
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testEnabledDataStore Test:
Warning: msgpack_numpy could not be imported. This may cause issues for iohub.
Error during ioDataStore creation....
Traceback (most recent call last):
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\iohub\server.py", line 556, in _initDataStore
    self.createDataStoreFile(hdf_name, ds_dir, 'a', ds_conf)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\iohub\server.py", line 849, in createDataStoreFile
    self.dsfile = DataStoreFile(fname, fpath, fmode, iohub_settings)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\iohub\datastore\__init__.py", line 93, in __init__
    self.buildOutTemplate()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\iohub\datastore\__init__.py", line 118, in buildOutTemplate
    title='Mapping of ioHub DeviceEvent Classes to ioHub DataStore Tables.'
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\tables\file.py", line 1060, in create_table
    chunkshape=chunkshape, byteorder=byteorder)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\tables\table.py", line 873, in __init__
    byteorder, _log)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\tables\leaf.py", line 262, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\tables\node.py", line 261, in __init__
    parentnode._g_refnode(self, name, validate)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\tables\group.py", line 526, in _g_refnode
    % (self._v_pathname, childname))
NodeError: group ``/`` already has a child node named ``class_table_mapping``
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'unit_type': 'mm', 'width': 300.0, 'height': 168.75}
Experiment Metadata: 
{'code': 'gap_endo_que',
 'description': '',
 'experiment_id': False,
 'title': '',
 'total_sessions_to_run': 0,
 'version': ''}

Session Metadata: 
{'code': u'S_25_04_2018_14_55',
 'comments': '',
 'name': '',
 'session_id': False,
 'user_variables': {}}
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testEnabledDataStoreAutoSessionCode Test:
Current Session Code will be:  S_1524660945
Warning: msgpack_numpy could not be imported. This may cause issues for iohub.
Error during ioDataStore creation....
Traceback (most recent call last):
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\iohub\server.py", line 556, in _initDataStore
    self.createDataStoreFile(hdf_name, ds_dir, 'a', ds_conf)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\iohub\server.py", line 849, in createDataStoreFile
    self.dsfile = DataStoreFile(fname, fpath, fmode, iohub_settings)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\iohub\datastore\__init__.py", line 93, in __init__
    self.buildOutTemplate()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\iohub\datastore\__init__.py", line 118, in buildOutTemplate
    title='Mapping of ioHub DeviceEvent Classes to ioHub DataStore Tables.'
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\tables\file.py", line 1060, in create_table
    chunkshape=chunkshape, byteorder=byteorder)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\tables\table.py", line 873, in __init__
    byteorder, _log)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\tables\leaf.py", line 262, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\tables\node.py", line 261, in __init__
    parentnode._g_refnode(self, name, validate)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\tables\group.py", line 526, in _g_refnode
    % (self._v_pathname, childname))
NodeError: group ``/`` already has a child node named ``class_table_mapping``
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'unit_type': 'mm', 'width': 300.0, 'height': 168.75}
Experiment Metadata: 
{'code': 'gap_endo_que',
 'description': '',
 'experiment_id': False,
 'title': '',
 'total_sessions_to_run': 0,
 'version': ''}

Session Metadata: 
{'code': 'S_1524660945',
 'comments': '',
 'name': '',
 'session_id': False,
 'user_variables': {}}
ioHub Server Process Completed With Code:  0
Test Result:  None

```

**Comment by hoechenberger** [comment]
> Warning: msgpack_numpy could not be imported. This may cause issues for iohub.

What's with that, does standalone not include `msgpack_numpy`? Could that be related to the issue?

**Comment by stfnrpplngr** [comment]
> What's with that, does standalone not include msgpack_numpy? Could that be related to the issue?

I had this warning with the Python 3 version as well, but installing the module did not change anything.

> And that only happens with standalone Python 2, while ioHub doesn't even start up with standalone Python 3?

Yes. Maybe interesting, there is no problem with `StandalonePsychoPy-1.85.6-win32`.

**Comment by hoechenberger** [comment]
When trying to run `launchHubServer` in IPython (which includes Spyder), it fails though.

**Comment by tjwilli58** [comment]
I mistakenly posted about running the launchHub.py test failing  in #1759. I ran it in PsychopyApp instead of Spyder and it still failed.

`##### Running: C:\Users\timothy.j.williams1\Anaconda3\Lib\site-packages\psychopy\demos\coder\iohub\launchHub.py #####

------------------------------------

Running testWithNoKwargs Test:

 ** PRESS A KEY TO CONTINUE.....
A Keyboard Event was Detected; exiting Test.
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testUsingPsychoPyMonitorConfig Test:
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'width': 300.0, 'height': 187.5, 'unit_type': b'mm'}
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testEnabledDataStore Test:
Traceback (most recent call last):
  File "C:\Users\timothy.j.williams1\Anaconda3\Lib\site-packages\psychopy\demos\coder\iohub\launchHub.py", line 158, in <module>
    result = namespace[test]()
  File "C:\Users\timothy.j.williams1\Anaconda3\Lib\site-packages\psychopy\demos\coder\iohub\launchHub.py", line 89, in testEnabledDataStore
    experiment_code=exp_code)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server
ioHub Server Process Completed With Code:  1
`
I went to try and run the offending test from inside the shell:

`>>> from psychopy.demos.coder.iohub import launchHub
`
```
>>> launchHub.testEnabledDataStore()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\demos\coder\iohub\launchHub.py", line 89, in testEnabledDataStore
    experiment_code=exp_code)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server
>>> 

```

In launchHub.testEnabledDataStore(), what/where is 

`        exp_code = 'gap_endo_que'
`
?

**Comment by hcp4715** [comment]
I run the following code in the shell of StandalonePsychoPy3-3.0.0b9-win32.exe
`from psychopy.demos.coder.iohub import launchHub
launchHub.testEnabledDataStore()`

and get the following error:

> Warning: msgpack_numpy could not be imported. This may cause issues for iohub.
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\demos\coder\iohub\launchHub.py", line 89, in testEnabledDataStore
    experiment_code=exp_code)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server

My PC's OS is win 10, 64 bit, with an intel Xeon CPU.

**Comment by isolver** [comment]
Closing this as the issues not related to running via Spyder should have all been fixed by now. 

Further, iohub experiments seem to run fine with Spyder 4 and Python 3.6 as long as you set the script to "Excecute in a dedicated console" in the Spyder Run settings.
