### ISSUE TITLE
Error with visual.Textbox on Windows 10

### ISSUE THREAD

**Issue by SlugocM** [psychopy/psychopy#1894]
Hello everyone, 

If I run any demo that uses visual.Textbox on PsychoPy (standalone version v1.90.3) on Windows 10,  I get the following error: 

[Output from running 'textstim_vs_textbox.py' demo]

Welcome to PsychoPy2!
v1.90.3

##### Running: C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\demos\coder\stimuli\textBoxStim\textstim_vs_textbox.py #####
FreeType import Failed: Freetype library not found
Traceback (most recent call last):
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\demos\coder\stimuli\textBoxStim\textstim_vs_textbox.py", line 25, in <module>
    from psychopy.visual import textbox
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\visual\textbox\__init__.py", line 59, in <module>
    fm = getFontManager()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\visual\textbox\__init__.py", line 56, in getFontManager
    _system_font_manager = FontManager(mono_only)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\visual\textbox\fontmanager.py", line 77, in __init__
    self.updateFontInfo(monospace_only)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\visual\textbox\fontmanager.py", line 244, in updateFontInfo
    self.addFontFiles(fonts_found, monospace_only)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\visual\textbox\fontmanager.py", line 151, in addFontFiles
    face = Face(fp)
NameError: global name 'Face' is not defined

Seems as though a monospace font is missing, or a variable in the fontmanager.py file is mislabeled. I will try to investigate further and solve the problem, but please let me know if someone knows/finds a solution. 

Best,
Michael

**Comment by SlugocM** [comment]
Just read the top line and realized the "Freetype library" is not installed. Should this come pre-installed on standalone?

**Comment by peircej** [comment]
I've looked into this and fixed in the Standalone distros (will be in 3.0.0b5).

For info:
  - we were packaging a v slightly adapted freetype-py package inside psychopy
  - removed that and use the pip installed freetype-py instead (more recent and includes its own dll//dylib)

Relevant commit at #1930

**Comment by jackdolgin** [comment]
I'm finding a similar issue when I run Textbox on my Mac in PsychoPy3, and the issue disappears when I run it in on a Windows10 (see also [this](https://discourse.psychopy.org/t/textbox-cannt-work-freetype-ft-errors/6649/2) discourse conversation)

  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/contrib/lazy_import.py", line 119, in __call__
    obj = object.__getattribute__(self, '_resolve')()
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/contrib/lazy_import.py", line 88, in _resolve
    obj = factory(self, scope, name)
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/contrib/lazy_import.py", line 203, in _import
    module = __import__(module_python_path, scope, scope, [member], level=0)
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/visual/textbox/__init__.py", line 37, in <module>
    from .fontmanager import FontManager
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/visual/textbox/fontmanager.py", line 21, in <module>
    from freetype import Face, FT_LOAD_RENDER, FT_LOAD_FORCE_AUTOHINT, FT_Exception
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "freetype/__init__.pyc", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "freetype/raw.pyc", line 52, in <module>
RuntimeError: Freetype library not found

**Comment by peircej** [comment]
I'll look into the packaging and see why the lib isn't being packaged (or maybe just not detected) but in the meantime you can most likely install freetype with homebrew
