### ISSUE TITLE
MovieStim3 not closing video sometimes causes OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by tjwilli58** [psychopy/psychopy#1915]
We've have an experiment that displays videos in multiple trials/blocks. Sometimes trial/block completes, but other times when the experiment tries to open the video again, there is an error.

```

Traceback (most recent call last):
  File "C:\Users\xxx\blockedTrialsVideoBreaks\blockedVideoTrialsWithBreaksWorking_videoLoopVideo.py", line 413, in <module>
    depth=-2.0,
  File "C:\Users\xxx\Anaconda3\envs\perceptionlab\lib\site-packages\psychopy\visual\movie3.py", line 134, in __init__
    self.loadMovie(self.filename)
  File "C:\Users\xxx\Anaconda3\envs\perceptionlab\lib\site-packages\psychopy\visual\movie3.py", line 180, in loadMovie
    self._mov = VideoFileClip(filename, audio=(1 - self.noAudio))
  File "C:\Users\xxx\Anaconda3\envs\perceptionlab\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "C:\Users\xxx\Anaconda3\envs\perceptionlab\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "C:\Users\xxx\Anaconda3\envs\perceptionlab\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 256, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "C:\Users\xxx\Anaconda3\envs\perceptionlab\lib\subprocess.py", line 596, in __init__
    _cleanup()
  File "C:\Users\xxx\Anaconda3\envs\perceptionlab\lib\subprocess.py", line 205, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Users\xxx\Anaconda3\envs\perceptionlab\lib\subprocess.py", line 1035, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid


```
It turns out that if you add a .close() to _unload() in movie3.py, this fixes the problem.

```
    def _unload(self):
        try:
            # remove textures from graphics card to prevent crash
            self.clearTextures()
        except Exception:
            pass
        self._mov.close()
        self._mov = None
        self._numpyFrame = None
        self._audioStream = None
        self.status = FINISHED

```

I haven't checked movie2.py.

**Comment by tjwilli58** [comment]
added a [pull request 1917](https://github.com/psychopy/psychopy/pull/1917)

**Comment by tjwilli58** [comment]
Pull request accepted
