### ISSUE TITLE
Clean install of StandalonePsychoPy3_PY3-3.0.0b3-MacOS.dmg fails on app startup

### ISSUE THREAD

**Issue by jacob-lee** [psychopy/psychopy#1925]
A clean install of PsychoPy3 (StandalonePsychoPy3_PY3-3.0.0b3-MacOS.dmg) on a Mac Book Pro running OSX 10.11.6. On start up it crashes. Sort of looks like a  PIL dynamic library was built for OSX 10.12. 

Ran from terminal and got this stack trace:

> ~ jacoblee$  /Applications/PsychoPy3_PY3.app/Contents/MacOS/PsychoPy3
01:16:29 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
01:16:29 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
01:16:29 PM: Debug: Adding duplicate animation handler for '1' type
01:16:29 PM: Debug: Adding duplicate animation handler for '2' type
01:16:29 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
01:16:29 PM: Debug: Adding duplicate animation handler for '1' type
01:16:29 PM: Debug: Adding duplicate animation handler for '2' type
Traceback (most recent call last):
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/__boot__.py", line 430, in <module>
    _run()
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/__boot__.py", line 409, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/psychopyApp.py", line 96, in <module>
    start_app()
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/psychopyApp.py", line 28, in start_app
    app = PsychoPyApp(0, showSplash=showSplash)
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/_psychopyApp.py", line 178, in __init__
    self.onInit(testMode=testMode, **kwargs)
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/_psychopyApp.py", line 212, in onInit
    from psychopy.app import coder, builder, dialogs
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/coder/__init__.py", line 9, in <module>
    from .coder import *  # pylint: disable=W0401
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/coder/coder.py", line 22, in <module>
    import psychopy.app.pavlovia_ui.menu
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/pavlovia_ui/__init__.py", line 22, in <module>
    from . import menu, project, search, toolbar
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/pavlovia_ui/toolbar.py", line 4, in <module>
    from .. import icons
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/psychopy/app/icons.py", line 15, in <module>
    from PIL import Image
  File "/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: dlopen(/Applications/PsychoPy3_PY3.app/Contents/Resources/lib/python3.6/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Applications/PsychoPy3_PY3.app/Contents/MacOS/../Resources/lib/python3.6/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/PsychoPy3_PY3.app/Contents/MacOS/../Resources/lib/python3.6/PIL/.dylibs/liblzma.5.dylib
2018-08-03 13:16:29.821 PsychoPy3[1038:45527] PsychoPy3 Error

**Comment by peircej** [comment]
Looks like this was a temporary bug in pillow that has been fixed. I've just installed newer versions and I'll include those in 3.0.0b5! :-)
