### ISSUE TITLE
Win10 Standalone Beta8/Conda install won't start: esprima missing

### ISSUE THREAD

**Issue by OlafHaag** [psychopy/psychopy#2000]
I'm on Windows 10 and I just installed the latest beta8 and wanted to start PsychoPy but it crashed silently. Did restart just in case, but to no avail. So I tried starting it with from the console using python.exe with this result:
```cmd
C:\Program Files (x86)\PsychoPy3>python.exe Lib\site-packages\psychopy\app\psychopyApp.py
Traceback (most recent call last):
  File "Lib\site-packages\psychopy\app\psychopyApp.py", line 96, in <module>
    start_app()
  File "Lib\site-packages\psychopy\app\psychopyApp.py", line 28, in start_app
    app = PsychoPyApp(0, showSplash=showSplash)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\app\_psychopyApp.py", line 181, in __init__
    self.onInit(testMode=testMode, **kwargs)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\app\_psychopyApp.py", line 215, in onInit
    from psychopy.app import coder, builder, dialogs
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\app\coder\__init__.py", line 9, in <module>
    from .coder import *  # pylint: disable=W0401
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\app\coder\coder.py", line 22, in <module>
    import psychopy.app.pavlovia_ui.menu
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\app\pavlovia_ui\__init__.py", line 22, in <module>
    from . import menu, project, search, toolbar
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\app\pavlovia_ui\toolbar.py", line 4, in <module>
    from .. import icons
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\app\icons.py", line 18, in <module>
    from psychopy import experiment, prefs
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\experiment\__init__.py", line 21, in <module>
    from .params import getCodeFromParamStr, Param
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\experiment\params.py", line 28, in <module>
    from . import py2js
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\experiment\py2js.py", line 14, in <module>
    import esprima
ModuleNotFoundError: No module named 'esprima' 
```
I then followed the instructions for manually installing with Anaconda using python 3.6 and got the same issue, but could install esprima with pip.
So I did the same in the standalone beta8 with:
```cmd
C:\Program Files (x86)\PsychoPy3>python -m pip install esprima
Collecting esprima
Installing collected packages: esprima
  The script esprima.exe is installed in 'C:\Program Files (x86)\PsychoPy3\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed esprima-4.0.1
```
Which solved the problem and the start menu link worked resulting in the builder view.
Shouldn't be too hard to fix. :)

**Comment by peircej** [comment]
This is indeed fixed in 3.0.0b9. Sorry it was broken in beta8

**Comment by peircej** [comment]
(FYI I was hoping that beta9 would be released yesterday but it looks like it will be delayed for a week).

**Comment by peircej** [comment]
This is now fixed and released
