### ISSUE TITLE
Order of Psychopy Imports is Not Commutative

### ISSUE THREAD

**Issue by jacob-lee** [psychopy/psychopy#2007]
I am using an anaconda install of psychopy 3.0.0b4 using python3 on Mac OS 10.11.6

When running  a simple demo script, I found that importing from iohub after import psychopy's visual causes a crash with the following stack trace:

```
(anaconda-py3) L1L-C02JQ0A4F1G4:temp jacoblee$ pythonw demo_error.py
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
2018-09-07 15:34:56.601 python[1227:532738] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/t1/gfl4qg2j3b53z2b6m111dbxj85xtck/T/com.continuum.python.savedState
_addDeviceView: Error adding class. 
Traceback (most recent call last):
  File "/Users/jacoblee/anaconda3/envs/anaconda-py3/lib/python3.6/site-packages/psychopy/iohub/client/__init__.py", line 1056, in _addDeviceView
    dev_import_result = import_device(dev_mod_pth, dev_cls_name)
  File "/Users/jacoblee/anaconda3/envs/anaconda-py3/lib/python3.6/site-packages/psychopy/iohub/devices/__init__.py", line 985, in import_device
    module = __import__(module_path, fromlist=["{}".format(device_class_name)])
  File "/Users/jacoblee/anaconda3/envs/anaconda-py3/lib/python3.6/site-packages/psychopy/iohub/devices/keyboard/__init__.py", line 108, in <module>
    from .darwin import Keyboard
  File "/Users/jacoblee/anaconda3/envs/anaconda-py3/lib/python3.6/site-packages/psychopy/iohub/devices/keyboard/darwin.py", line 108, in <module>
    class Keyboard(ioHubKeyboardDevice):
  File "/Users/jacoblee/anaconda3/envs/anaconda-py3/lib/python3.6/site-packages/psychopy/iohub/devices/keyboard/darwin.py", line 114, in Keyboard
    (Qz.kCGEventFlagMaskAlphaShift, 'capslock'),
  File "/Users/jacoblee/anaconda3/envs/anaconda-py3/lib/python3.6/site-packages/objc/_lazyimport.py", line 163, in __getattr__
    raise AttributeError(name)
AttributeError: kCGEventFlagMaskAlphaShift
_addDeviceView: Error adding class. 
Traceback (most recent call last):
  File "/Users/jacoblee/anaconda3/envs/anaconda-py3/lib/python3.6/site-packages/psychopy/iohub/client/__init__.py", line 1056, in _addDeviceView
    dev_import_result = import_device(dev_mod_pth, dev_cls_name)
  File "/Users/jacoblee/anaconda3/envs/anaconda-py3/lib/python3.6/site-packages/psychopy/iohub/devices/__init__.py", line 985, in import_device
    module = __import__(module_path, fromlist=["{}".format(device_class_name)])
  File "/Users/jacoblee/anaconda3/envs/anaconda-py3/lib/python3.6/site-packages/psychopy/iohub/devices/mouse/__init__.py", line 399, in <module>
    from .darwin import Mouse
  File "/Users/jacoblee/anaconda3/envs/anaconda-py3/lib/python3.6/site-packages/psychopy/iohub/devices/mouse/darwin.py", line 12, in <module>
    from .. import Keyboard, Computer, Device
ImportError: cannot import name 'Keyboard'
ioHub Server Process Completed With Code:  `0`
```

The following is code to reproduce the issue:

demo_error.py
--------------
```
# This should crash with error
from psychopy import visual
from psychopy.iohub import launchHubServer

io = launchHubServer()
io.quit()
```

demo_noerror.py
-----------------
```
# This should work
from psychopy.iohub import launchHubServer
from psychopy import visual

io = launchHubServer()
io.quit()
```

**Comment by heuristicwondering** [comment]
I was also able to replicate your bug in an anaconda install of psychopy 3.0.3 using python3 on Ubuntu 16.04 Xenial

This may be a similar issue, but the order of Psychopy's sound import is also not commutative. Specifically with the modules visual, event, and info. It doesn't throw and error however but just seems to exit the program.

**will_work.py**
`# All of these import statements will work
print('The top')

from psychopy import sound, event
# from psychopy import sound, visual
# from psychopy import sound, info

print('The bottom')
`

**will_not_work.py**
`# None of these import statements will work
print('The top')

from psychopy import event, sound
# from psychopy import visual, sound
# from psychopy import info, sound

print('The bottom')
`

**Comment by peircej** [comment]
Thanks both for your input finding the places where things do/don't work

Both iohub and sound libs are going through some substantial rewriting right now and I'll hope that the changes we are making will fix these but I'm going to put off debugging them until we're done I think.

**Comment by isolver** [comment]
Using 2021.1.2, tested both:

```
from psychopy import event, sound
```

and 

```
from psychopy import visual
from psychopy.iohub import launchHubServer

io = launchHubServer()
io.quit()
```

on Ubuntu and both run without error and to completion, so these issues seem to have been fixed.
