### ISSUE TITLE
PIL.Image fail in combineImageEmblem

### ISSUE THREAD

**Issue by sherdim** [psychopy/psychopy#2029]
When launching 3.0.0.b in Windows

```
Traceback (most recent call last):
  File "C:\a\Python\Scripts\psychopyApp.py", line 96, in <module>
    start_app()
  File "C:\a\Python\Scripts\psychopyApp.py", line 28, in start_app
    app = PsychoPyApp(0, showSplash=showSplash)
  File "C:\a\Python\lib\site-packages\psychopy\app\_psychopyApp.py", line 181, in __init__
    self.onInit(testMode=testMode, **kwargs)
  File "C:\a\Python\lib\site-packages\psychopy\app\_psychopyApp.py", line 307, in onInit
    self.showCoder(fileList=scripts)
  File "C:\a\Python\lib\site-packages\psychopy\app\_psychopyApp.py", line 499, in showCoder
    files=fileList, app=self)
  File "C:\a\Python\lib\site-packages\psychopy\app\coder\coder.py", line 1426, in __init__
    self.makeToolbar()  # must be before the paneManager for some reason
  File "C:\a\Python\lib\site-packages\psychopy\app\coder\coder.py", line 2000, in makeToolbar
    pavButtons.addPavloviaTools(buttons=['pavloviaSync', 'pavloviaSearch', 'pavloviaUser', ])
  File "C:\a\Python\lib\site-packages\psychopy\app\pavlovia_ui\toolbar.py", line 33, in addPavloviaT
ools
    emblem=join(rc, emblem), pos='bottom_right'))
  File "C:\a\Python\lib\site-packages\psychopy\app\icons.py", line 69, in combineImageEmblem
    main.paste(emblem, [x, y], mask=emblem)
  File "C:\a\Python\lib\site-packages\PIL\Image.py", line 1339, in paste
    box = box + (box[0]+size[0], box[1]+size[1])
TypeError: can only concatenate list (not "tuple") to list
```

Is fixed by change of brackets at psychopy\app\icons.py:69 :
`
main.paste(emblem, [x, y], mask=emblem)`

to 
`
main.paste(emblem, (x, y), mask=emblem)`

**Comment by peircej** [comment]
Thanks. That's interesting. I wonder why I haven't encountered that problem myself. What version of Python and wx are you using, or is this on the standalone install?

**Comment by peircej** [comment]
Or PIL version (wx version won't be relevant)?

**Comment by sherdim** [comment]
Python: 2.7.14   on Windows 10

PIL: 
Name: Pillow
Version: 2.9.0
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.github.io/

**Comment by peircej** [comment]
Ah, OK, yes pillow is now at version 5.2 so yours is quite old. This is probably something they've made more tolerant in recent versions. I'll add your fix too though (and similar change later in the icons file)
