### ISSUE TITLE
wx._core.PyNoAppError after creating a second Dlg

### ISSUE THREAD

**Issue by Kodiologist** [psychopy/psychopy#2063]
On PsychoPy 30066a5, Python 2.7.15rc1, wxPython 3.0.2.0, wxWidgets 3.0.4, and Ubuntu 18.04, the following crashes at the second call to `Dlg`.

    import psychopy.gui.wxgui

    dialog = psychopy.gui.wxgui.Dlg(title = 'win 1')
    dialog.addText('text 1')
    dialog.show()

    dialog = psychopy.gui.wxgui.Dlg(title = 'win 2')
    dialog.addText('text 2')
    dialog.show()

The backtrace is:

    Traceback (most recent call last):
      File "/tmp/foo.py", line 7, in <module>
        dialog = psychopy.gui.wxgui.Dlg(title = 'win 2')
      File "/usr/local/lib/python2.7/dist-packages/psychopy/gui/wxgui.py", line 78, in __init__
        super().__init__(parent=None, id=-1, title=title, style=style, pos=pos)
      File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_windows.py", line 734, in __init__
        _windows_.Dialog_swiginit(self,_windows_.new_Dialog(*args, **kwargs))
    wx._core.PyNoAppError: The wx.App object must be created first!

The workaround is to say `x = wx.App()` first. Oddly, `psychopy.gui.wxgui.ensureWxApp` doesn't seem to help, whether `Dlg` calls it internally or I call it manually, nor does assigning the `wx.App` to `psychopy.gui.wxgui.app` instead of a variable in the same module.

**Comment by peircej** [comment]
The solution here is simply to use PyQt. On Python3, PyQt5 really easy to install and doesn't have the problems that wxPython does

**Comment by Kodiologist** [comment]
If I were starting from scratch, I'd use PyQt, but I'm not eager to learn a new GUI library and rewrite my code working directly with wxWidgets, of which I have a lot at this point.

**Comment by Kodiologist** [comment]
I know, I'm back to Python 2 for now. :(
