### ISSUE TITLE
lazy_import conflict when using iohub

### ISSUE THREAD

**Issue by ariekahn** [psychopy/psychopy#2079]
When I try to launch iohub on master, I run into an exception which seems like a conflict between `iohub/lazy_import.py` and the external version (being called in `psychopy/__init__.py`.

Renaming the internal version to something like iohub_lazy_import.py fixes the issue, but seems kinda messy.

Not an issue when I import `psychopy.iohub` directly, presumably because of search path differences?

```
Python 3.7.0 (default, Aug 26 2018, 12:45:31)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import psychopy

In [2]: import psychopy.iohub

In [3]: from psychopy.iohub import launchHubServer

In [4]: io = launchHubServer()
Traceback (most recent call last):
  File "/Users/ari/.pyenv/versions/3.7.0/envs/psychopy/lib/python3.7/site-packages/psychopy/iohub/launchHubProcess.py", line 17, in <module>
    import iohub
ModuleNotFoundError: No module named 'iohub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ari/.pyenv/versions/3.7.0/envs/psychopy/lib/python3.7/site-packages/psychopy/iohub/launchHubProcess.py", line 26, in <module>
    import psychopy.iohub
  File "/Users/ari/.pyenv/versions/3.7.0/envs/psychopy/lib/python3.7/site-packages/psychopy/__init__.py", line 52, in <module>
    git = lazy_import.lazy_module("git")
AttributeError: module 'lazy_import' has no attribute 'lazy_module'
```

**Comment by peircej** [comment]
Actually I'm reverting this dependency on the (external) lazy_import anyway. 

The reason it was in was because of git on mac. On mac, when we try to import git to see if it's installed, it brings up a system dialog box telling the user to install xcode, which is really annoying when most of the time we don't need it (e.g. unless syncing with pavlovia). This lazy_import module has the ability to tag something as lazy early on (during `__init__`) and that will be respected by submodules (cool!).

BUT:

- this module also has the disadvantage that it prevents people from creating subclasses for that same reason (there is no way to import "not-lazy" having designated the class/module as lazy so subclasses always fail).
- I've just been removing the use of git altogether in favour of [dulwich](https://github.com/dulwich/dulwich). This allows us not to need any local install of git which gets rid of he problem that lazy_import was needed for.

I'm still testing/troubleshooting the dulwich solution but I believe it's going to work very well. I'm sure for massive projects the performance will be slightly worse than C-based git but for most purposes this won't be a problem and the advantages of being pure-python are substantial.

You can see the progress at
https://github.com/peircej/psychopy/tree/dulwich

**Comment by iancharest** [comment]
I actually have similar issues trying to setup for use of iohub in our experiments. 

I have detailed my install in https://github.com/psychopy/psychopy/issues/2082

In the coder, when I run the launchHub demo:

```python
Welcome to PsychoPy3!
v3.0.0b11

##### Running: /home/adf/charesti/Documents/GitHub/psychopy/psychopy/demos/coder/iohub/launchHub.py #####

------------------------------------

Running testWithNoKwargs Test:
Warning: msgpack_numpy could not be imported. This may cause issues for iohub.
Traceback (most recent call last):
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/iohub/launchHubProcess.py", line 17, in <module>
    import iohub
ModuleNotFoundError: No module named 'iohub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/iohub/launchHubProcess.py", line 26, in <module>
    import psychopy.iohub
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/__init__.py", line 52, in <module>
    git = lazy_import.lazy_module("git")
AttributeError: module 'lazy_import' has no attribute 'lazy_module'
ioHub Server Process Completed With Code:  1
Traceback (most recent call last):
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/demos/coder/iohub/launchHub.py", line 158, in <module>
    result = namespace[test]()
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/demos/coder/iohub/launchHub.py", line 27, in testWithNoKwargs
    io = launchHubServer()
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/contrib/lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/iohub/client/connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/iohub/client/__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server
```
when I try the same thing i ipython (notice the additional warning about msgpack_numpy)

```python
~/Documents/GitHub/psychopy/psychopy/demos/coder/iohub$ ipython
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import psychopy                                                         

In [2]: import psychopy.iohub                                                   

In [3]: from psychopy.iohub import launchHubServer                              

In [4]: io = launchHubServer()                                                  
Warning: msgpack_numpy could not be imported. This may cause issues for iohub.
Traceback (most recent call last):
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/iohub/launchHubProcess.py", line 17, in <module>
    import iohub
ModuleNotFoundError: No module named 'iohub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/iohub/launchHubProcess.py", line 26, in <module>
    import psychopy.iohub
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/__init__.py", line 52, in <module>
    git = lazy_import.lazy_module("git")
AttributeError: module 'lazy_import' has no attribute 'lazy_module'
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-4-18ae25f6b059> in <module>
----> 1 io = launchHubServer()

~/Documents/GitHub/psychopy/psychopy/contrib/lazy_import.py in __call__(self, *args, **kwargs)
    118     def __call__(self, *args, **kwargs):
    119         obj = object.__getattribute__(self, '_resolve')()
--> 120         return obj(*args, **kwargs)
    121 
    122 

~/Documents/GitHub/psychopy/psychopy/iohub/client/connect.py in launchHubServer(**kwargs)
    299     #print('ioHubConnection(iohub_config):')
    300     #pprint.pprint(iohub_config)
--> 301     return ioHubConnection(iohub_config)

~/Documents/GitHub/psychopy/psychopy/iohub/client/__init__.py in __init__(self, ioHubConfig, ioHubConfigAbsPath)
    286         self._cv_order = None
    287 
--> 288         self.iohub_status = self._startServer(ioHubConfig, ioHubConfigAbsPath)
    289         if self.iohub_status != 'OK':
    290             raise RuntimeError('Error starting ioHub server')

~/Documents/GitHub/psychopy/psychopy/iohub/client/__init__.py in _startServer(self, ioHubConfig, ioHubConfigAbsPath)
    970         # If ioHub server did not respond correctly,
    971         # terminate process and exit the program.
--> 972         if self._waitForServerInit() is False:
    973             self._server_process.terminate()
    974             return "ioHub startup failed."

~/Documents/GitHub/psychopy/psychopy/iohub/client/__init__.py in _waitForServerInit(self)
   1017         timeout_time = Computer.getTime() + timeout_duration
   1018         while hubonline is False and Computer.getTime() < timeout_time:
-> 1019             r = self._sendToHubServer(['GET_IOHUB_STATUS', ])
   1020             if r:
   1021                 hubonline = r[1] == 'RUNNING'

~/Documents/GitHub/psychopy/psychopy/iohub/client/__init__.py in _sendToHubServer(self, tx_data)
   1114             # wait for response from ioHub server, which will be the
   1115             # result data and iohub server address (ip4,port).
-> 1116             result = self.udp_client.receive()
   1117             if result:
   1118                 result, _ = result

~/Documents/GitHub/psychopy/psychopy/iohub/net.py in receive(self)
     81     def receive(self):
     82         try:
---> 83             data, address = self.sock.recvfrom(self._rcvBufferLength)
     84             self.lastAddress = address
     85             self.feed(data)

KeyboardInterrupt: 

```


any advice on how to fix this would be greatly appreciated!

**Comment by peircej** [comment]
Well the quick workaround while you wait for the fix is to delete the line in `psychopy.__init__` about making git a lazy import so that gitpython is directly imported. Then you'll need to make sure that you have gitpython and git installed, of course. The idea of the lazy import, where the clash is occurring is to allow the application to at least run without git being present

**Comment by peircej** [comment]
Yes, literally just that

**Comment by peircej** [comment]
I believe this has been resolved. I removed any dependency on the lazy_import package
