### ISSUE TITLE
The GLFW library is not initialized

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#2089]
In PsychoPy 3.0.0b11, exiting the application with an open GLFW window causes the following error...

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\mdc\AppData\Local\Programs\Python\Python36\lib\site-packages\glfw\__init__.py", line 611, in callback_wrapper
    return func(*args, **kwargs)
  File "C:\Users\mdc\AppData\Local\Programs\Python\Python36\lib\site-packages\glfw\__init__.py", line 785, in _raise_glfw_errors_as_exceptions
    raise GLFWError(message)
glfw.GLFWError: (65537) b'The GLFW library is not initialized'
```

when running ...

```
...
while 1:
    grating.draw()
    win.flip()

    if event.getKeys(['q']):
        break

core.quit()
```

It seems to be caused by recent changes to how the GLFW backend handles closing windows. We may need to modify the registered 'atexit' function 'close_on_exit' associated with the window class to fix this problem.

**Comment by gitouni** [comment]
I met this problem when use open3d in remote ssh mode
`from open3d.web_visualizer import draw`
comment this line will tackle this problem.
