### ISSUE TITLE
iohub "TypeError: ord() expected string of length 1, but int found"

### ISSUE THREAD

**Issue by iancharest** [psychopy/psychopy#2092]
trying to launch iohub
```python
 io = launchHubServer()
```
results in errors in python 3.6

```python
Exception in thread Thread-1:                                          
Traceback (most recent call last):
  File "/home/adf/charesti/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/iohub/devices/pyXHook.py", line 236, in run
    self.record_dpy.record_enable_context(self.ctx, self.processevents)
  File "/home/adf/charesti/anaconda3/lib/python3.6/site-packages/Xlib/ext/record.py", line 243, in enable_context
    context = context)
  File "/home/adf/charesti/anaconda3/lib/python3.6/site-packages/Xlib/ext/record.py", line 220, in __init__
    rq.ReplyRequest.__init__(self, *args, **keys)
  File "/home/adf/charesti/anaconda3/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/home/adf/charesti/anaconda3/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1381, in reply
    self._display.send_and_recv(request = self._serial)
  File "/home/adf/charesti/anaconda3/lib/python3.6/site-packages/Xlib/protocol/display.py", line 613, in send_and_recv
    gotreq = self.parse_response(request)
  File "/home/adf/charesti/anaconda3/lib/python3.6/site-packages/Xlib/protocol/display.py", line 705, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/home/adf/charesti/anaconda3/lib/python3.6/site-packages/Xlib/protocol/display.py", line 793, in parse_request_response
    req._parse_response(self.data_recv[:self.recv_packet_len])
  File "/home/adf/charesti/anaconda3/lib/python3.6/site-packages/Xlib/ext/record.py", line 224, in _parse_response
    self._callback(r)
  File "/home/adf/charesti/Documents/GitHub/psychopy/psychopy/iohub/devices/pyXHook.py", line 294, in processevents
    if not len(reply.data) or ord(reply.data[0]) < 2:
TypeError: ord() expected string of length 1, but int found
```

**Comment by isolver** [comment]
this should no longer be an issue in python 3.x.
