### ISSUE TITLE
Problem syncing

### ISSUE THREAD

**Issue by FearghalHughes** [psychopy/psychopy#2218]
Hi there,

I am having a difficult time synchronising my experiment, the following code comes up: 

Pushing files to PavloviaTraceback (most recent call last):
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/app/pavlovia_ui/project.py", line 470, in syncProject
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/projects/pavlovia.py", line 773, in firstPush
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 548, in <lambda>
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 1014, in _call_process
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 825, in execute
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git push -u origin master
  stderr: 'fatal: could not read Username for 'https://gitlab.pavlovia.org': Device not configured'

I have seen another post on this forum containing a similar error but unfortunately this did not help me, I'm not particularly good at computers/coding so solutions would have to be in very basic English. Time is against me currently, a quick response would be much appreciated – thanks.

**Comment by peircej** [comment]
Could you confirm what version of PsychoPy you're using? This was a problem before, but I believe this has been fixed in recent releases.

**Comment by FearghalHughes** [comment]
Thanks for the response - it's v3.0.0b11

**Comment by peircej** [comment]
I'm closing this for now. Reopen if it turns out things are still broken with the new version

**Comment by FearghalHughes** [comment]
Here is a link to it on gitlab – https://gitlab.pavlovia.org/FearghalHughes/Alpha . I'm not sure if this will help, if not please let me know what to post, thanks.
