### ISSUE TITLE
iohub launchHub demo results in error

### ISSUE THREAD

**Issue by LKPsychology** [psychopy/psychopy#2224]
In PsychoPy v3.0.2, the coder demo launchHub.py results in the following error.

`##### Running: C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\demos\coder\iohub\launchHub.py #####

------------------------------------

Running testWithNoKwargs Test:

 ** PRESS A KEY TO CONTINUE.....
A Keyboard Event was Detected; exiting Test.
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testUsingPsychoPyMonitorConfig Test:
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'width': 300.0, 'height': 168.75, 'unit_type': b'mm'}
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testEnabledDataStore Test:
Traceback (most recent call last):
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\demos\coder\iohub\launchHub.py", line 158, in <module>
    result = namespace[test]()
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\demos\coder\iohub\launchHub.py", line 89, in testEnabledDataStore
    experiment_code=exp_code)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\iohub\client\connect.py", line 301, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\iohub\client\__init__.py", line 290, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server
ioHub Server Process Completed With Code:  1
`

**Comment by hoechenberger** [comment]
The datastore currently does not work with Python 3, sorry. We're working on it.

**Comment by isolver** [comment]
Fixed, @peircej please close.

**Comment by peircej** [comment]
Sol's fix was included in release 3.0.6
