### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt4'

### ISSUE THREAD

**Issue by kurokida** [psychopy/psychopy#2375]
I installed PsychoPy 3.0.6 in Mac OS 10.9.5, and I noticed a ModuleNotFoundError when I run an initial program.

The error messages are follows.

 Running: /Users/jikkenyou/Desktop/USER/myName/untitled folder 2/untitled_lastrun.py 
Traceback (most recent call last):
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/gui/qtgui.py", line 15, in <module>
    from PyQt4 import QtGui  
ModuleNotFoundError: No module named 'PyQt4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jikkenyou/Desktop/USER/myName/untitled folder 2/untitled_lastrun.py", line 14, in <module>
    from psychopy import locale_setup, sound, gui, visual, core, data, event, logging, clock
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/gui/__init__.py", line 33, in <module>
    from .qtgui import *
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/gui/qtgui.py", line 19, in <module>
    from PyQt5 import QtWidgets
ImportError: dlopen(/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/PyQt5/QtWidgets.so, 2): Symbol not found: _LSCopyDefaultApplicationURLForURL
  Referenced from: /Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
 in /Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore

**************************
PsychoPy 3.0.6 is working in Mac OS 10.13.6 and 10.14.3.
Is 10.9.5 too old? 
Can I use the latest PsychoPy in the old Mac?

**Comment by peircej** [comment]
Ah. It looks like the version of PyQt we provided is too new for MacOS 10.9:
  https://doc.qt.io/archives/qt-5.10/supported-platforms-and-configurations.html

In the next release I'll package PyQt 5.8 instead which should be more widely compatible.

**Comment by kurokida** [comment]
Thanks a lot!
I am waiting for the new release one.

**Comment by grudeng2** [comment]
Seeing same error on Windows 10 build 1803.

**Comment by peircej** [comment]
@grudeng2 that's stranger because the PyQt page doesn't mention any Win10 incompatibilities. 
Could you go to the shell in PsychoPy's coder view and do 
```
import PyQt5
from PyQt5 import QtWidgets
from PyQt5 import QtGui
```
and let me know any errors (if the first fails the other 2 are irrelevant)? Thanks

**Comment by peircej** [comment]
This is even more confusing. I've checked on a Wind10 1803 virtual box. The gui demo runs fine and the import commands above are fine, so currently I can't reproduce the issue on windows

**Comment by TEParsons** [comment]
I'll close this but if you're still getting errors importing PyQt please reopen
