### ISSUE TITLE
No module named click error with OpenCV movie playback (3.0.7 Py27 Win 32)

### ISSUE THREAD

**Issue by frankgasking** [psychopy/psychopy#2385]
Testing 3.0.7 Py27 Win 32,  when you run any video using OpenCV as the playback method - you get the following error message:

Traceback (most recent call last):
  File "C:\Users\fg30\Desktop\PsychoPy3TestBed\12372_kcdu_video_study\experiment_lastrun.py", line 473, in <module>
    depth=0.0,
  File "C:\Program Files (x86)\PsychoPy3_PY2\lib\site-packages\psychopy\contrib\lazy_import.py", line 119, in __call__
    obj = object.__getattribute__(self, '_resolve')()
  File "C:\Program Files (x86)\PsychoPy3_PY2\lib\site-packages\psychopy\contrib\lazy_import.py", line 88, in _resolve
    obj = factory(self, scope, name)
  File "C:\Program Files (x86)\PsychoPy3_PY2\lib\site-packages\psychopy\contrib\lazy_import.py", line 203, in _import
    module = __import__(module_python_path, scope, scope, [member], level=0)
  File "C:\Program Files (x86)\PsychoPy3_PY2\lib\site-packages\psychopy\visual\movie2.py", line 121, in <module>
    raise err
ImportError: No module named click

The OpenCV test on the other ticket at https://github.com/psychopy/psychopy/files/2966389/OpenCVTest.zip will demonstrate the issue.

**Comment by peircej** [comment]
The 'click' error should be fixed here: https://github.com/psychopy/psychopy/releases/tag/3.1.0
