### ISSUE TITLE
pyglet 1.4 causes exception on Windows 10

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#2399]
When running python setup.py install, psychopy installed pyglet 1.4.x. However running sysInfo.py demo gives the following error:

```
PsychoPy 3.1.0
Traceback (most recent call last):
  File "sysInfo.py", line 41, in <module>
    win = visual.Window([100, 100])  # some drivers want a window open first
  File "D:\DEV\WinPython3.5_64\python-3.5.4.amd64\lib\site-packages\psychopy-3.1.0-py3.5.egg\psychopy\visual\window.py", line 389, in __init__
    self.backend = backends.getBackend(win=self, *args, **kwargs)
  File "D:\DEV\WinPython3.5_64\python-3.5.4.amd64\lib\site-packages\psychopy-3.1.0-py3.5.egg\psychopy\visual\backends\__init__.py", line 32, in getBackend
    return Backend(win, *args, **kwargs)
  File "D:\DEV\WinPython3.5_64\python-3.5.4.amd64\lib\site-packages\psychopy-3.1.0-py3.5.egg\psychopy\visual\backends\pygletbackend.py", line 101, in __init__
    defDisp = pyglet.window.get_platform().get_default_display()
AttributeError: module 'pyglet.window' has no attribute 'get_platform'
4.8531  WARNING         Monitor specification not found. Creating a temporary one...
Exception ignored in: <bound method Window.__del__ of <psychopy.visual.window.Window object at 0x0000017B06D62D30>>
Traceback (most recent call last):
  File "D:\DEV\WinPython3.5_64\python-3.5.4.amd64\lib\site-packages\psychopy-3.1.0-py3.5.egg\psychopy\visual\window.py", line 501, in __del__
    self.close()
  File "D:\DEV\WinPython3.5_64\python-3.5.4.amd64\lib\site-packages\psychopy-3.1.0-py3.5.egg\psychopy\visual\window.py", line 1327, in close
    self.backend.close()  # moved here, dereferencing the window prevents
AttributeError: 'NoneType' object has no attribute 'close'
```

Uninstalling pyglet 1.4.0b1 and installing 1.3.2 using:

```
pip install pyglet
```

fixes the issue:

```
d:\DEV\my-code\psychopy\psychopy\demos\coder>python sysInfo.py
Paths to files on the system:
    userPrefsFile: C:\Users\sol\AppData\Roaming\psychopy3\userPrefs.cfg
    appDataFile: C:\Users\sol\AppData\Roaming\psychopy3\appData.cfg
    demos: D:\DEV\WinPython3.5_64\python-3.5.4.amd64\lib\site-packages\psychopy-3.1.0-py3.5.egg\psychopy\demos
    appFile: D:\DEV\WinPython3.5_64\python-3.5.4.amd64\lib\site-packages\psychopy-3.1.0-py3.5.egg\psychopy\app\PsychoPy.py

System info:
Windows-10-10.0.17763-SP0

Python info
D:\DEV\WinPython3.5_64\python-3.5.4.amd64\python.exe
3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
numpy 1.13.3
scipy 1.0.1
matplotlib 2.2.2
pyglet 1.3.2
pyo [not installed]

PsychoPy 3.1.0
have shaders: True

OpenGL info:
vendor: NVIDIA Corporation
rendering engine: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2
OpenGL version: 4.6.0 NVIDIA 419.67
(Selected) Extensions:
         True GL_ARB_multitexture
         True GL_EXT_framebuffer_object
         True GL_ARB_fragment_program
         True GL_ARB_shader_objects
         True GL_ARB_vertex_shader
         True GL_ARB_texture_non_power_of_two
         True GL_ARB_texture_float
         False GL_STEREO
        max vertices in vertex array: 1048576
```

**Comment by hoechenberger** [comment]
Closing in favor of #2518

**Comment by DingkunLiu** [comment]
Installing pyglet<=1.3 did not work for me.

```pygame 1.9.6  
Hello from the pygame community. https://www.pygame.org/contribute.html
Paths to files on the system:
    userPrefsFile: C:\Users\liudk\AppData\Roaming\psychopy3\userPrefs.cfg
    appDataFile: C:\Users\liudk\AppData\Roaming\psychopy3\appData.cfg
    demos: C:\Users\liudk\.conda\envs\py36\lib\site-packages\psychopy\demos
    appFile: C:\Users\liudk\.conda\envs\py36\lib\site-packages\psychopy\app\PsychoPy.py

System info:
Windows-10-10.0.18362-SP0

Python info
C:\Users\liudk\.conda\envs\py36\python.exe
3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
numpy 1.17.0
scipy 1.3.1
matplotlib 3.0.3
pyglet 1.3.2
pyo [not installed]

PsychoPy 3.1.5
Traceback (most recent call last):
  File ".\sysInfo.py", line 41, in <module>
    win = visual.Window([100, 100])  # some drivers want a window open first
  File "C:\Users\liudk\.conda\envs\py36\lib\site-packages\psychopy\visual\window.py", line 389, in __init__
    self.backend = backends.getBackend(win=self, *args, **kwargs)
  File "C:\Users\liudk\.conda\envs\py36\lib\site-packages\psychopy\visual\backends\__init__.py", line 32, in getBackend
    return Backend(win, *args, **kwargs)
  File "C:\Users\liudk\.conda\envs\py36\lib\site-packages\psychopy\visual\backends\pygletbackend.py", line 227, in __init__
    self._origGammaRamp = self.getGammaRamp()
  File "C:\Users\liudk\.conda\envs\py36\lib\site-packages\psychopy\visual\backends\pygletbackend.py", line 329, in getGammaRamp
    return getGammaRamp(self.screenID, self.xDisplay)
  File "C:\Users\liudk\.conda\envs\py36\lib\site-packages\psychopy\visual\backends\gamma.py", line 128, in getGammaRamp
    raise AssertionError('GetDeviceGammaRamp failed')
AssertionError: GetDeviceGammaRamp failed
1.2735  WARNING         Monitor specification not found. Creating a temporary one...
Exception ignored in: <bound method Window.__del__ of <psychopy.visual.window.Window object at 0x000001CF8FEA6668>>
Traceback (most recent call last):
  File "C:\Users\liudk\.conda\envs\py36\lib\site-packages\psychopy\visual\window.py", line 501, in __del__
    self.close()
  File "C:\Users\liudk\.conda\envs\py36\lib\site-packages\psychopy\visual\window.py", line 1327, in close
    self.backend.close()  # moved here, dereferencing the window prevents
AttributeError: 'NoneType' object has no attribute 'close'```

**Comment by DingkunLiu** [comment]
Looking forward to your reply! Thanks!
