### ISSUE TITLE
Psychopy fails on Linux without wxPython

### ISSUE THREAD

**Issue by rkcf** [psychopy/psychopy#2418]
I am packaging psychopy for Archlinux and have come across a problem where Psychopy fails to run without wxPython installed.

The requirements in setup.cfg stops wxPython from being installed on linux systems.
https://github.com/psychopy/psychopy/blob/6977e9dba33f4903e26bb8ced0735b96a463e262/setup.cfg#L71
When I try to run psychopy without wxPython it fails to start with:
```
 Traceback (most recent call last):
  File ".venv/bin/psychopy", line 10, in <module>
    sys.exit(main())
  File ".venv/lib/python3.7/site-packages/psychopy/app/psychopyApp.py", line 100, in main
    start_app()
  File ".venv/lib/python3.7/site-packages/psychopy/app/psychopyApp.py", line 22, in start_app
     from psychopy.app._psychopyApp import PsychoPyApp
  File ".venv/lib/python3.7/site-packages/psychopy/app/_psychopyApp.py", line 30, in <module>
     import wx
 ModuleNotFoundError: No module named 'wx'
```

After installing wxPython with `pip install wxPython` Psychopy is able to start.

## Version Info ##
```
$ python --version
Python 3.7.3

$ python .venv/bin/psychopy -v
PsychoPy3, version 3.0.7 (c)Jonathan Peirce 2018, GNU GPL license

$ pip freeze
arabic-reshaper==2.0.14
asn1crypto==0.24.0
astunparse==1.6.2
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
configparser==3.7.4
cryptography==2.6.1
cycler==0.10.0
decorator==4.4.0
esprima==4.0.1
et-xmlfile==1.0.1
freetype-py==2.1.0.post1
future==0.17.1
gevent==1.4.0
gitdb2==2.0.5
GitPython==2.1.11
greenlet==0.4.15
idna==2.8
imageio==2.5.0
imageio-ffmpeg==0.3.0
jdcal==1.4.1
json-tricks==3.13.1
kiwisolver==1.0.1
matplotlib==3.0.3
mock==2.0.0
moviepy==1.0.0
msgpack==0.6.1
msgpack-numpy==0.4.4.2
msgpack-python==0.5.6
numexpr==2.6.9
numpy==1.16.3
opencv-python==4.1.0.25
openpyxl==2.6.2
pandas==0.24.2
pbr==5.1.3
Pillow==6.0.0
proglog==0.1.9
psutil==5.6.1
PsychoPy==3.0.7
pycparser==2.19
pygame==1.9.5
pyglet==1.3.2
PyOpenGL==3.1.0
pyOpenSSL==19.0.0
pyosf==1.0.5
pyparallel==0.2.2
pyparsing==2.4.0
PyQt5==5.12.1
PyQt5-sip==4.19.15
pyserial==3.4
python-bidi==0.4.0
python-dateutil==2.8.0
python-gitlab==1.8.0
pytz==2019.1
PyYAML==5.1
pyzmq==18.0.1
requests==2.21.0
scipy==1.2.1
six==1.12.0
smmap2==2.0.5
sounddevice==0.3.13
SoundFile==0.10.2
tables==3.5.1
tqdm==4.31.1
urllib3==1.24.2
xlrd==1.2.0
```

## Steps to Reproduce ##
```
wget https://github.com/psychopy/psychopy/archive/3.0.7.tar.gz
tar xvf 3.0.7.tar.gz
cd psychopy-3.0.7
virtualenv .venv
. .venv/bin/activate
pip install .
python .venv/bin/psychopy
```

**Comment by peircej** [comment]
You **do definitely** need wxPython, but it can't be installed using the requirements file because you have to fetch and download the right version for your system from here:
https://extras.wxpython.org/wxPython4/extras/linux/gtk3/

They haven't managed to make a single wheel that supports multiple linux flavours yet
