### ISSUE TITLE
Microphone and voice key are not working

### ISSUE THREAD

**Issue by minnie2112** [psychopy/psychopy#2488]
Dear all, 

I am using Psychopy 3.1.2 Standalone on Windows 10 (64 bit) to design a naming experiment where the voice of the participants should be recorded and onset time should be measured with the help of the voice key. Unfortunately, the experiment is not running. I always receive the following warning message:

> 21.1213     WARNING     Starting Microphone but sound lib preference is set to be ['sounddevice', 'pyo', 'pygame']. Clashes might occur since 'pyo' is not preferred lib but is needed for Microphone

There are a couple of error messages that refer to the lines where the microphone is activated or where the sound file should be saved. 

>  File "C:\FAU\PhD dissertation\Phd_data\new_experiment\final_experiment\voice_key.py", line 261, in <module>
    mic_1.record(sec=2.0, block=False)  # start the recording thread
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\microphone.py", line 398, in record
    self.filename = self._record(sec, filename=filename, block=block)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\microphone.py", line 249, in _record
    self.recorder.run(self.savedFile, self.duration, **self.options)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\microphone.py", line 117, in run
    inputter = pyo.Input(chnl=chnl, mul=1)

I would be grateful if someone could help me to launch the experiment.

**Comment by peircej** [comment]
The warning message that you see is telling you what to do. Your sound settings are set to prioritise sounddevice over pyo, but pyo is needed for the microphone. Change your preferences to use the sound lib like this:
```['pyo', 'sounddevice', 'pygame']```
If that doesn't fix the other message then let us know what the message is (here, in this issue)
thanks, Jon

**Comment by minnie2112** [comment]
Thank you for your answer. The warning message has disappeared but the experiment is still not running. I have only three components in each trial, a text one - containing one single word, the microphone, which is set to 2 seconds, and the keyboard to move to the next trial.

**Comment by peircej** [comment]
> The warning message has disappeared but the experiment is still not running. 

And is there still an error message? Or nothing at all? At what point does it fail?

**Comment by minnie2112** [comment]
There is first error message leads to the activation of the microphone:
`# *mic_1* updates
    if t >= 0.0 and mic_1.status == NOT_STARTED:
        # keep track of start time/frame for later
        mic_1.tStart = t  # not accounting for scr refresh
        mic_1.frameNStart = frameN  # exact frame index
        win.timeOnFlip(mic_1, 'tStartRefresh')  # time at next scr refresh
        mic_1.status = STARTED
        mic_1.record(sec=2.0, block=False)  # start the recording thread`

The last line causes the problem, according to the traceback.

**Comment by peircej** [comment]
Please copy and paste **the entire** error message or we have to just guess what the problem is!

**Comment by minnie2112** [comment]
> Traceback (most recent call last):
  File "C:\FAU\PhD dissertation\Phd_data\new_experiment\final_experiment\voice_key.py", line 265, in <module>
    mic_1.record(sec=2.0, block=False)  # start the recording thread
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\microphone.py", line 398, in record
    self.filename = self._record(sec, filename=filename, block=block)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\microphone.py", line 249, in _record
    self.recorder.run(self.savedFile, self.duration, **self.options)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\microphone.py", line 117, in run
    inputter = pyo.Input(chnl=chnl, mul=1)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\pyo\lib\generators.py", line 420, in __init__
    pyoArgsAssert(self, "iOO", chnl, mul, add)
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\pyo\lib\_core.py", line 503, in pyoArgsAssert
    raise PyoArgumentTypeError(err % (i, name, expected, argtype))
pyo.lib._core.PyoArgumentTypeError: bad argument at position 0 to "Input" (integer expected, got <class 'str'>)

These are all the  error messages

**Comment by minnie2112** [comment]
Yes, the issue the same but no answer is given there

**Comment by peircej** [comment]
Yes, clearly the issue apparently remains and needs sorting out, but asking the question again as a new issue just makes things confusing. You can follow along on that issue and when it gets fixed will update there.

**Comment by peircej** [comment]
The issue is fixed in the repository and we'll hopefully have a bug-fix release out soon but, in the meantime, you could potentially apply the changes seen in https://github.com/psychopy/psychopy/commit/b262fba343f5d733665b5f7d4a5db9b81ca2c283 to your own installation and hopefully you'll be able to get going again
