### ISSUE TITLE
Installation error on Ubuntu

### ISSUE THREAD

**Issue by gbrookshire** [psychopy/psychopy#2802]
After installing Psychopy on Ubuntu 18.04, I get an error when trying to start the GUI. This error occurs whether I've installed using pip or conda.

Other details of the installation are included in issue #2664 

```
$ psychopy
Traceback (most recent call last):
  File "/home/local/ADF/brookshg/anaconda3/envs/psychopy/bin/psychopy", line 11, in <module>
    sys.exit(main())
  File "/home/local/ADF/brookshg/anaconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/psychopyApp.py", line 100, in main
    start_app()
  File "/home/local/ADF/brookshg/anaconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/psychopyApp.py", line 22, in start_app
    from psychopy.app._psychopyApp import PsychoPyApp
  File "/home/local/ADF/brookshg/anaconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/_psychopyApp.py", line 31, in <module>
    import wx
  File "/home/local/ADF/brookshg/.local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/local/ADF/brookshg/.local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /home/local/ADF/brookshg/anaconda3/envs/psychopy/bin/../lib/libgio-2.0.so.0: undefined symbol: g_spawn_async_with_fds
```

**Comment by hoechenberger** [comment]
I will try to look into this until the end of this week

**Comment by peircej** [comment]
Looks like conda needs a different (newer?) version of glib?
https://www.linuxquestions.org/questions/linux-software-2/apparent-glib-libgio-2-0-errors-during-make-860164/

**Comment by TEParsons** [comment]
Closing as not planned; now we have PsychoPy Studio which is installable via a `.AppImage` file
