### ISSUE TITLE
Translating new strings

### ISSUE THREAD

**Issue by hsogo** [psychopy/psychopy#2811]
I pulled the latest master branch and found there are several untranslated new strings in menus and dialog boxes.  I have some questions on translation.

1. Should **Runner** view be untranslated?

We decided that Coder and Builder should be untranslated when internationalization of user interface was started.  It looks that new Runner view is comparable UI to the Builder and Coder.  If so, I think that Runner should not be translated.  What do you think?

2. How should return strings of `psychopy.experiment.exports.NameSpace.isPossibleDerivable()`  be translated?

When "this" is used as the component name, Builder warns us not to use "this" as the name.  This message is not translated.

![1](https://user-images.githubusercontent.com/2094930/74915142-0b575b00-5407-11ea-9c20-dd5a98a8e1f3.png)

I searched this string from source codes and found at `NameSpace.isPossibleDerivable()` in psychopy/experiment/exports.py.  

```
    def isPossiblyDerivable(self, name):
        """catch all possible derived-names, regardless of whether currently
        """
        derivable = (name.startswith('this') or
                     name.startswith('these') or
                     name.startswith('continue') or
                     name.endswith('Clock') or
                     name.lower().find('component') > -1)
        if derivable:
            return (" Avoid `this`, `these`, `continue`, `Clock`,"
                    " or `component` in name")
        return None
```

This function is called as follows (in psychopy/app/builder/dialogs/\_\_init\_\_.py).

```
            elif namespace.isPossiblyDerivable(newName):
                msg = namespace.isPossiblyDerivable(newName)
                return namespace._localized[msg], True
```

`namespace._localized` is defined as (in psychopy/experiment/exports.py)

```
        toTranslate = [
            "one of your Components, Routines, or condition parameters",
            " Avoid `this`, `these`, `continue`, `Clock`, or `component` in name",
            "Builder variable",
            "Psychopy module",
            "numpy function",
            "python keyword"
        ]
        self._localized = {None: ''}  # start with this so None=""
        for transStr in toTranslate:
            self._localized[transStr] = _translate(transStr)
```

Unfortunately, poedit can't recognize that these strings need to be translated.  We have to write them without `for` statement.

```
            self._localized[transStr] = [
            "one of your Components, Routines, or condition parameters":_translate("one of your Components, Routines, or condition parameters"),
(snip)
            "python keyword":_translate("python keyword")
            ]

```

On the other hand, we have put pairs of original and translated strings into psychopy/app/builder/localizedStrings.py.  Should these strings be moved to localizedStrings.py, too?  Or, should they remain as the attribute of `NameSpace` object ?

**Comment by peircej** [comment]
I'm happy with your gut feeling on this one. If lcalized feels more natural that's fine with me. I think there are quite a few more strings in the new GUI elements weve added (several by David who I don't think was aware of the translation need at all) but you may also want to wait for a few quick iterations of these in case they change further?

**Comment by peircej** [comment]
Yes, I think Runner should probably not be translated (although do you translate Builder and Coder names?)

**Comment by hsogo** [comment]
Builder, Coder, Routine, Component and Flow are not translated :wink:.
![3](https://user-images.githubusercontent.com/2094930/75037243-0e317900-54f7-11ea-862b-8dc411d4af3d.png)
![4](https://user-images.githubusercontent.com/2094930/75037247-1093d300-54f7-11ea-8c71-afc61f1bb747.png)
![5](https://user-images.githubusercontent.com/2094930/75037508-ae879d80-54f7-11ea-96d5-5de7cce9a17f.png)

**Comment by hsogo** [comment]
I've modified psychopy/experiment/exports.py and some other files so that strings to be translated are defined in psychopy/app/builder/localizedStrings.py.

I said that component is not translated, but it came to my mind that I used コンポーネント as translation of "Component" in some sentences.  Because コンポーネント represents pronunciation of "Component" in Katakana characters, Japanese users would not be confused, I think.

By the way, now I've been learning Runner interface.  Alert is a nice feature especially for beginners.  Although it would be more helpful for non-English users if alert messages were translated, I'll wait and see because it seems that the alarm feature is under development.

**Comment by hsogo** [comment]
Ouch, I can't start PsychoPy app after I pulled the latest master branch from upstream!
The error message is following:

```
Traceback (most recent call last):
  File "C:\Users\Hiroyuki\Dropbox\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Hiroyuki\Dropbox\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\psychopyApp.py", line 104, in <module>
    main()
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\psychopyApp.py", line 100, in main
    start_app()
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\psychopyApp.py", line 28, in start_app
    app = PsychoPyApp(0, showSplash=showSplash)
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\_psychopyApp.py", line 210, in __init__
    self.onInit(testMode=testMode, **kwargs)
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\_psychopyApp.py", line 348, in onInit
    self.showCoder(fileList=scripts)
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\_psychopyApp.py", line 556, in showCoder
    files=fileList, app=self)
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\coder\coder.py", line 1085, in __init__
    self.fileBrowserWindow = FileBrowserPanel(self.sourceAsst, self)
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\coder\fileBrowser.py", line 228, in __init__
    self.gotoDir(os.getcwd())
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\coder\fileBrowser.py", line 610, in gotoDir
    if not self.scanDir(path):  # if failed, return the current directory
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\coder\fileBrowser.py", line 547, in scanDir
    time.strptime(modTime, "%a %b %d %H:%M:%S %Y"),"%b %d, %Y, %I:%M %p",
  File "C:\Users\Hiroyuki\Dropbox\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Hiroyuki\Dropbox\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'Mon Mar 27 02:05:00 2017' does not match format '%a %b %d %H:%M:%S %Y'
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
```
At first I didn't understand why `strptime()` failed, but I read manpage of strftime(3) and found that %a and %b is interpreted according to the current locale.  So I tested following code on my Win10 PC.

```
iimport locale
import time
import os

locale.setlocale(locale.LC_TIME, 'en_US.UTF-8')
modTime = time.ctime(os.path.getmtime('./strptime_test.py'))
print('\n--en_US.UTF-8 locale--\nctime: '+modTime)
print(time.strptime(modTime, "%a %b %d %H:%M:%S %Y"))

locale.setlocale(locale.LC_TIME, 'ja_JP.UTF-8')
modTime = time.ctime(os.path.getmtime('./strptime_test.py'))
print('\n--ja_JP.UTF-8 locale--\nctime: '+modTime)
print(time.strptime(modTime, "%a %b %d %H:%M:%S %Y"))
```

The result was as follows.  `ctime()` returns month and day of the week in English regardless of locale, resulting error in `strptime()`.

```
--en_US.UTF-8 locale--
ctime: Fri Mar  6 14:15:54 2020
time.struct_time(tm_year=2020, tm_mon=3, tm_mday=6, tm_hour=14, tm_min=15, tm_sec=54, tm_wday=4, tm_yday=66, tm_isdst=-1)

--ja_JP.UTF-8 locale--
ctime: Fri Mar  6 14:15:54 2020
Traceback (most recent call last):
  File "strptime_test.py", line 13, in <module>
    print(time.strptime(modTime, "%a %b %d %H:%M:%S %Y"))
  File "C:\Users\Hiroyuki\Dropbox\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Hiroyuki\Dropbox\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'Fri Mar  6 14:15:54 2020' does not match format '%a %b %d %H:%M:%S %Y'
```

Back to the error in fileBrowser.py, how important is it to convert output of `ctime()`?  If no so important, we have an option not to convert the output here, I think.

**Comment by peircej** [comment]
Thanks @hsogo 
I was just saying to @mdcutone yesterday that I thought it was time we brought this new feature in to the master branch so that developers started finding the issues before a release (not soon)! 
@mdcutone can date formatting be avoided (or at least delayed)? I couldn't quickly see where it gets used.

**Comment by mdcutone** [comment]
I'll get rid of it.

**Comment by mdcutone** [comment]
PR #2830 fixes this issue. Also thanks @hsogo for putting the work into translating the software. I greatly appreciate such efforts.

**Comment by hsogo** [comment]
Thank you @mdcutone , now I can open Coder view. New features are really cool!

**Comment by hsogo** [comment]
In psychopy/preferences/*.spec files, initial value of "locale" is defined as `string(default='')`.  When locale is set to `""`, system locale is used.  Therefore, if users haven't changed locale setting, "locale" will be shown as a blank in the Preference Dialog and the application will be shown in the system locale.
![5](https://user-images.githubusercontent.com/2094930/76201182-38dd3a80-6236-11ea-985e-3166398cd842.png)

However, in the new Preference Dialog, locale is shown as "en_US" when locale is set to `""`.  Because application is shown in system locale (Japanese in this screen shot).
![3](https://user-images.githubusercontent.com/2094930/76199510-59f05c00-6233-11ea-92fc-09f2337e89af.png)
I've committed fix for this issue to my feature-localization branch.

**Comment by mdcutone** [comment]
Okay, I'll fix that.

**Comment by hsogo** [comment]
Please see https://github.com/hsogo/psychopy/commit/af8d1a7f8306dd70d5e21856c9735a4e9b885cfb#diff-c5c27e5fd2860340f6a982cec74b6668 for my fix.

I've just thought that it may be helpful to display some words like "system locale" or "auto-detect" when locale is `""`.  This can be done as follows.

```
labels = ['system locale'] + [_localized[i] for i in self.app.localization.available]
```

**Comment by hsogo** [comment]
I'm adding _translate() to new Coder items.  I noticed that context menu in the Shell pane is defined in `wx.py.shell.Shell`, outside of PsychoPy.  I guess this menu can be translated by overriding `GetContextMenu()` method of `wx.py.shell.Shell`.  I'll try it soon.
![2](https://user-images.githubusercontent.com/2094930/76314764-c1350b80-631a-11ea-89c7-d5547ec52cfd.png)

**Comment by mdcutone** [comment]
I eventually want to make a string table for all the error messages and warnings in PsychoPy. It will keep the code base neat and make it easier to translate everything eventually. Errors will have codes associated with them so developers of other languages can make sense of output people post in the issue tracker.

**Comment by hsogo** [comment]
Error code is nice idea.  I sometimes have to use Microsoft Visual C++, and it is quite difficult to google error messages without error ID because error messages are localized.

**Comment by peircej** [comment]
> I eventually want to make a string table for all the error messages and warnings in PsychoPy. It will keep the code base neat and make it easier to translate everything eventually. Errors will have codes associated with them so developers of other languages can make sense of output people post in the issue tracker.

You checked the alerts system, right? That's the idea entirely. Alerts are defined by code numbers and have various fields stored in yamlfiles https://github.com/psychopy/psychopy/tree/master/psychopy/alerts/alertsCatalogue

We parse those yaml files to generate the documentation https://www.psychopy.org/alerts/ and one of the key advantages here is that the error in the output (whether a stdout or a dedicated AlertHandler) can then provide users with a link to get more info than the one-line error message.

In the code you just call something like `alerts.alert(3210)` and it handles the rest (using the message defined in the yaml file). Right now these are mostly being used for warnings about Builder experiments but the plan is to move all `logging.warn()` and `logging.error()` calls to alerts.

We called them alerts rather than errors or warnings so that the user could define what happens on each one. For instance, if a frame gets dropped it's no big deal to some people (don't even tell me) but catastrophic to others (abort the study) so I'd like for the user to set what they want.

@hsogo it did cross my mind too that these could warrant translations but there's a lot more text in them than in the dialog boxes, so it could turn into a big job.

**Comment by mdcutone** [comment]
I think we need enums for alerts, I would rather see something like "alerts.alert(FILE_NOT_FOUND_ERROR)" than just numbers.

**Comment by hsogo** [comment]
I seems that gettext wouldn't be effective for translation in this case.  It would be better to prepare yaml files for each locale, I think.

**Comment by peircej** [comment]
I'm not sure abouth using enums. Maybe. The advantage of being more visible in code (and I'm expecting most alert codes to come up in just a single place) is that it adds an extra mechanism that we need to keep tracked and in-sync. It would be important that the name and relevant code never ever change or the relevant help files will become disconnected. Presumably we would still use the actual code number for the user, but then tracing where that code had been raised also requires an extra step if we used enums: rather than search-in-project for the number we would have to find the name and then search-in-project for that name. Maybe we should skype/zoom to chat about how this would be implemented and the pros/cons.

For translations, yes, we could duplicate all the yaml files and that might be the best thing, especially if we plan to do translations for the web pages of further info. If we only plan to translate the alert `msg` (which the user receives) then we could do that by compiling files of messages to be translated (e.g. with each documentation update, or each release)

**Comment by hsogo** [comment]
Just a trial.  I modified getter of `psychopy.alerts.AlertsCatalog.alertPath` and created psychopy/alerts/alertsCatalogue/ja_JP folder.  Then, I copied yaml files to ja_JP folder and translate some yaml files.

```
    @property
    def alertPath(self):
        base_path = Path(__file__).parent / "alertsCatalogue"
        locale_path = base_path / _translate("locale_folder")
        if locale_path.is_dir():
            return locale_path
        else:
            return base_path
```
The result was as follows.  It worked fine.

![2](https://user-images.githubusercontent.com/2094930/76519747-e6ee1c00-64a4-11ea-9a9f-1cde93f91dde.png)

**Comment by peircej** [comment]
That's cool. The question is whether you'd prefer it to work from the same POEdit setup so that when new oens got added it's easy to see what isn't yet translated

**Comment by hsogo** [comment]
It's a tough choice.  Translating YAML files directly would be somewhat easier to work than using Poedit for me.  However, it would be tiresome to check changes in dozens of original YAML files!  So, if error messages will be almost unchanged after created, translating YAML files is preferable.  If they will be updated often, Poedit is helpful to find updates.

By the way, though I've never tried, Sphinx supports internationalization.  PO files can be generated from ReST files.  If contents of YAML files are converted to ReST, this may be a possible option.
[https://www.sphinx-doc.org/en/master/usage/advanced/intl.html](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html)

**Comment by hsogo** [comment]
@peircej  I've come to think that it is somewhat redundant to prepare translated YAML files while having localization with gettext.  What do you think about generating a python file which contains alert messages in the same way as generating hints.py from psychopy/preferences/*.spec files?  Here is my attempt.  generateAlertmsg.py extracts alert messages from alert catalog and writes them to alertmsg.py.
[FF: localize alert messages](https://github.com/hsogo/psychopy/commit/7e4f18c3990cefdbfcbf323a2ad36b38cf205175)

**Comment by peircej** [comment]
I think that makes sense. I think the only reason to go the other way would be so that we can provide translations of the entire help pages, but that would be a lot of work and we can change the structure to help make that possible only if we get that far!

**Comment by hsogo** [comment]
Do you mean that alert messages are always shown in English and users can read translated documents when clinking URL on alert messages (e.g. https://psychopy.org/alerts/2115.html)?  It may be nice, because I am somewhat worried that localized alert messages might cause trouble when they are output to log files and consoles.
Now I'm trying Sphinx internationalization (sphinx-intl).  Sphinx-intl only provides translation, and does not provide a way to switch multiple languages.  Like official python document ([https://docs.python.org/ja/3/](https://docs.python.org/ja/3/)), it would be nice to have a menu for switching languages on the top of each page.

**Comment by peircej** [comment]
I mean it would be great if the alert message in the app whereas all the other fields, like the details and the workarounds could be left, given that the documentation is still in English.

I agree it would be great to translate the entire documentation, but that seems like a huge job!

**Comment by hsogo** [comment]
@peircej Congrats for releasing PsychoPy 2020.2!  I'm working on translating new codes and troubled with `PsychoPyToolbar.addPsychopyTool()` in psychopy/app/utils.py.  In this method, label string is concatenated with shortcut key name and passed to `_translate()` (lines 264-266, see below).  This cannot be detected by Poedit.

```
     label=_translate(
            label + " [%s]") %
              self.keys[shortcut],
```

I think it is better to remove `_translate()` from `addPsychopyTool()` and to translate label strings before passing them to `addPsychopyTool()` (actually, labels of Builder toolbar has already translated in this way, please see lines 144-211 of utils.py).  However, I'm not sure whether `label` parameter need to be original string because the value is used as `name` parameter of `makeBitmapButton()` within `addPsychopyTool()` (line 263).  Is it safe to use translated label as `name` of `makeBitmapButton()` 
 here?   If not, how about modifying call of `makeBitmapButton()` as below?

```
        if not name.endswith('.png'):
            filename = name + '.png'  # name of bitmap file is stored in `filename`
        else:
            filename = name
        item = self.app.iconCache.makeBitmapButton(parent=self, filename=filename,
                                                   name=name,  #use `name` parameter as the name of button
                                                   label=label + (" [%s]" % self.keys[shortcut]),
                                                   emblem=emblem, toolbar=self,
                                                   tip=tooltip,
                                                   size=self.iconSize)
```

**Comment by peircej** [comment]
Ah, yes, I had spotted the issue was going to crop up but obviously failed to apply the fix to the Coder buttons having done the Builder ones. I assum it is safe to use a unicode as the name (as wel as the label) if the app doesn't crash for you when you open Builder given that's already translated. I've just updated the translation step for the Code buttons in f5a68a062f7c9ddcdfb171d861821eedc737b5dc

**Comment by hsogo** [comment]
Thank you for your quick response. I've pulled your update.

**Comment by hsogo** [comment]
I think I've finished translating new strings.  I've sent a pull request.
