### ISSUE TITLE
saveAsWideText using fileName = 'stdout' or fileName = None does not print results to stdout

### ISSUE THREAD

**Issue by joaquinmoris** [psychopy/psychopy#2843]
In version 2020.1.2 of Psychopy, calling saveAsWideText with the parameter ```fileName = 'stdout'``` or ```fileName = None``` does not write the results to stdout. In the first case, a file named 'stdout.delim' is created (where delim comes from the type of delimiter selected). In the second, the following errors occur.

reprex:
```python
from psychopy import core, data

psychopyVersion = '2020.1.2'
expInfo = {'psychopyVersion': psychopyVersion}

thisExp = data.ExperimentHandler(name='', version=psychopyVersion,
    extraInfo=expInfo, runtimeInfo=None,
    originPath='.',
    savePickle=False, saveWideText=False,
    dataFileName='onExit.csv')

thisExp.saveAsWideText('stdout')
thisExp.saveAsWideText(None)

Traceback (most recent call last):
  File "reprex_saveAsWideTest.py", line 1, in <module>
  File ".\psychopy\data\experiment.py", line 304, in saveAsWideText
    delim = genDelimiter(fileName)
  File ".\psychopy\tools\filetools.py", line 195, in genDelimiter
    if fileName.endswith(('.csv', '.CSV')):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

If a delimiter is set, a different error is shown, but nothing is printed in either case:
```python
from psychopy import core, data

psychopyVersion = '2020.1.2'
expInfo = {'psychopyVersion': psychopyVersion}

thisExp = data.ExperimentHandler(name='', version=psychopyVersion,
    extraInfo=expInfo, runtimeInfo=None,
    originPath='.',
    savePickle=False, saveWideText=False,
    dataFileName='onExit.csv')

thisExp.saveAsWideText('stdout', delim = ",")
thisExp.saveAsWideText(None, delim = ",")

Traceback (most recent call last):
  File "reprex_saveAsWideTest.py", line 1, in <module>
  File ".\psychopy\data\experiment.py", line 310, in saveAsWideText
    fileName = genFilenameFromDelimiter(fileName, delim)
  File ".\psychopy\tools\filetools.py", line 207, in genFilenameFromDelimiter
    if not filename.endswith(('.dlm', '.DLM', '.tsv', '.TSV', '.txt',
AttributeError: 'NoneType' object has no attribute 'endswith'
```

In the first case, the function ```genDelimiter``` could be modified changing the condition of the ```if``` statement of the function from ```if fileName.endswith(('.csv', '.CSV')):``` to ```    if filename is not None and filename != 'stdout' and fileName.endswith(('.csv', '.CSV')):``` and the function would be as follows:

```python

def genDelimiter(fileName):
    """Return a delimiter based on a filename.

    :Parameters:

    fileName : string
        The output file name.

    :Returns:

    delim : string
        A delimiter picked based on the supplied filename. This will be
        ``,`` if the filename extension is ``.csv``, and a tabulator
        character otherwise.

    """
    fileName = pathToString(fileName)
    if filename is not None and filename != 'stdout' and fileName.endswith(('.csv', '.CSV')):
        delim = ','
    else:
        delim = '\t'

    return delim
```

In the second case the problem comes from this call to the function ```genFilenameFromDelimiter``` inside ```saveAsWideText```:

```python
# create the file or send to stdout
fileName = genFilenameFromDelimiter(fileName, delim)
```

The problem seems to be that this function adds an extension to the ```'stdout'``` string and gives the mentioned error when using ```None```. This behaviour could be changed adding the following ```if``` statement at the top of the function
```python
if filename is not None and filename != 'stdout':
```

The function then would be:

```python
def genFilenameFromDelimiter(filename, delim):
    # If no known filename extension was specified, derive a one from the
    # delimiter.
    if filename is not None and filename != 'stdout':
        filename = pathToString(filename)
        if not filename.endswith(('.dlm', '.DLM', '.tsv', '.TSV', '.txt',
                                  '.TXT', '.csv', '.CSV', '.psydat', '.npy',
                                  '.json')):
            if delim == ',':
                filename += '.csv'
            elif delim == '\t':
                filename += '.tsv'
            else:
                filename += '.txt'

    return filename
```

**Comment by peircej** [comment]
Well done tracking this down @joaquinmoris I guess it's functionality that almost nobody uses so nobody noticed that it had been lost.
Do you want to submit a pull request with your fix? (please prefix your commit with BF: if you do)
