### ISSUE TITLE
I can't put any Components in the Builder

### ISSUE THREAD

**Issue by iuype** [psychopy/psychopy#2869]
Below is what I got in Stdout exsiting at Runner when I click any Components in the Builder
what shoul I do ?

Traceback (most recent call last):
  File "d:\application\py37\lib\site-packages\psychopy\app\builder\builder.py", line 905, in onClick
    timeout=timeout)
  File "d:\application\py37\lib\site-packages\psychopy\app\builder\dialogs\__init__.py", line 1758, in __init__
    timeout=timeout)
  File "d:\application\py37\lib\site-packages\psychopy\app\builder\dialogs\__init__.py", line 510, in __init__
    ctrls = self.addCategoryOfParams(theseParams, parent=page)
  File "d:\application\py37\lib\site-packages\psychopy\app\builder\dialogs\__init__.py", line 617, in addCategoryOfParams
    currRow)
  File "d:\application\py37\lib\site-packages\psychopy\app\builder\dialogs\__init__.py", line 720, in addStartStopCtrls
    flag=wx.ALIGN_RIGHT | wx.ALIGN_CENTRE_VERTICAL)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_VERTICAL)" failed at ..\..\src\common\sizer.cpp(2077) in wxBoxSizer::DoInsert(): Vertical alignment flags are ignored in vertical sizers

**Comment by iuype** [comment]
My installation is "StandalonePsychoPy3-2020.1.3-win64" on WIN10 platform

**Comment by peircej** [comment]
I suspect you also have a separate python installation, created from conda or from python.org?

The error above looks like something that comes from having wxPython 4.1 installed (which wasn't packaged in Standalone) so I think you've got a clash of versions. We are working to add support for wx 4.1 in the next release but I think this is something symptomatic of your setup

**Comment by iuype** [comment]
Thank you very much for your suggestion, under your guidance, I uninstalled all the python environment, after reinstalling psychopy, everything works normally
