### ISSUE TITLE
OSError: [WinError -2147417850] Cannot change thread mode after it is set

### ISSUE THREAD

**Issue by nobias** [psychopy/psychopy#2876]
I just installed PsychoPy3 v2020.1.2 via the environment file you provide for Anaconda3 (Python 3.7.6 64bit) on Windows 10 (10.0.18363 Build 18363). When I run any of the demos, for example visual_noise.py, I run into an exception that occurs after the experiment has ended:

`Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\demouser\Miniconda3\envs\psychopy\lib\site-packages\pyglet\media\codecs\wmf.py", line 834, in __init__
    ole32.CoInitializeEx(None, COINIT_MULTITHREADED)
  File "_ctypes/callproc.c", line 940, in GetResult
OSError: [WinError -2147417850] Cannot change thread mode after it is set`

Here's the full ouput from the PsychoPy Runner log window:

```
## Running: C:\Users\demouser\Miniconda3\envs\psychopy\lib\site-packages\psychopy\demos\coder\stimuli\visual_noise.py ##
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
1.1714     WARNING     Monitor specification not found. Creating a temporary one...
1.8385     EXP     Created window1 = Window(allowGUI=False, allowStencil=False, args=UNKNOWN, autoLog=True, bitsMode=UNKNOWN, blendMode='avg', bpc=(8, 8, 8), color=array([0., 0., 0.]), colorSpace='rgb', depthBits=8, fullscr=<method-wrapper '__getattribute__' of attributeSetter object at 0x000002250CECF9B0>, gamma=None, gammaErrorPolicy='raise', kwargs=UNKNOWN, lms=UNKNOWN, monitor=<psychopy.monitors.calibTools.Monitor object at 0x000002257FD637F0>, multiSample=False, name='window1', numSamples=2, pos=[660.0, 240.0], screen=0, size=array([600, 600]), stencilBits=0, stereo=False, units='norm', useFBO=False, useRetina=False, viewOri=0.0, viewPos=None, viewScale=None, waitBlanking=True, winType='pyglet')
18.1711     DATA     Mouse: Left button down, pos=(56,437)
18.2683     DATA     Mouse:  Left button up, pos=(56,437)
19.7024     DATA     Keypress: space
19.7513     EXP     window1: mouseVisible = True
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\demouser\Miniconda3\envs\psychopy\lib\site-packages\pyglet\media\codecs\wmf.py", line 834, in __init__
    ole32.CoInitializeEx(None, COINIT_MULTITHREADED)
  File "_ctypes/callproc.c", line 940, in GetResult
OSError: [WinError -2147417850] Cannot change thread mode after it is set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\demouser\Miniconda3\envs\psychopy\lib\site-packages\pyglet\media\__init__.py", line 143, in <module>
    add_default_media_codecs()
  File "C:\Users\demouser\Miniconda3\envs\psychopy\lib\site-packages\pyglet\media\codecs\__init__.py", line 175, in add_default_media_codecs
    add_decoders(wmf)
  File "C:\Users\demouser\Miniconda3\envs\psychopy\lib\site-packages\pyglet\media\codecs\__init__.py", line 128, in add_decoders
    for decoder in module.get_decoders():
  File "C:\Users\demouser\Miniconda3\envs\psychopy\lib\site-packages\pyglet\media\codecs\wmf.py", line 890, in get_decoders
    return [WMFDecoder()]
  File "C:\Users\demouser\Miniconda3\envs\psychopy\lib\site-packages\pyglet\media\codecs\wmf.py", line 836, in __init__
    warnings.warn('WMF failed to initialize threading:', err.strerror)
TypeError: category must be a Warning subclass, not 'str'
##### Experiment ended. #####
```

Any advice appreciated. Thanks!

**Comment by TEParsons** [comment]
I got the same error recently! I'm still getting the error text, so will continue investigating why, but it doesn't interfere with running the experiment now that I have the "Build Tools for Visual Studio 2019" installed - from here: https://visualstudio.microsoft.com/downloads/

One hypothesis is that it's an incompatibility with my specific GPU, are you using an NVIDIA GTX 1060 by any chance?

**Comment by peircej** [comment]
My thoughts, in case they help:
1.  it looks like this is happening during our shutdown call (atexit calls win.close() which calls PygletBackend.close()) which explains why Todd found it didn't interfere with the experiment
2. as we haven't seen this before and the closing call hasn't changed recently, my guess is that this is something to do with recent versions of Pyglet. ie. they've changed something and it's now not working properly. So what version of pyglet do you guys have installed?

**Comment by nobias** [comment]
My pyglet is at 1.5.5 (python 3.6), from conda-forge. I've seen the error on two systems, both running Windows 10, one with a GeForce RTX 2070, the other with a GeForce GTX 1050 Ti. I can dig deeper, but a few pointers on how to approach this would be helpful. I guess testing pyglet alone would be a good first step?

**Comment by peircej** [comment]
My guess is that downgrading pyglet to an older version will fix it. I'm on 1.4.10 and it works there with no problems

**Comment by peircej** [comment]
I'd be a little surprised if this is graphics card specific

**Comment by Thundor404** [comment]
I met a similar problem recently via deploying with anaconda. I'll check whether the problem occurs in a standalone package. By the way, I run psychoPy in my laptop with an NVIDIA MX350. It will be a confusing problem if it occurs for specific graphics cards.

**Comment by efunn** [comment]
> My guess is that downgrading pyglet to an older version will fix it. I'm on 1.4.10 and it works there with no problems

I just grabbed PsychoPy from `pip install psychopy` on a fresh Windows 10 install and ran into this error, alongside another catastrophic error anytime you try to render text or load fonts (with `pyglet==1.5.6`). Can confirm that `pip install pyglet==1.4.10` fixed both issues. Might be worth specifying `pyglet` version `<=` for Windows in `setup.cfg`?

**Comment by Gertone** [comment]
Same here. Had the same error on an recent install of Anaconda.
Downgrading pyglet did the trick
`!pip install pyglet==1.4.10
`No more thread mode errors after

**Comment by isolver** [comment]
Having same issue here when using pyglet 1.5. Warning is printed when experiemnt starts though, not on exit. It is also usually printed several times, not just once. Using pyglet 1.3.1 works.
