### ISSUE TITLE
ValueError when creating visual.Window with default monitor=None

### ISSUE THREAD

**Issue by cbrnr** [psychopy/psychopy#2888]
This example results in a `ValueError` on my machine (macOS 10.15.5, Python 3.8.3. PsychoPy 2020.1.2 installed via conda-forge):

```python
from psychopy import core, visual

win = visual.Window()
circle = visual.Circle(win)
circle.draw()
win.flip()
core.wait(2)
win.close()
core.quit()
```

The error message:

```
Traceback (most recent call last):
  File "psychopy_mwe.py", line 6, in <module>
    circle.draw()
  File "/Users/clemens/anaconda/envs/psychopy/lib/python3.8/site-packages/psychopy/visual/shape.py", line 335, in draw
    vertsPix = self.verticesPix
  File "/Users/clemens/anaconda/envs/psychopy/lib/python3.8/site-packages/psychopy/visual/basevisual.py", line 479, in verticesPix
    self._updateVertices()
  File "/Users/clemens/anaconda/envs/psychopy/lib/python3.8/site-packages/psychopy/visual/basevisual.py", line 519, in _updateVertices
    verts = convertToPix(vertices=verts, pos=self.pos,
  File "/Users/clemens/anaconda/envs/psychopy/lib/python3.8/site-packages/psychopy/tools/monitorunittools.py", line 95, in convertToPix
    return unit2pixFunc(vertices, pos, win)
  File "/Users/clemens/anaconda/envs/psychopy/lib/python3.8/site-packages/psychopy/tools/monitorunittools.py", line 38, in _deg2pix
    return deg2pix(pos + vertices, win.monitor)
  File "/Users/clemens/anaconda/envs/psychopy/lib/python3.8/site-packages/psychopy/tools/monitorunittools.py", line 249, in deg2pix
    raise ValueError(msg % monitor.name)
ValueError: Monitor __blank__ has no known size in pixels (SEE MONITOR CENTER)
1.1652 	WARNING 	Monitor specification not found. Creating a temporary one...
```

AFAIR the default `monitor=None` should use a default monitor and not raise an error (at least I'm pretty sure that this used to work). Now I have to explicitly specify a monitor for the example to work:

```
win = visual.Window(monitor="testMonitor")
```

Is this behavior intentional?

Bonus question (only slightly related): when I don't specify the `units` - what does it default to? The docs do not mention what `None` means in this case. I think it is `'deg'`, but where can I find out?

**Comment by mdcutone** [comment]
I think those arguments should default to a string instead of None. If we are using None, PsychoPy should detect the display settings and create a dummy monitor configuration. It can raise a warning saying that it's guessing what configuration is being used.

**Comment by cbrnr** [comment]
So the error that I get is an actual bug, right?

**Comment by peircej** [comment]
The default unit is set in preferences. The default for that default is actually `norm` which shouldn't give you the error. 

My guess is that you've set your default in preferences (I regret that this was ever an optoin to be fair!) to be `'deg'` and then PsychoPy is complaining that you've requested a unit that needs more info than given (e.g. cm needs screen cm,pix,; `deg` needs cm,pix,distance)

**Comment by cbrnr** [comment]
Thanks @peircej - this was indeed the problem. I've removed that setting from my config file and it works like a charm!
