### ISSUE TITLE
ioHub doesn't start in fresh install due to decoding errors

### ISSUE THREAD

**Issue by matthias-k** [psychopy/psychopy#2950]
I installed psychopy into a fresh anaconda installation exactly as in https://www.psychopy.org/download.html#conda. The basic demos work (e.g. hello_world), but the ioHub demos don't work. When starting them from the console, I get the following error:

```
```(psychopy) $ python launchHub.py 

------------------------------------

Running testWithNoKwargs Test:
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/matthias/anaconda3/envs/psychopy/lib/python3.6/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/matthias/anaconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/iohub/server.py", line 76, in handle
    request_type = unicode(request.pop(0), 'utf-8') # convert bytes to string for compatibility
TypeError: decoding str is not supported
2020-07-17T14:00:54Z <Greenlet at 0x7f768bdabd48: _handle_and_close_when_done(<bound method udpServer.handle of <udpServer at 0x, <bound method BaseServer.do_close of <udpServer at, (b'\x91\xb0GET_IOHUB_STATUS', ('127.0.0.1', 58533))> failed with TypeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/matthias/anaconda3/envs/psychopy/lib/python3.6/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/matthias/anaconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/iohub/server.py", line 76, in handle
    request_type = unicode(request.pop(0), 'utf-8') # convert bytes to string for compatibility
TypeError: decoding str is not supported
2020-07-17T14:00:54Z <Greenlet at 0x7f768bdabd48: _handle_and_close_when_done(<bound method udpServer.handle of <udpServer at 0x, <bound method BaseServer.do_close of <udpServer at, (b'\x91\xb0GET_IOHUB_STATUS', ('127.0.0.1', 58533))> failed with TypeError

[repeating for ever]
```
I debugged a little bit and figured out that `request.pop(0)` is already a string which of course can't be decoded. I don't know where the request comes from, maybe this is a compatibility issue (the environment.yml file provided by psychopy doesn't provide any versions for the required libraries).

**Comment by matthias-k** [comment]
It seems to work in the standalone version under Mac, which adds more evidence that this is a compatibility issue. Is there any way to figure out which dependencies the standalone version is using? (maybe @mdcutone knows?)

**Comment by peircej** [comment]
The standalone mac versions of greenlet and gevent are as below:
```
>>> greenlet.__version__
'0.4.13'
>>> gevent.__version__
'1.2.2'
```

**Comment by peircej** [comment]
Presumably gevent used to sent/received in bytes and left it to the user to convert to unicdoe but now converts automatically. What I've done in the past to handle these is format into a string in the native format:
```python
request_type = "{}".format(unicode(request.pop(0), 'utf-8'))
```

**Comment by matthias-k** [comment]
@peircej Thanks! unfortunately, downgrading gevent and greenlet to the versions you mentioned doesn't solve the problem. It's still exactly the same error.
