### ISSUE TITLE
AttributeError: ‘NoneType’ object has no attribute ‘addTask’

### ISSUE THREAD

**Issue by pstetz** [psychopy/psychopy#3101]
### Issue

Version: [2020.2.3](https://github.com/psychopy/psychopy/releases/tag/2020.2.3)
OS: MacOS Catalina 10.15.6

To reproduce: (1) Open PsychoPy, (2) Open task and run it (clicking on "Run Experiment"), (3) The task fails (see Stdout of task if relevant), (4)  When I click on "Run experiment" a second time, the following dialog box appears and asks me to quit PsychoPy.  The error pops up each time the green "Run experiment" button is pressed.

### Error

```
Traceback (most recent call last):
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/coder/coder.py”, line 2518, in runFile
AttributeError: ‘NoneType’ object has no attribute ‘addTask’
```

![スクリーンショット 2020-08-26 10 39 07](https://user-images.githubusercontent.com/16963003/91337667-96375a80-e788-11ea-80ee-43ebe63c603f.png)

### Stdout

```
Welcome to PsychoPy3!
v2020.2.3
############ Running: /Users/pbezuhov/git/stimuli/scripts/gonogo.py ############
OrderedDict([('stimulus', 'images/1,1.png'), ('category', 'Go')])
5.4886     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
11.0782     WARNING     Monitor specification not found. Creating a temporary one...
11.0835     WARNING     Requested an unavailable screen number - using first available.
2020-08-26 10:33:43.980 python[8853:85970] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "/Users/pbezuhov/git/stimuli/scripts/gonogo.py", line 313, in <module>
    exec(paramName + '= thisTrial.' + paramName)
  File "<string>", line 1, in <module>
AttributeError: 'collections.OrderedDict' object has no attribute 'stimulus'
##### Experiment ended. #####
```

**Comment by au-uni** [comment]
Same setup, same problem. For me it happens even if I try to run any demos.

Version: 2020.2.3
OS: MacOS Catalina 10.15.6
