### ISSUE TITLE
PsychoPy3 does not load when BitLocker encrypted drive is unlocked on Windows 10

### ISSUE THREAD

**Issue by brunodOut** [psychopy/psychopy#3229]
Hello,

I'm using PsychoPy3 v2020.2.4 on a Windows 10 (updated) computer and I am facing an issue, likely very specific.

I have a BitLocker encrypted drive and this drive is intended not to be unlocked every time, and it's actually seldom unlocked. When this drive is locked, PsychoPy3 does not start. I have no project or file related to that drive at all, nothing related to PsychoPy or Python. I have checked the command line output and I have the following stacktrace:

```PS C:\Users\me> & 'C:\Program Files\PsychoPy3\python.exe' 'C:\Program Files\PsychoPy3\Lib\site-packages\psychopy\app\psychopyApp.py' --builder
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy3\Lib\site-packages\psychopy\app\psychopyApp.py", line 104, in <module>
    main()
  File "C:\Program Files\PsychoPy3\Lib\site-packages\psychopy\app\psychopyApp.py", line 100, in main
    start_app()
  File "C:\Program Files\PsychoPy3\Lib\site-packages\psychopy\app\psychopyApp.py", line 22, in start_app
    from psychopy.app._psychopyApp import PsychoPyApp
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\_psychopyApp.py", line 24, in <module>
    from . import themes
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\themes\__init__.py", line 1, in <module>
    from ._themes import ThemeMixin, IconCache
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\themes\_themes.py", line 16, in <module>
    from ...experiment import components
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\experiment\__init__.py", line 22, in <module>
    from .components import getInitVals, getComponents, getAllComponents
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\experiment\components\__init__.py", line 21, in <module>
    from ._base import BaseVisualComponent, BaseComponent
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\experiment\components\_base.py", line 21, in <module>
    from psychopy.alerts import alerttools
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\alerts\alerttools.py", line 5, in <module>
    from psychopy.tools import monitorunittools
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\tools\monitorunittools.py", line 15, in <module>
    from psychopy import monitors
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\monitors\__init__.py", line 10, in <module>
    from .calibTools import *
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\monitors\calibTools.py", line 37, in <module>
    import scipy.optimize as optim
  File "C:\Program Files\PsychoPy3\lib\site-packages\scipy\optimize\__init__.py", line 389, in <module>
    from .optimize import *
  File "C:\Program Files\PsychoPy3\lib\site-packages\scipy\optimize\optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "C:\Program Files\PsychoPy3\lib\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: DLL load failed: This drive is locked by BitLocker Drive Encryption. You must unlock this drive from Control Panel.
PS C:\Users\me>
```

After some digging, I have found out that it might be related to the fact I map this hard drive as `B:` (it's for a specific reason and I cannot change that on a permanent basis). I have temporarily disabled the device, and then mapped it to another drive letter, like `F:`, and in both cases it worked without issues, so it seems like something hardcoded (perhaps because `B:` was, traditionally, the letter for 5.25 floppy drives?).

**Comment by peircej** [comment]
The issue here isn't with PsychoPy code itself. It seems that the scipy extension for optimization doesn't load. If the issue is ultimately about the drive assignment that's ultimately an issue for the scipy team.

What _we_ could do is to delay the loading of the scipy.optimize lib until it's actually required. That way, the issue would only crop up if you attempt to _use_ the lib (for fitting the gamma curve to some luminance values)

**Comment by peircej** [comment]
This is't completely fixed (requires upstream help? or possbily a new packaging system) but very much ameliorated by #3287
