### ISSUE TITLE
New color picker raises error when activated

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#3244]
Raises the following error ...

```
Traceback (most recent call last):
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\_psychopyApp.py", line 647, in colorPicker
    PsychoColorPicker(self.coder)
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\colorpicker\__init__.py", line 38, in __init__
    self.ctrls.AddPage(ColorPage(self.ctrls, self, 'hexa'), 'Hex')
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\colorpicker\__init__.py", line 219, in __init__
    self.valCtrl = ColorValue(self)
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\colorpicker\__init__.py", line 261, in __init__
    wx.TextCtrl.__init__(self, parent=self.parent, value=str(getattr(self.color, self.space)), style=wx.TE_RICH, size=(250, -1))
AttributeError: 'Color' object has no attribute 'hexa'

```

**Comment by TEParsons** [comment]
Ahhh I know what this is - we changed the Color class to handle alpha independently of RGB, I forgot to update the colour picker accordingly... Will get on it!
