### ISSUE TITLE
launchHubServer demo failed

### ISSUE THREAD

**Issue by yuewu57** [psychopy/psychopy#3246]
Hi 

I was trying to run  launchHubServer demo (first example in https://www.psychopy.org/api/iohub/starting.html)
on Windows 10 system under **Python 3.6.0** with **PsychoPy (2020.2.4.post1)**, **greenlet 0.4.17**, **gevent-20.9.**0, but error occurred even from the second line:

Here are the error msgs:

>>> from psychopy.iohub.client  import launchHubServer
>>> io=launchHubServer()

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\Administrator\py36_faces\lib\site-packages\gevent\baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "C:\Users\Administrator\py36_faces\lib\site-packages\psychopy\iohub\server.py", line 94, in handle
    return self.handleExperimentDeviceRequest(request, replyTo)
  File "C:\Users\Administrator\py36_faces\lib\site-packages\psychopy\iohub\server.py", line 229, in handleExperimentDeviceRequest
    dclass = unicode(dclass, 'utf-8')
TypeError: decoding str is not supported
2020-10-23T21:45:44Z <Greenlet at 0x1deaeb87348: _handle_and_close_when_done(<bound method udpServer.handle of <udpServer at 0x, <bound method BaseServer.do_close of <udpServer at, (b'\x96\xaaEXP_DEVICE\xa7DEV_RPC\xa8Keyboard\xb1is)> failed with TypeError

I would appreciate your support.
 
 
Many thanks,
Yue

**Comment by peircej** [comment]
This is fixed in the 2020.2.5 release by commits: 1c360424535bbf3b285f42c86f1ff649f6e76ffa and #3136

**Comment by peircej** [comment]
(2020.2.5 release is imminent but you could apply the changes manually yourself)
