### ISSUE TITLE
ioHub and DataStore on Linux: `RPC_ATTRIBUTE_ERROR` and `decoding str is not supported`

### ISSUE THREAD

**Issue by rphlypo** [psychopy/psychopy#3348]
Below is the output I have when running `psychopy/demos/coder/iohub/launchHub.py`, no idea about how to further deal with the error messages telling `decoding str is not supported` whenever trying to access the DataStore. Anyone with an idea on where to look into?

```bash
Running testWithNoKwargs Test:
pygame 2.0.0 (SDL 2.0.12, python 3.6.11)
Hello from the pygame community. https://www.pygame.org/contribute.html

 ** PRESS A KEY TO CONTINUE.....
gA Keyboard Event was Detected; exiting Test.
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testUsingPsychoPyMonitorConfig Test:
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'width': 300.0, 'height': 168.75, 'unit_type': 'mm'}
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testEnabledDataStore Test:
RPC_ATTRIBUTE_ERROR
Traceback (most recent call last):
  File "/home/rphlypo/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/iohub/server.py", line 108, in handle
    result = getattr(self, unicode(callable_name, 'utf-8'))
TypeError: decoding str is not supported
RPC_ATTRIBUTE_ERROR
Traceback (most recent call last):
  File "/home/rphlypo/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/iohub/server.py", line 108, in handle
    result = getattr(self, unicode(callable_name, 'utf-8'))
TypeError: decoding str is not supported
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'width': 300.0, 'height': 168.75, 'unit_type': 'mm'}
Experiment Metadata: 
{'code': 'gap_endo_que',
 'description': '',
 'experiment_id': 'C',
 'title': '',
 'total_sessions_to_run': 0,
 'version': ''}

Session Metadata: 
{'code': 'S_07_12_2020_16_18',
 'comments': '',
 'name': '',
 'session_id': 'C',
 'user_variables': {}}
ioHub Server Process Completed With Code:  0
Test Result:  None

------------------------------------

Running testEnabledDataStoreAutoSessionCode Test:
Current Session Code will be:  S_1607354282
RPC_ATTRIBUTE_ERROR
Traceback (most recent call last):
  File "/home/rphlypo/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/iohub/server.py", line 108, in handle
    result = getattr(self, unicode(callable_name, 'utf-8'))
TypeError: decoding str is not supported
RPC_ATTRIBUTE_ERROR
Traceback (most recent call last):
  File "/home/rphlypo/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/iohub/server.py", line 108, in handle
    result = getattr(self, unicode(callable_name, 'utf-8'))
TypeError: decoding str is not supported
Display Psychopy Monitor Name:  testMonitor
Display Default Eye Distance:  570.0
Display Physical Dimensions:  {'width': 300.0, 'height': 168.75, 'unit_type': 'mm'}
Experiment Metadata: 
{'code': 'gap_endo_que',
 'description': '',
 'experiment_id': 'C',
 'title': '',
 'total_sessions_to_run': 0,
 'version': ''}

Session Metadata: 
{'code': 'S_1607354282',
 'comments': '',
 'name': '',
 'session_id': 'C',
 'user_variables': {}}
ioHub Server Process Completed With Code:  0
Test Result:  None
```

**Comment by isolver** [comment]
I can also now reproduce this on win10. Will fix this week.

**Comment by isolver** [comment]
This should now be working.
