### ISSUE TITLE
Can not create a TextBox instance

### ISSUE THREAD

**Issue by waa8128** [psychopy/psychopy#3379]
As title.
from psychopy import visual

textstimlike=visual.TextBox(
                            window=win,
                            text="This textbox looks most like a textstim.",
                            font_size=18,
                            font_color=[-1,-1,1],
                            color_space='rgb',
                            size=(1.8,.1),
                            pos=(0.0,.5),
                            units='norm'
                           )

The error is:
Traceback (most recent call last):
File "C:\Users\THINK\Desktop\test.py", line 61, in <module>
    units='norm'
  File "C:\ProgramData\Anaconda3\lib\site-packages\psychopy\contrib\lazy_import.py", line 119, in __call__
    obj = object.__getattribute__(self, '_resolve')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psychopy\contrib\lazy_import.py", line 88, in _resolve
    obj = factory(self, scope, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psychopy\contrib\lazy_import.py", line 203, in _import
    module = __import__(module_python_path, scope, scope, [member], level=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psychopy\visual\textbox\__init__.py", line 59, in <module>
    fm = getFontManager()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psychopy\visual\textbox\__init__.py", line 56, in getFontManager
    _system_font_manager = FontManager(mono_only)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psychopy\visual\textbox\fontmanager.py", line 79, in __init__
    self.updateFontInfo(monospace_only)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psychopy\visual\textbox\fontmanager.py", line 246, in updateFontInfo
    self.addFontFiles(fonts_found, monospace_only)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psychopy\visual\textbox\fontmanager.py", line 153, in addFontFiles
    face = Face(fp)
  File "C:\ProgramData\Anaconda3\lib\site-packages\freetype\__init__.py", line 991, in __init__
    raise FT_Exception(error)
freetype.ft_errors.FT_Exception: FT_Exception:  (cannot open resource)

**Comment by m-macaskill** [comment]
The code snippet provided above shouldn't run as given, as `win` is not defined. But as people can routinely create TextBox instances, this doesn't really belong here as an issue with the source code. I'll close this as an issue and suggest you go to the forum at https://discourse.psychopy.org, which is the venue for user support requests.
