### ISSUE TITLE
onIdle() reports that StdOutText has been deleted

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#3380]
```
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\_psychopyApp.py", line 864, in onIdle
    idle.doIdleTasks(app=self)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\idle.py", line 120, in doIdleTasks
    logging.flush()
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\logging.py", line 314, in flush
    logger.flush()
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\logging.py", line 300, in flush
    target.write(formatted[thisEntry] + '\n')
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\logging.py", line 208, in write
    stream.write(txt)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\runner\runner.py", line 888, in write
    StdOutRich.write(self, inStr, evt)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\stdOutRich.py", line 40, in write
    self.MoveEnd()  # always 'append' text rather than 'writing' it
RuntimeError: wrapped C/C++ object of type StdOutText has been deleted
```

**Comment by TEParsons** [comment]
This has all changed so much since 2020 that I'd be very surprised if this bug survived, so closing this
