### ISSUE TITLE
Callibrartion of Monitor

### ISSUE THREAD

**Issue by JKerzina** [psychopy/psychopy#3383]
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy3\psychopy\monitors\MonitorCenter.py", line 826, in onCalibGammaBtn
    screen=screen)
  File "C:\Program Files\PsychoPy3\psychopy\monitors\calibTools.py", line 968, in getLumSeries
    pos=(0, -0.85), rgb=[1, -1, -1])
  File "C:\Program Files\PsychoPy3\psychopy\visual\text.py", line 228, in __init__
    self.setText(text, log=False)
  File "C:\Program Files\PsychoPy3\psychopy\visual\text.py", line 376, in setText
    setAttribute(self, 'text', text, log)
  File "C:\Program Files\PsychoPy3\psychopy\tools\attributetools.py", line 141, in setAttribute
    setattr(self, attrib, value)
  File "C:\Program Files\PsychoPy3\psychopy\tools\attributetools.py", line 32, in __set__
    newValue = self.func(obj, value)
  File "C:\Program Files\PsychoPy3\psychopy\visual\text.py", line 367, in text
    self._setTextShaders(text)
  File "C:\Program Files\PsychoPy3\psychopy\visual\text.py", line 391, in _setTextShaders
    multiline=True, width=self._wrapWidthPix)  # width of the frame
  File "C:\Program Files\PsychoPy3\lib\site-packages\pyglet\text\__init__.py", line 453, in __init__
    multiline, dpi, batch, group)
  File "C:\Program Files\PsychoPy3\lib\site-packages\pyglet\text\__init__.py", line 275, in __init__
    dpi=dpi, batch=batch, group=group)
  File "C:\Program Files\PsychoPy3\lib\site-packages\pyglet\text\layout.py", line 805, in __init__
    self._wrap_lines_invariant()
  File "C:\Program Files\PsychoPy3\lib\site-packages\pyglet\text\layout.py", line 841, in _wrap_lines_invariant
    "When the parameters 'multiline' and 'wrap_lines' are True," \
AssertionError: When the parameters 'multiline' and 'wrap_lines' are True,the parameter 'width' must be a number.

What is it mean?

**Comment by mdcutone** [comment]
Hello @JKerzina 

Please provide the steps taken in order to replicate the error. Thank you.

**Comment by bchen93** [comment]
This error popped up for me when I tried to calibrate a monitor where the screen size and screen width was not defined (set at 0). Once you define those parameters the error should go away
