### ISSUE TITLE
Error when changing themes

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#3488]
When attempting to change themes I get this error. 

```
Traceback (most recent call last):
  File "C:\Users\Matthew\PycharmProjects\psychopy\psychopy\app\_psychopyApp.py", line 857, in onThemeChange
    self.theme = newTheme
  File "C:\Users\Matthew\PycharmProjects\psychopy\psychopy\app\_psychopyApp.py", line 883, in theme
    self._applyAppTheme()
  File "C:\Users\Matthew\PycharmProjects\psychopy\psychopy\app\_psychopyApp.py", line 892, in _applyAppTheme
    frame._applyAppTheme()
  File "C:\Users\Matthew\PycharmProjects\psychopy\psychopy\app\themes\_themes.py", line 309, in _applyAppTheme
    handlers[thisType](target)
  File "C:\Users\Matthew\PycharmProjects\psychopy\psychopy\app\themes\_themes.py", line 142, in applyToFrame
    target.GetAuiManager().Update()
  File "C:\Python37\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 6370, in Update
    self.DoUpdate()
  File "C:\Python37\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 6564, in DoUpdate
    self.Repaint()
  File "C:\Python37\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 8755, in Repaint
    client_dc = wx.BufferedDC(wx.ClientDC(self._frame), wx.Size(w, h))
wx._core.wxAssertionError: C++ assertion "m_buffer && m_buffer->IsOk()" failed at ..\..\src\common\dcbufcmn.cpp(132) in wxBufferedDC::UnMask(): invalid backing store

```

Issue affects current main branch.

**Comment by mdcutone** [comment]
Seems to prevent builder's theme from being updated.

**Comment by mdcutone** [comment]
Closing this because I can't replicate it. Might pop back up at some point.
