### ISSUE TITLE
Saving files to demo folders - Windows standalone

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3503]
On Windows, demo's can not save files to the demo directory when running from `C:\Program Files\PsychoPy3\Lib\site-packages\psychopy\demos` unless running app as administrator. For example,

```
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy3\Lib\site-packages\psychopy\demos\coder\experiment control\logFiles.py", line 33, in <module>
    level=logging.WARNING)  # errors, data and warnings will be sent to this logfile
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\logging.py", line 171, in __init__
    self.stream = codecs.open(f, filemode, encoding)
  File "C:\Program Files\PsychoPy3\lib\codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: 'logLastRun.log'
```

I think this issue would also exist for any experiment saving data files to the experiment folder. It is also an issue for starting any iohub experiment.

Should demo's be installed to a user folder instead of Program Files, for example `C:\Users\username\PsychoPy3\demos`?

**Comment by peircej** [comment]
This is true for mac too. In the past, Builder demos were saved out to user space (hence the "unpack demos..." in Builder>demos ) because Builder demos usually need to save data, but we didn't bother for Coder demos because they didn't typically save anything

**Comment by isolver** [comment]
But some do, including the iohub demos. Maybe we should just add a comment
on the top of  coder demos that need to be saved into a user writable
folder for it to work?

**Comment by TEParsons** [comment]
It would be cool to eventually use Pavlovia to manage demos - have a "Subscribe" button on projects on the site and then populate the demos menu in the app using your subscribed projects. That way we won't need to worry about unpacking, overwriting, etc. because it'll all be Git
