### ISSUE TITLE
colors.py demo exception

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3539]
While testing colors.py demo with the dev4 build, the following exception occurred:

```
Traceback (most recent call last):
  File ".psychopy\demos\coder\stimuli\colors.py", line 69, in <module>
    stim.draw()
  File ".\psychopy\visual\textbox2\textbox2.py", line 592, in draw
    self.box.setLineWidth(self.pallette['lineWidth']) # Use 1 as base if border width is none
  File ".\psychopy\visual\textbox2\textbox2.py", line 247, in pallette
    'fillColor': self._fillColor+0.1
  File ".\psychopy\colors.py", line 381, in __add__
    buffer.rgba = self.rgba + other
numpy.core._exceptions.UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
```

I was pressing the different color buttons and typing in random text when it occurred.

I'm also not able to select the left or right most color types displayed in the demo using the mouse.

**Comment by TEParsons** [comment]
Forgot to tag but this is fixed in #3541
