### ISSUE TITLE
Installation issue on Ubuntu 20.04 LTS of Psychopy 3 (Linux)

### ISSUE THREAD

**Issue by emmaducos** [psychopy/psychopy#3575]
Hello there, thank you for putting out there a super nice software !

I've been trying to install psychopy3 on my linux machine, but I can't open the software, as when I type "psychopy" after a successful installation, I get this error message :

```
pygame 2.0.1 (SDL 2.0.14, Python 3.6.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/educos/miniconda3/envs/psychopy/bin/psychopy", line 8, in <module>
    sys.exit(main())
  File "/home/educos/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/psychopyApp.py", line 100, in main
    start_app()
  File "/home/educos/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/psychopyApp.py", line 22, in start_app
    from psychopy.app._psychopyApp import PsychoPyApp
  File "/home/educos/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/_psychopyApp.py", line 58, in <module>
    from .utils import FileDropTarget
  File "/home/educos/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/utils.py", line 27, in <module>
    from . import pavlovia_ui
  File "/home/educos/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/pavlovia_ui/__init__.py", line 19, in <module>
    from .functions import *
  File "/home/educos/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/pavlovia_ui/functions.py", line 13, in <module>
    from ._base import PavloviaMiniBrowser, PavloviaCommitDialog
  File "/home/educos/miniconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/pavlovia_ui/_base.py", line 9, in <module>
    import wx.html2
  File "/home/educos/miniconda3/envs/psychopy/lib/python3.6/site-packages/wx/html2.py", line 15, in <module>
    from ._html2 import *
ImportError: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory
1.7224 	WARNING 	We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
```

I have tried through conda or through pip, following the documentation instructions. 
It seams the crux of the issue is the needed "libwebkitgtk" package, which I cannot find on apt.

when I tap:
`sudo apt-get install libwebkitgtk-1.0`
I get:
```
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Note : sélection de libwebkitgtk-1.0-0 pour l'expression rationnelle « libwebkitgtk-1.0 »
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
```

(sorry for the french version, basically it says it selected " libwebkitgtk-1.0-0 " for the given name, but nothing have been installed or updated.)

then when tapping:
`sudo apt-get install libwebkitgtk-1.0-0`
```
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Aucune version du paquet libwebkitgtk-1.0-0 n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source
E: Le paquet « libwebkitgtk-1.0-0 » n'a pas de version susceptible d'être installée
```

which means that no version the package is available, but it exist in their database. it means in general that the package is missing, obsolete or available only on another source.

is it possible to check the availability of this dependency, or to discard this dependancy, so we can run psychopy on modern ubuntu versions ?

**Comment by isolver** [comment]
Could you please try following the full Linux install instuctions, which can be found [here.](https://www.psychopy.org/download.html#linux)

For Ubuntu 20.04, it looks like there are only [wx wheels for Python 3.8](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/).

Thank you.

**Comment by emmaducos** [comment]
Dear Sol Simpson,

I have put extra care in following the instructions to install psychopy
through, pip, and it all seemed to work until I tried to launch psychopy.

I have doe the following steps :
- pip install psychopy
- download wxPython-4.1.1-cp38-cp38-linux_x86_64.whl
<https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.1.1-cp38-cp38-linux_x86_64.whl>,
which is the most recent wheel for my distribution (Linux Ubuntu 20.04 LTS)
- pip install the above downloaded wheel
- sudo apt-get the said packages
- pip install psychotoolbox successfully

I verified that I was using python 3.8.5

When I typed "psychopy" on the command line, I got the following error:

Traceback (most recent call last):
  File "/home/educos/miniconda3/bin/psychopy", line 8, in <module>
    sys.exit(main())
  File
"/home/educos/miniconda3/lib/python3.8/site-packages/psychopy/app/psychopyApp.py",
line 100, in main
    start_app()
  File
"/home/educos/miniconda3/lib/python3.8/site-packages/psychopy/app/psychopyApp.py",
line 22, in start_app
    from psychopy.app._psychopyApp import PsychoPyApp
  File
"/home/educos/miniconda3/lib/python3.8/site-packages/psychopy/app/_psychopyApp.py",
line 24, in <module>
    from . import themes
  File
"/home/educos/miniconda3/lib/python3.8/site-packages/psychopy/app/themes/__init__.py",
line 1, in <module>
    from ._themes import ThemeMixin, IconCache
  File
"/home/educos/miniconda3/lib/python3.8/site-packages/psychopy/app/themes/_themes.py",
line 5, in <module>
    import wx
  File
"/home/educos/miniconda3/lib/python3.8/site-packages/wx/__init__.py", line
17, in <module>
    from wx.core import *
  File "/home/educos/miniconda3/lib/python3.8/site-packages/wx/core.py",
line 12, in <module>
    from ._core import *
ImportError: libSDL2-2.0.so.0: cannot open shared object file: No such file
or directory
Does it mean that I can't use psychopy because no wheel exists for my
distribution in python 3.6 ?

Thank you for your help and support.


Le mar. 16 févr. 2021 à 12:59, Sol Simpson <notifications@github.com> a
écrit :

**Comment by isolver** [comment]
Thanks for reporting back on this issue.
It seems like libSDL2-2.0 is missing. Based on a stackover flow answer to a similar question, could you try:

```
sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0
```

and see if that installs the missing libs for you and fixes the issue?

> Does it mean that I can't use psychopy because no wheel exists for my
distribution in python 3.6 ?

Maybe, lets see if installing the missing libs helps.

Thanks again.

**Comment by emmaducos** [comment]
Dear Sol Simpson,

After installing the missing libraries as you suggested, I was able to open
the psychopy software for the first time.

I tried to run an experiment that I have just successfully ran on a windows
computer with psychopy.

The experiment started but crashed almost immediately, with the following
stdout:

Welcome to PsychoPy3!
v2020.2.10
1.2509     WARNING     We strongly recommend you activate the PTB sound
engine in PsychoPy prefs as the preferred audio engine. Its timing is
vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB',
'pyo', 'pygame'] (in that order).
23.0831     INFO     Loaded monitor calibration from ['2021_02_16 11:15']
23.1113     INFO     Investigating repo at /home/educos/ACClab/roughxp
23.1276     WARNING     We found a repository pointing to
https://gitlab.pavlovia.org/TanguyDelmas/roughxp.git but no user is logged
in for us to check it
Generating PsychoPy script...

########### Running: /home/educos/ACClab/roughxp/roughxp_lastrun.py
############
29.7633     INFO     Loaded monitor calibration from ['2021_02_16 11:15']
PsychHID-WARNING: Seems like the libX11 library was *not* initialized for
thread-safe mode,
PsychHID-WARNING: because the application host process omitted a required
call to
PsychHID-WARNING: XInitThreads() during its startup, as required for safe
operation!
PsychHID-WARNING: Unfortunately the application host process already used
XLib for
PsychHID-WARNING: something, e.g., for starting up its GUI, so i can not
safely work
PsychHID-WARNING: around this problem! Use of multi-threading in PsychHID()
might cause
PsychHID-WARNING: malfunctions or even a hard application crash!
PsychHID-WARNING: Please fix the application to call XInitThreads()
*before* calling
PsychHID-WARNING: any other libX11 X-Lib functions, or not to call X-Lib at
all before using this module.
PsychHID-WARNING: You could force me to call XInitThreads() by setting the
environment
PsychHID-WARNING: variable PSYCH_XINITTHREADS to any non-empty value as a
workaround, if
PsychHID-WARNING: you like living on the edge, at your own risk though!
PsychHID-WARNING: I will continue, but may malfunction or crash at some
point!
PsychHID-INFO: If you are using PsychoPy, simply upgrade to version 3.1.3
or later.
PsychHID-INFO: Otherwise, you can generally fix Python scripts/apps by
adding the following
PsychHID-INFO: snippet early enough at the beginning of script execution
under X11:
PsychHID-INFO: import ctypes
PsychHID-INFO: xlib = ctypes.cdll.LoadLibrary("libX11.so")
PsychHID-INFO: xlib.XInitThreads()

PTB-CRITICAL: In call to PsychSetThreadPriority(): Failed to set new
basePriority 2, tweakPriority 1, effective 1 [REALTIME] for thread (nil)
provided!
PsychHID: KbQueueStart: Failed to switch to realtime priority [Operation
not permitted].
##### Experiment ended. #####

I don't really understand the warnings concerning libX11. Do you have an
idea if it is the crux of the issue here ?
Or does the "We found a repository pointing to [...] but no user is logged
in for us to check it" warning an issue ?

Thank you again for your quick replies !


Le mer. 17 févr. 2021 à 14:46, Sol Simpson <notifications@github.com> a
écrit :

**Comment by isolver** [comment]
I'm not sure.
Could you try doing as part of the warnings suggest, and add the following to the very start of your script, maybe before importing psychopy:

```
import ctypes
xlib = ctypes.cdll.LoadLibrary("libX11.so")
xlib.XInitThreads()
``` 
@peircej , have you come across this PsychHID error before?

Thanks again.

**Comment by emmaducos** [comment]
I've added the suggested snippet before/after the psychopy import, but now
I get a warning that the libX11.so library is not present.

Traceback (most recent call last):
  File "/home/educos/ACClab/roughxp/roughxp_lastrun.py", line 17, in
<module>
    xlib = ctypes.cdll.LoadLibrary("libX11.so")
  File "/home/educos/miniconda3/lib/python3.8/ctypes/__init__.py", line
459, in LoadLibrary
    return self._dlltype(name)
  File "/home/educos/miniconda3/lib/python3.8/ctypes/__init__.py", line
381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libX11.so: cannot open shared object file: No such file or
directory

I have tried to look for the libx11 package, and found this page :
https://launchpad.net/ubuntu/+source/libx11

then I tried to install the latest package (libX11, libx11, libx11.so did
not worked):
sudo apt-get install libx11-6
To discover that it was already installed.

I have tried to change the script by changing the name of the imported
library :

import ctypes
xlib = ctypes.cdll.LoadLibrary("libx11-6.so")
xlib.XInitThreads()

But it did not worked, even with any combinaison of the X/x, with or
without the 6, with or without the .so.

I still get the same error :

OSError: libx11-6.so: cannot open shared object file: No such file or directory


Le mer. 17 févr. 2021 à 15:52, Sol Simpson <notifications@github.com> a
écrit :

**Comment by isolver** [comment]
I'm not sure why `xlib = ctypes.cdll.LoadLibrary("libX11.so")` is failing for you. That code runs for me on Mint Linux 18.x and 19.1. I'm trying to install Ubuntu 20.04 now and will try to reproduce the libX11 issue.

Regardless though, I also no longer seem to be able to get the `psychtoolbox` working on either of the above mentiond versions of Mint Linux. I can import it, but not use it. An example that does not even import psychopy gives the same `PsychHID-WARNING` messages posted above. If I add the suggested:

```
import ctypes
xlib = ctypes.cdll.LoadLibrary("libX11.so")
xlib.XInitThreads()
```

to the start of the script, it starts but then seg faults as soon as I make any call to `PsychHID()`.

Right now, I'm not sure what to suggest next. Suggestions are welcome. ;)

PsychoPy does not _need_ the psychtoolbox package to run, so I guess as a short term work around would be to uninstall the psychtoolbox package and use psychopy without it until we can figure out what is going on:

```
pip uninstall psychtoolbox
```

**Comment by isolver** [comment]
I've installed Ubuntu 20.04 and I cannot reproduce the X11 lib missing issue, so I'm not sure what to suggest for that, sorry. 

I'm still not able to run code that uses the psychtoolbox without issue though. I wonder if there is an issue with using anaconda python and psychtoolbox on linux?

If I run [this python psychtoolbox demo](https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/PsychPython/demos/hidtest_pythonic.py), I get this output:

```
Devices:
PsychHID-INFO: libX11 library not yet set up for thread-safe operation by host application, as required.
PsychHID-INFO: Now calling XInitThreads() myself, to fix this problem in a likely safe way.
```

So it seems that psychtoolbox is complaining that the python interpreter itself has not 'properly' setup libX11. 

followed by

```
Keyboards:
  3.0: Virtual core XTEST keyboard
  4.0: Power Button
  5.0: Video Bus
  8.0: Sleep Button
  9.0: Sony Visual Communication Camer
  10.0: AT Translated Set 2 keyboard
PTB-CRITICAL: In call to PsychSetThreadPriority(): Failed to set new basePriority 2, tweakPriority 1, effective 1 [REALTIME] for thread (nil) provided!
PsychHID: KbQueueStart: Failed to switch to realtime priority [Operation not permitted].
Segmentation fault (core dumped)
```
Wondering if psychtoolbox has to be run as root / sudo on linux? Have not been able to test this myself as I can't seem to run an anaconda python env. using sudo (get an error that python can not be found).

Anyone else able to help figure this out?

**Comment by peircej** [comment]
Have a look at the threads here:
https://discourse.psychopy.org/t/psychtoolbox-manylinux2010-wheels/8874/4
https://discourse.psychopy.org/t/psychopy-keyboard-keyboard-psychhid-kbqueuestart-memory-fault/12005

In short, I think you *could* solve the problem by setting Python to have the right privileges to update the priority (using nice). You shouldn't need to run it with sudo all the time but you might need sudo briefly to correct the privileges

**Comment by isolver** [comment]
Thanks for the suggestion @peircej, that fixed it for me on Ubuntu 20.04. 

Todo:
- [ ] update the install page for linux to include these extra _one time_ psychtoolbox setup steps:

1. Install octave and the psychtoolbox
```
sudo apt install octave
sudo apt install psychtoolbox-3-common
sudo apt install octave-psychtoolbox-3
```
2. Start octave from a terminal with admin privileges:
```
sudo octave --no-gui
```
3. Executed the (interactive) script from within octave:
```
run /usr/share/psychtoolbox-3/PsychLinuxConfiguration.m
```
4. Reboot the computer.

@emmaducos, can you let us know if you are also able to figure this out for your system?

Thank you.

**Comment by isolver** [comment]
Just tried the above steps on Mint Linux 18 and running the PsychLinuxConfiguration.m file from octave just returns immediately with nothing printed and nothing fixed. ;(

For Mint Linux 18 I ended up fixing the psychopy seg fault and priority issues on this version of linux by [following these instuctions](https://discourse.psychopy.org/t/installation-headaches-and-partly-fixes-on-ubuntu-20-04/16476/6) and rebooting, which are also much simplier.

**Comment by 104H** [comment]
I had the same issue and check the log file `~/.psychopy3/last_app_load.log`

`Traceback (most recent call last):
  File "/usr/bin/psychopy", line 11, in <module>
    load_entry_point('PsychoPy==2020.1.3', 'gui_scripts', 'psychopy')()
  File "/usr/lib/python3/dist-packages/psychopy/app/psychopyApp.py", line 100, in main
    start_app()
  File "/usr/lib/python3/dist-packages/psychopy/app/psychopyApp.py", line 28, in start_app
    app = PsychoPyApp(0, showSplash=showSplash)
  File "/usr/lib/python3/dist-packages/psychopy/app/_psychopyApp.py", line 210, in __init__
    self.onInit(testMode=testMode, **kwargs)
  File "/usr/lib/python3/dist-packages/psychopy/app/_psychopyApp.py", line 246, in onInit
    from psychopy.app import coder, builder, runner, dialogs
  File "/usr/lib/python3/dist-packages/psychopy/app/coder/__init__.py", line 9, in <module>
    from .coder import *  # pylint: disable=W0401
  File "/usr/lib/python3/dist-packages/psychopy/app/coder/coder.py", line 39, in <module>
    from .. import pavlovia_ui
  File "/usr/lib/python3/dist-packages/psychopy/app/pavlovia_ui/__init__.py", line 19, in <module>
    from .functions import *
  File "/usr/lib/python3/dist-packages/psychopy/app/pavlovia_ui/functions.py", line 13, in <module>
    from ._base import PavloviaMiniBrowser, PavloviaCommitDialog
  File "/usr/lib/python3/dist-packages/psychopy/app/pavlovia_ui/_base.py", line 9, in <module>
    import wx.html2
ModuleNotFoundError: No module named 'wx.html2'`

Then I did a `find /usr/lib/python3/dist-packages/ | grep html2` and this returned an empty set. So there is no such module as html2 in wxPython==4.0.7

So I went inside `/usr/lib/python3/dist-packages/psychopy/app/pavlovia_ui/_base.py` and changed `import wx.html2` to `import wx.html`.

The I ran `psychopy` and the software runs.

I have not prepared or run any experiments yet.

**Comment by emmaducos** [comment]
Sorry for my late reply, but this is my current state in using psychopy in Linux Ubuntu 20.04 LTS:

As of today, I have updated & upgraded everything I could with apt-get for linux, I have done the same with conda.
I uninstalled all previous instances of psychopy/psychtoolbox that I could find on my computer.

I created a conda environment with python 3.8.5, and followed the installation process:
pip install psychopy

it installed the latest version of psychopy (psychopy-2021.1.3).

and it works without issues for now : I was able to open the GUI with the psychopy command, and run a "hello world" dummy experiment.

Psychtoolbox seems to not be installed, I got this warning : 
0.9840     WARNING     Import Error: No module named 'psychtoolbox'. Using event module for keyboard component.

But I don't know yet If i'll need it. 

thank you for your help !

**Comment by TEParsons** [comment]
Closing as not planned; now that we have PsychoPy Studio which doesn't use wxPython.
