### ISSUE TITLE
Unhandled error when changing themes

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#3815]
I tried to change the coder document and output font and got this error. Possibly caused by a recent change in wx, so not sure if our bug or an upstream fix is needed.

```
Traceback (most recent call last):
  File "C:\Users\Matthew Cutone\PycharmProjects\psychopy\psychopy\app\preferencesDlg.py", line 869, in OnApplyClicked
    self.applyPrefs()  # saves the preferences
  File "C:\Users\Matthew Cutone\PycharmProjects\psychopy\psychopy\app\preferencesDlg.py", line 846, in applyPrefs
    self.app.theme = self.app.theme
  File "C:\Users\Matthew Cutone\PycharmProjects\psychopy\psychopy\app\_psychopyApp.py", line 923, in theme
    self._applyAppTheme()
  File "C:\Users\Matthew Cutone\PycharmProjects\psychopy\psychopy\app\_psychopyApp.py", line 932, in _applyAppTheme
    frame._applyAppTheme()
  File "C:\Users\Matthew Cutone\PycharmProjects\psychopy\psychopy\app\themes\_themes.py", line 309, in _applyAppTheme
    handlers[thisType](target)
  File "C:\Users\Matthew Cutone\PycharmProjects\psychopy\psychopy\app\themes\_themes.py", line 142, in applyToFrame
    target.GetAuiManager().Update()
  File "C:\Users\Matthew Cutone\AppData\Local\Programs\Python\Python36\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 6370, in Update
    self.DoUpdate()
  File "C:\Users\Matthew Cutone\AppData\Local\Programs\Python\Python36\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 6564, in DoUpdate
    self.Repaint()
  File "C:\Users\Matthew Cutone\AppData\Local\Programs\Python\Python36\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 8755, in Repaint
    client_dc = wx.BufferedDC(wx.ClientDC(self._frame), wx.Size(w, h))
wx._core.wxAssertionError: C++ assertion "m_buffer && m_buffer->IsOk()" failed at ..\..\src\common\dcbufcmn.cpp(132) in wxBufferedDC::UnMask(): invalid backing store

```

**Comment by TEParsons** [comment]
Are you still getting this?

**Comment by mdcutone** [comment]
It honestly happened randomly. I have a feeling wx being updated cleared this error.
