### ISSUE TITLE
Cannot open preferences in dev branch: "Failed to find icon"

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3926]
file > preferences produces error in dev branch:

Traceback (most recent call last):
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\themes\_themes.py", line 816, in _loadBitmap
    im = wx.Image(filename)
TypeError: Image(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'NoneType'
  overload 3: argument 1 has unexpected type 'NoneType'
  overload 4: argument 1 has unexpected type 'NoneType'
  overload 5: argument 1 has unexpected type 'NoneType'
  overload 6: argument 1 has unexpected type 'NoneType'
  overload 7: argument 1 has unexpected type 'NoneType'
  overload 8: argument 1 has unexpected type 'NoneType'
  overload 9: argument 1 has unexpected type 'NoneType'
  overload 10: argument 1 has unexpected type 'NoneType'
  overload 11: argument 1 has unexpected type 'NoneType'
  overload 12: argument 1 has unexpected type 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\_psychopyApp.py", line 764, in showPrefs
    prefsDlg = PreferencesDlg(app=self)
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\preferencesDlg.py", line 557, in __init__
    self.populatePrefs()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\preferencesDlg.py", line 733, in populatePrefs
    icon = self.app.iconCache.getBitmap(choice.Text)
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\themes\_themes.py", line 843, in getBitmap
    self._loadBitmap(name, theme, emblem=emblem, size=size)
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\themes\_themes.py", line 820, in _loadBitmap
    .format(name, theme, size, emblem))
FileNotFoundError: Failed to find icon name=FlowTop_CompRight, theme=dark, size=48, emblem=None

**Comment by TEParsons** [comment]
This is git ghosts I think - *should* be a problem unique to people pulling the version from Git and should only affect those who've previously pulled revisions before this name changed happened. If you go to psychopy->app->Resources and find those FlowTop_CompRight files and delete them then checkout from Git again it should fix this
