### ISSUE TITLE
Cannot add loops to flow in dev branch

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3947]
selecting insert loop and then selecting the location on the flow for insertion produces the following error:
```
Traceback (most recent call last):
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\builder\builder.py", line 3189, in OnMouse
    self.setLoopPoint2()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\builder\builder.py", line 3066, in setLoopPoint2
    self.insertLoop()  # there's only one place - use it
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\builder\builder.py", line 3071, in insertLoop
    helpUrl=self.app.urls['builder.loops'])
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\builder\dialogs\__init__.py", line 1067, in __init__
    self.show()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\builder\dialogs\__init__.py", line 766, in show
    self.Validate()  # disables OKbtn if bad name, syntax error, etc
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\app\builder\dialogs\__init__.py", line 1099, in Validate
    return bool(self.warnings._valid)
AttributeError: 'WarningManager' object has no attribute '_valid'
```

**Comment by peircej** [comment]
I just saw the same 😦
