### ISSUE TITLE
Adding a loop to an empty timeline raises an error

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#3959]
I tried to add a loop to an empty timeline, which admittedly doesn't make a lot of sense to do. It did raise an error though:
```
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 3171, in OnMouse
    self.setLoopPoint2()
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 3045, in setLoopPoint2
    self.drawEntryPoints([self.entryPointPosList[0], x])
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 3447, in drawEntryPoints
    self.pdc.DrawCircle(pos, self.linePos[1], ptSize)
TypeError: PseudoDC.DrawCircle(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'NoneType'
  overload 2: argument 1 has unexpected type 'NoneType'
```
PS - This happened in an experiment that originally contained 4 routines, that I had first deleted.

**Comment by TEParsons** [comment]
I think the solution here is to grey out the Add Loop button when there's no routines, so rather than letting people do this and then erroring because it doesn't make any sense, we just stop them doing it in the first place.
