### ISSUE TITLE
Issue opening preferences dialog (+workaround)

### ISSUE THREAD

**Issue by martinthedinov** [psychopy/psychopy#4090]
When I was trying to open the preferences to change the order of sound drivers, I get this error:

`Traceback (most recent call last):
  File "/home/thebrain/Desktop/Maaind/dev/NOVA/.venv/lib/python3.9/site-packages/psychopy/app/themes/_themes.py", line 814, in _loadBitmap
    im = wx.Image(filename)
TypeError: Image(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'NoneType'
  overload 3: argument 1 has unexpected type 'NoneType'
  overload 4: argument 1 has unexpected type 'NoneType'
  overload 5: argument 1 has unexpected type 'NoneType'
  overload 6: argument 1 has unexpected type 'NoneType'
  overload 7: argument 1 has unexpected type 'NoneType'
  overload 8: argument 1 has unexpected type 'NoneType'
  overload 9: argument 1 has unexpected type 'NoneType'
  overload 10: argument 1 has unexpected type 'NoneType'
  overload 11: argument 1 has unexpected type 'NoneType'
  overload 12: argument 1 has unexpected type 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thebrain/Desktop/Maaind/dev/NOVA/.venv/lib/python3.9/site-packages/psychopy/app/_psychopyApp.py", line 754, in showPrefs
    prefsDlg = PreferencesDlg(app=self)
  File "/home/thebrain/Desktop/Maaind/dev/NOVA/.venv/lib/python3.9/site-packages/psychopy/app/preferencesDlg.py", line 557, in __init__
    self.populatePrefs()
  File "/home/thebrain/Desktop/Maaind/dev/NOVA/.venv/lib/python3.9/site-packages/psychopy/app/preferencesDlg.py", line 733, in populatePrefs
    icon = self.app.iconCache.getBitmap(choice.Text)
  File "/home/thebrain/Desktop/Maaind/dev/NOVA/.venv/lib/python3.9/site-packages/psychopy/app/themes/_themes.py", line 842, in getBitmap
    self._loadBitmap(name, theme, emblem=emblem, size=size)
  File "/home/thebrain/Desktop/Maaind/dev/NOVA/.venv/lib/python3.9/site-packages/psychopy/app/themes/_themes.py", line 816, in _loadBitmap
    raise FileNotFoundError("Failed to find icon name={}, theme={}, "
FileNotFoundError: Failed to find icon name=FlowTop_CompRight, theme=light, size=48, emblem=None
`

Seems to be related to other image related issues PsychoPy is having lately. If anyone else hits this, you can get around this issue by commenting out the following 2 lines in `preferencesDlg.py`:

`icon = self.app.iconCache.getBitmap(choice.Text)
choice.SetBitmap(icon)`

Seems to leave everything else intact. 

This issue is happening on PsychoPy v2021.1.4 on Ubuntu 21.04 with Python 3.9.5.

**Comment by peircej** [comment]
That's fixed by this commit (and in 2021.2.0)
https://github.com/psychopy/psychopy/pull/3755
