### ISSUE TITLE
BUG with Ubuntu 18.04 and Python 3.6 - Stack Smashing error

### ISSUE THREAD

**Issue by kappa95** [psychopy/psychopy#4150]
Hi community, 
I have installed Psychopy with Python 3.6.9 on Ubuntu 18.04. I am trying the demo code of the [tutorial](https://www.psychopy.org/coder/codeStimuli.html) but i get the following output:
```bash
pygame 2.0.1 (SDL 2.0.14, Python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
*** stack smashing detected ***: <unknown> terminated
```

I have also tried to change the stack limits with: `ulimit -s unlimited` without success. 

It is also impossible to use directly from the terminal the `psychopy` command because it results not installed.
I tried also to install psychopy with python2 but it is not compatible anymore.
I have a laptop with 16GB of RAM and Ryzen5 2500U, Psychopy3 version: 2021.2.0.

How can i solve?

**EDIT:** I have installed everything using: `sudo -H python3 -m pip install <name_package>` and now I can open the builder and coder...but anyway I get always `*** stack smashing detected ***: <unknown> terminated` error when executed by shell or another IDE.

This happens also when I run in the Coder with any window with Stimuli.
`last_app_load.log`:

```
3.6535 	WARNING 	Speech-to-text recognition module not available (use command `pip install SpeechRecognition` to get it. Transcription will be unavailable.
3.7533 	WARNING 	We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
```
Others error shown:
```bash
Traceback (most recent call last):
  File "/home/kappa95/.local/lib/python3.6/site-packages/psychopy/app/runner/runner.py", line 845, in removeTask
    self.app.updateWindowMenu()
  File "/home/kappa95/.local/lib/python3.6/site-packages/psychopy/app/_psychopyApp.py", line 563, in updateWindowMenu
    frame.windowMenu.updateFrames()
  File "/home/kappa95/.local/lib/python3.6/site-packages/psychopy/app/utils.py", line 483, in updateFrames
    if frame.filename:
  File "/home/kappa95/.local/lib/python3.6/site-packages/psychopy/app/runner/runner.py", line 94, in filename
    return self.panel.expCtrl.GetItem(self.panel.currentSelection).Text
wx._core.wxAssertionError: C++ assertion ""item.m_itemId >= 0 && (size_t)item.m_itemId < GetItemCount()"" failed at /home/wxpy/wxPython-4.1.1/ext/wxWidgets/src/generic/listctrl.cpp(3759) in GetItem(): invalid item index in GetItem

```
Do you know how can i solve?

**Comment by TEParsons** [comment]
Closing this as we no longer recommend running the wx app (PsychoPy Standalone) on Linux, PsychoPy Studio is packaged as an AppImage file which is much easier to install.
