### ISSUE TITLE
Eyetracking demo: Error on launch 2021.2.2 iohub issue?

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#4208]
I get the following error when launching the eyetracking demo in builder 2021.2.2 on windows (app launched from pycharm)- does anyone else get this? looks like an iohub issue?

```
## Running: C:\Users\44797\Documents\PsychoPy_demos\2021.2\Feature Demos\eyetracking\eyetracking_lastrun.py ##
pygame 2.0.1 (SDL 2.0.14, Python 3.6.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Error during device creation ....
Traceback (most recent call last):
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\server.py", line 667, in createNewMonitoredDevice
    dev_data = self.addDeviceToMonitor(dev_cls_name, dev_conf)
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\server.py", line 833, in addDeviceToMonitor
    dev_instance = DeviceClass(dconfig=dev_conf)
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\devices\display\__init__.py", line 56, in __init__
    self._addRuntimeInfoToDisplayConfig()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\devices\display\__init__.py", line 516, in _addRuntimeInfoToDisplayConfig
    self._createPsychopyCalibrationFile()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\devices\display\__init__.py", line 704, in _createPsychopyCalibrationFile
    px, py = self.getPixelResolution()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\devices\display\__init__.py", line 200, in getPixelResolution
    return self.getConfiguration()['runtime_info']['pixel_resolution']
TypeError: 'NoneType' object is not subscriptable
Error during device creation ....
Traceback (most recent call last):
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\server.py", line 667, in createNewMonitoredDevice
    dev_data = self.addDeviceToMonitor(dev_cls_name, dev_conf)
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\server.py", line 833, in addDeviceToMonitor
    dev_instance = DeviceClass(dconfig=dev_conf)
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\devices\display\__init__.py", line 56, in __init__
    self._addRuntimeInfoToDisplayConfig()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\devices\display\__init__.py", line 516, in _addRuntimeInfoToDisplayConfig
    self._createPsychopyCalibrationFile()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\devices\display\__init__.py", line 704, in _createPsychopyCalibrationFile
    px, py = self.getPixelResolution()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\devices\display\__init__.py", line 200, in getPixelResolution
    return self.getConfiguration()['runtime_info']['pixel_resolution']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\server.py", line 601, in _addDevices
    self.createNewMonitoredDevice(dev_cls_name, dev_conf)
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\server.py", line 680, in createNewMonitoredDevice
    raise ioHubError('Error during device creation ....')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Error during device creation ....',)

GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
0.5463     WARNING     Speech-to-text recognition module not available (use command `pip install SpeechRecognition` to get it. Transcription will be unavailable.
1.1135     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
5.3450     WARNING     Requested an unavailable screen number - using first available.
5.3573     WARNING     User requested fullscreen with size [1280  800], but screen is actually [1920, 1200]. Using actual size
Error in ioSever.shutdown():
Traceback (most recent call last):
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\server.py", line 971, in shutdown
    del self._hookManager
AttributeError: _hookManager
ioHub Server Process Completed With Code:  0
_addDeviceView: Error adding class. 
Traceback (most recent call last):
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\client\__init__.py", line 1060, in _addDeviceView
    d = local_class(self, dev_cls_name, dev_config)
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\client\keyboard.py", line 208, in __init__
    self._reporting = self.isReportingEvents()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\client\__init__.py", line 146, in __getattr__
    raise AttributeError(self, name)
AttributeError: (<psychopy.iohub.client.keyboard.Keyboard object at 0x000001529B330A20>, 'isReportingEvents')
Traceback (most recent call last):
  File "C:\Users\44797\Documents\PsychoPy_demos\2021.2\Feature Demos\eyetracking\eyetracking_lastrun.py", line 173, in <module>
    calibration.run()
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\hardware\eyetracker.py", line 207, in run
    self.last = self.eyetracker.runSetupProcedure(dict(self))
  File "C:\Users\44797\PycharmProjects\psychopy\psychopy\iohub\client\__init__.py", line 146, in __getattr__
    raise AttributeError(self, name)
AttributeError: (<psychopy.iohub.client.ioHubDeviceView object at 0x000001529B1F46D8>, 'runSetupProcedure')
```

**Comment by isolver** [comment]
the demo seems to be OK for me. What screen number is the demo tryng to use? One of the errors / warnings you get suggests the requested screen number does not exist. The demo in the release branch is set to use the first screen, so that seems correct. 

```
5.3450     WARNING     Requested an unavailable screen number - using first available.
```

thank you

**Comment by isolver** [comment]
With that said, iohub should probably be defaulting back to the first monitor in cases like this (like psychopy itself does), instead of raising an error and crashing out.

**Comment by RebeccaHirst** [comment]
Hi @isolver sorry about that - yes you are correct. I was trying to use screen 2 (I had a second monitor plugged in) - it runs fine with one monitor and screen number set to 1. Thanks!
