### ISSUE TITLE
2022.1.1: graphical issues

### ISSUE THREAD

**Issue by dcnieho** [psychopy/psychopy#4722]
I have just installed v2022.1.1 standalone on several machines (both a Windows 10 and a Windows server machine), and for i observe the following:
- dots demo: the dots don't move but are static. no error messages
- benchmark: random dots don't move at any of the dot numbers

I have some more complicated code with shapestims to run that suddenly doesn't work well, but haven't isolated that to a minimal example yet. I do note that trying to run the shapes.py demo fails with the following error:
```
## Running: C:\Program Files\PsychoPy\lib\site-packages\psychopy\demos\coder\stimuli\shapes.py ##
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
1.6686     WARNING     Monitor specification not found. Creating a temporary one...
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\demos\coder\stimuli\shapes.py", line 32, in <module>
    donut = ShapeStim(win, vertices=donutVert, fillColor='orange', lineWidth=0, size=.75, pos=(-.2, -.25))
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\contrib\lazy_import.py", line 118, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\shape.py", line 486, in __init__
    self.vertices = vertices
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\shape.py", line 553, in vertices
    WindowMixin.vertices.fset(self, value)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\basevisual.py", line 1378, in vertices
    self._vertices = Vertices(value, obj=self, flip=self.flip, anchor=self.anchor)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\layout.py", line 640, in __init__
    assert len(verts.shape) == 2, (
AssertionError: Vertices must be coercible to a Nx2 numpy array
################ Experiment ended with exit code 1 [pid:93284] #################
```
a further error:
```
## Running: C:\Program Files\PsychoPy\lib\site-packages\psychopy\demos\coder\stimuli\stim3d.py ##
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Alert 8105: Color space attribute `.colorSpace` is no longer in use, as colors are no longer tied to one space.
Hello from the pygame community. https://www.pygame.org/contribute.html
For more info see https://docs.psychopy.org/alerts/8105.htmlAlert 8110: RGB attribute `.diffuseRGB` is no longer in use, as non-RGB colors now handle their own conversion.
For more info see https://docs.psychopy.org/alerts/8110.htmlTraceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\demos\coder\stimuli\stim3d.py", line 18, in <module>
    redLight = LightSource(win, pos=(0, 1, 0), diffuseColor=(.5, 0, 0),
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\contrib\lazy_import.py", line 118, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\stim3d.py", line 89, in __init__
    self.diffuseColor = diffuseColor
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\stim3d.py", line 139, in diffuseColor
    setColor(self, value, colorSpace=self.colorSpace, operation=None,
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\helpers.py", line 222, in setColor
    setattr(obj, colorAttrib, color)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\stim3d.py", line 138, in diffuseColor
    self._diffuseColor = np.asarray(value, np.float32)
TypeError: float() argument must be a string or a number, not 'Color'
################ Experiment ended with exit code 1 [pid:98368] #################
```

**Comment by dcnieho** [comment]
I see I'm not the only one that found this: https://discourse.psychopy.org/t/bug-with-random-dot-stimulus/27913
@marcus-nystrom as its relevant to him

**Comment by m-macaskill** [comment]
This has been reported previously: https://github.com/psychopy/psychopy/issues/4691
Fixed by: https://github.com/psychopy/psychopy/pull/4694

i.e. You should see this resolved in the bug fix release 2022.1.2, available now.

If the ShapeStim error is unrelated and continues to happen in 2021.1.2, you should raise an issue specifically for that.

**Comment by dcnieho** [comment]
Thanks! Should i file a separate bug for the other two issues (non-working
demos)?

**Comment by m-macaskill** [comment]
Yes please - it is difficult to tease out and deal with separate problems reported within a single issue - e.g. I hadn't actually noted that there were three problems here until you pointed it out.

PS please say hello to Marcus for us.

@TEParsons  The `shapes.py` issue reported above still occurs in release 2022.1.2 -  is this due to similar reasons as the DotStim bug - i.e. something to do with vertices?
