### ISSUE TITLE
pyglet error in showing bengali text

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [psychopy/psychopy#4756]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: Windows 10
- Psycopg version: 
- Python version: 3.8
- PostgreSQL version:
- pip version

**Describe the bug**
Please let us know:

1: what you did

We were creating text prompts on screen with bengali text.

2: what you expected to happen

The text to be shown on screen as typed in events

3: what happened instead

Text not shown, traceback generated. 

Traceback:

```
Generating PsychoPy script...

############ Running: C:\Users\ELKL7JU\Desktop\untitled_lastrun.py #############
43.8417     INFO     Loaded monitor calibration from ['2021_07_14 02:30']
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
WARNING: pytables package not found. ioHub functionality will be disabled.
1.4189     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
5.6028     WARNING     User requested fullscreen with size [1024  768], but screen is actually [1440, 900]. Using actual size
0.8214     WARNING     Monitor specification not found. Creating a temporary one...
Traceback (most recent call last):
  File "C:\Users\ELKL7JU\Desktop\untitled_lastrun.py", line 94, in <module>
    text = visual.TextStim(win=win, name='text',
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\text.py", line 222, in __init__
    self.setText(text, log=False)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\text.py", line 380, in setText
    setAttribute(self, 'text', text, log)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\tools\attributetools.py", line 134, in setAttribute
    setattr(self, attrib, value)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\tools\attributetools.py", line 27, in __set__
    newValue = self.func(obj, value)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\text.py", line 371, in text
    self._setTextShaders(text)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\text.py", line 389, in _setTextShaders
    self._pygletTextObj = pyglet.text.Label(
  File "C:\Program Files\PsychoPy\lib\site-packages\pyglet\text\__init__.py", line 452, in __init__
    super(Label, self).__init__(document, x, y, width, height,
  File "C:\Program Files\PsychoPy\lib\site-packages\pyglet\text\__init__.py", line 273, in __init__
    super(DocumentLabel, self).__init__(document,
  File "C:\Program Files\PsychoPy\lib\site-packages\pyglet\text\layout.py", line 820, in __init__
    self.document = document
  File "C:\Program Files\PsychoPy\lib\site-packages\pyglet\text\layout.py", line 929, in _set_document
    self._init_document()
  File "C:\Program Files\PsychoPy\lib\site-packages\pyglet\text\layout.py", line 1043, in _init_document
    self._update()
  File "C:\Program Files\PsychoPy\lib\site-packages\pyglet\text\layout.py", line 966, in _update
    lines = self._get_lines()
  File "C:\Program Files\PsychoPy\lib\site-packages\pyglet\text\layout.py", line 942, in _get_lines
    glyphs = self._get_glyphs()
  File "C:\Program Files\PsychoPy\lib\site-packages\pyglet\text\layout.py", line 1085, in _get_glyphs
    glyphs.extend(font.get_glyphs(text[start:end]))
  File "C:\Program Files\PsychoPy\lib\site-packages\pyglet\font\base.py", line 394, in get_glyphs
    self.glyphs[c] = glyph_renderer.render(c)
  File "C:\Program Files\PsychoPy\lib\site-packages\pyglet\font\win32.py", line 432, in render
    ord(text), ord(text), byref(abc)):
TypeError: ord() expected a character, but string of length 2 found
################# Experiment ended with exit code 1 [pid:924] ##################
54.1004     INFO     Loaded monitor calibration from ['2021_07_14 02:30']

```

This is the same as this issue in pyglet: https://github.com/pyglet/pyglet/issues/540#issuecomment-1090259268

**Comment by TEParsons** [comment]
Are you running online as well as in Python? If not, you could try doing the same thing but with TextBox - which uses our own glyph rendering rather than relying on Pyglet

**Comment by TEParsons** [comment]
Closing this as it's an upstream issue and Pyglet seem to have resolved it (the linked issue is closed, at least)

Please reopen if the bug persists
