### ISSUE TITLE
[bug] error with upgrade dialog by open it twice

### ISSUE THREAD

**Issue by shun2wang** [psychopy/psychopy#4776]
If I open the upgrade dialog and then close the dialog, when trying to open the dialog again, it throws the following error info:

```
Traceback (most recent call last):
  File "D:\Program Files\Psychopy\lib\site-packages\psychopy\app\_psychopyApp.py", line 670, in openUpdater
    dlg = connections.InstallUpdateDialog(parent=None, ID=-1, app=self)
  File "D:\Program Files\Psychopy\lib\site-packages\psychopy\app\connections\updates.py", line 325, in __init__
    self.updateStatus()
  File "D:\Program Files\Psychopy\lib\site-packages\psychopy\app\connections\updates.py", line 341, in updateStatus
    elif (parse_version(self.latest['version'])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by shun2wang** [comment]
closed by https://github.com/psychopy/psychopy/pull/4783
