### ISSUE TITLE
Error starting ioHub server: ioHub startup failed

### ISSUE THREAD

**Issue by nolanrbrady** [psychopy/psychopy#4872]
I am just doing the HelloWorld example from the documentation and keep having the script freeze and crash. It's showing the following error:
```
##### Running: /Users/nolanbrady/Desktop/LabResearch/Debugging_lastrun.py ######
5498.1356     INFO     Loaded monitor calibration from ['2022_06_01 11:02']
2022-06-01 12:33:43.252 python[20398:653450] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/f_/0f3gmdgs0db0f5gf8gg2874c0000gn/T/org.opensciencetools.psychopy.savedState
Fontconfig warning: ignoring UTF-8: not a valid region tag
2022-06-01 12:33:48.031 python[20398:653450] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7f99923b9550>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-06-01 12:33:48.032 python[20398:653450] Warning: Expected min height of view: (<NSButton: 0x7f99615df0e0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-06-01 12:33:48.034 python[20398:653450] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7f99615e2400>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-06-01 12:33:48.036 python[20398:653450] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7f99615eb800>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
Traceback (most recent call last):
1.3448     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
ioHub Server Process Completed With Code:  Negsignal.SIGSEGV
  File "/Users/nolanbrady/Desktop/LabResearch/Debugging_lastrun.py", line 89, in <module>
    ioServer = io.launchHubServer(window=win, **ioConfig)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/contrib/lazy_import.py", line 118, in __call__
    return obj(*args, **kwargs)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/iohub/client/connect.py", line 256, in launchHubServer
    return ioHubConnection(iohub_config)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/iohub/client/__init__.py", line 296, in __init__
    raise RuntimeError('Error starting ioHub server: {}'.format(self.iohub_status))
RuntimeError: Error starting ioHub server: ioHub startup failed.
```
I read elsewhere that if you changed Settings -> Input -> Keyboard Backend from `ioHub` to `PsychToolbox` or `Pyglet` it fixes the issue for some people however for me `PsychToolbox` causes an immediate crash and `Pyglet` gives the following error:
```
##### Running: /Users/nolanbrady/Desktop/LabResearch/Debugging_lastrun.py ######
6229.2563     INFO     Loaded monitor calibration from ['2022_06_01 11:02']
2022-06-01 12:45:54.759 python[20632:664589] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/f_/0f3gmdgs0db0f5gf8gg2874c0000gn/T/org.opensciencetools.psychopy.savedState
Fontconfig warning: ignoring UTF-8: not a valid region tag
2022-06-01 12:45:59.908 python[20632:664589] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7f8012224e70>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-06-01 12:45:59.909 python[20632:664589] Warning: Expected min height of view: (<NSButton: 0x7f8012242b70>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-06-01 12:45:59.911 python[20632:664589] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7f80122464d0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-06-01 12:45:59.913 python[20632:664589] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7f801224fcf0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
Traceback (most recent call last):
1.4980     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
  File "/Users/nolanbrady/Desktop/LabResearch/Debugging_lastrun.py", line 88, in <module>
    Text = visual.TextStim(win=win, name='Text',
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/visual/text.py", line 223, in __init__
    self.setText(text, log=False)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/visual/text.py", line 383, in setText
    setAttribute(self, 'text', text, log)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/tools/attributetools.py", line 134, in setAttribute
    setattr(self, attrib, value)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/tools/attributetools.py", line 27, in __set__
    newValue = self.func(obj, value)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/visual/text.py", line 374, in text
    self._setTextShaders(text)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/visual/text.py", line 392, in _setTextShaders
    self._pygletTextObj = pyglet.text.Label(
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/text/__init__.py", line 473, in __init__
    self.document.set_style(0, len(self.document.text), {
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/text/document.py", line 596, in set_style
    return super(UnformattedDocument, self).set_style(
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/text/document.py", line 505, in set_style
    self.dispatch_event('on_style_text', start, end, attributes)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/event.py", line 408, in dispatch_event
    if handler(*args):
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/text/layout.py", line 1372, in on_style_text
    self._init_document()
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/text/layout.py", line 1336, in _init_document
    self._update()
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/text/layout.py", line 1247, in _update
    lines = self._get_lines()
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/text/layout.py", line 1224, in _get_lines
    glyphs = self._get_glyphs()
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/text/layout.py", line 1384, in _get_glyphs
    glyphs.extend(font.get_glyphs(text[start:end]))
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/font/base.py", line 398, in get_glyphs
    self.glyphs[c] = glyph_renderer.render(c)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/font/quartz.py", line 134, in render
    glyph = self.font.create_glyph(glyph_image)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/font/base.py", line 361, in create_glyph
    texture = self.texture_class.create_for_size(GL_TEXTURE_2D,
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/image/__init__.py", line 1545, in create_for_size
    glTexImage2D(target, 0,
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pyglet/gl/lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid value'
```
If anyone has any idea how to get past this I would be very grateful for advice.
Thank you!

**Comment by nolanrbrady** [comment]
Just in case anyone else is struggling I sorted this out by upgrading python to a version higher than 3.7.x, deleting the pre-installed version of psychopy, and finally reinstalling it with `brew install --cask psychopy`.
