### ISSUE TITLE
PsychoPy3 (2022.1.4 and 2020.2.10) still crashing in Monterey 12.3.1

### ISSUE THREAD

**Issue by NUTANLab** [psychopy/psychopy#4874]
Our Mac version is Monterey 12.3.1, and we've recently tried downloading PsychoPy3 versions 2022.1.4 and 2020.2.10 per this post and recommendations: https://github.com/psychopy/psychopy/issues/4812. The application isn't starting in either version; the splash screen appears and then goes away and nothing more happens. We would prefer to use the most recent version, if possible.

When we tried version 2020.2.10, these are the errors we get:

Welcome to PsychoPy3!
v2020.2.10
16.4709     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
Generating PsychoPy script...

############ Running: /Users/tanlab/Documents/tryagainx3_lastrun.py ############
145.3497     INFO     Loaded monitor calibration from ['2021_07_09 11:43']
PsychHID-ERROR: Could not enumerate and attach to all HID devices (HIDBuildDeviceList(0,0) failed)!
PsychHID-ERROR: One reason could be that some HID devices are already exclusively claimed by some 3rd party device drivers
PsychHID-ERROR: or applications. I will now retry to only claim control of a hopefully safe subset of devices like standard
PsychHID-ERROR: keyboards, mice, gamepads and supported USB-DAQ devices and other vendor defined devices and hope this goes better...
PsychHID-INFO: That worked. A subset of regular mouse, keyboard etc. input devices and maybe some vendor defined devices will be available at least.
INTERNAL PSYCHTOOLBOX ERROR
    error:                PsychError_system
    general description:  Error reported by a system call
    specific description: Failed to create event queue for detecting key press.
    module name:          PsychHID
    subfunction call:     KbQueueCreate
    file name:            ./PsychSourceGL/Source/OSX/PsychHID/PsychHIDStandardInterfaces.c
    function name:        PsychHIDOSKbQueueCreate
    line number:          956
PsychHID:KbQueueCreate: See error message printed above.
1.0124     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
9.6499     WARNING     User requested fullscreen with size [1024  768], but screen is actually [1440, 900]. Using actual size
2022-06-02 12:47:58.561 python[19196:360312] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/lm/nsmhypy12mg2qfrzsk29k_640000gs/T/org.opensciencetools.psychopy.savedState
Traceback (most recent call last):
  File "/Users/tanlab/Documents/tryagainx3_lastrun.py", line 160, in <module>
    if endExpNow or defaultKeyboard.getKeys(keyList=["escape"]):
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/hardware/keyboard.py", line 221, in getKeys
    name = event.getKeys(keyList, modifiers=False, timeStamped=False)
NameError: name 'event' is not defined
##### Experiment ended. #####

When we try version 2022.1.4, this is the error we get:

########## Running: /Users/tanlab/Documents/tryingagainx4_lastrun.py ###########
743.4487     INFO     Loaded monitor calibration from ['2021_07_09 11:43']
2022-06-02 13:25:02.798 python[20045:378873] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/lm/nsmhypy12mg2qfrzsk29k_640000gs/T/org.opensciencetools.psychopy.savedState
Traceback (most recent call last):
1.7210     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
9.7739     WARNING     User requested fullscreen with size [1024  768], but screen is actually [1440, 900]. Using actual size
ioHub Server Process Completed With Code:  Negsignal.SIGSEGV
  File "/Users/tanlab/Documents/tryingagainx4_lastrun.py", line 89, in <module>
    ioServer = io.launchHubServer(window=win, **ioConfig)
  File "/Volumes/PsychoPy-2022.1.4 1/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/contrib/lazy_import.py", line 118, in __call__
    return obj(*args, **kwargs)
  File "/Volumes/PsychoPy-2022.1.4 1/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/iohub/client/connect.py", line 256, in launchHubServer
    return ioHubConnection(iohub_config)
  File "/Volumes/PsychoPy-2022.1.4 1/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/iohub/client/__init__.py", line 296, in __init__
    raise RuntimeError('Error starting ioHub server: {}'.format(self.iohub_status))
RuntimeError: Error starting ioHub server: ioHub startup failed.
################ Experiment ended with exit code 1 [pid:20045] #################

From the above post and the release notes for the most recent version here (https://github.com/psychopy/psychopy/releases), it sounds like the iohub error should be resolved, but that seems to remain an issue for us. Any guidance would be greatly appreciated!

**Comment by meetinthemiddle-be** [comment]
Using the ad-hoc build that was made to prevent #6898 that was present in 2024.2.2 (https://drive.google.com/file/d/1fkvUeYVqImahdfQyEZVjfjkC3-u5B_Xd/view) I get a similar issue when running a simple test experiment.


```
Generating PsychoPy script...

################# Running: /Users/<REDACTED>/psychopytest_lastrun.py #################
379.3702     INFO     Loaded monitor calibration from ['2024_10_05 14:45']
379.3780     INFO     Loaded monitor calibration from ['2024_10_05 14:45']
2024-10-11 22:06:43.196 python[5803:83616] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/42/rfpp54213jj8qklfmr0f64fm0000gn/T/org.opensciencetools.psychopy.savedState
8.8683     WARNING     launchHubServer: If using the iohub mouse or eyetracker devices, fullScr should be True.
Traceback (most recent call last):
ioHub Server Process Completed With Code:  Negsignal.SIGSEGV
  File "/Users/<REDACTED>/psychopytest_lastrun.py", line 685, in <module>
    setupDevices(expInfo=expInfo, thisExp=thisExp, win=win)
  File "/Users/<REDACTED>/psychopytest_lastrun.py", line 253, in setupDevices
    ioServer = io.launchHubServer(window=win, **ioConfig)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/contrib/lazy_import.py", line 118, in __call__
    return obj(*args, **kwargs)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/iohub/client/connect.py", line 260, in launchHubServer
    return ioHubConnection(iohub_config)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/iohub/client/__init__.py", line 297, in __init__
    raise RuntimeError('Error starting ioHub server: {}'.format(self.iohub_status))
RuntimeError: Error starting ioHub server: ioHub startup failed.
################# Experiment ended with exit code 1 [pid:5803] #################

```

**Comment by peircej** [comment]
Thanks @meetinthemiddle-be 
Good to know that the app crashing on start is fixed by this release then. iohub errors are super-annoying to debug (because they never give us much info about what went wrong) but we'll look into this. 

In the meantime the workaround is to switch to PTB as your input method. Assuming you aren't needing eyetracking this should get you up and running while we work out the iohub issue
