### ISSUE TITLE
moviestim2 python-vlc version

### ISSUE THREAD

**Issue by bpinsard** [psychopy/psychopy#4956]
Using MovieStim2 I get the following errors (caught by the callback handler), resulting in sound de-sync.
```
Traceback (most recent call last):
  File ".../.local/lib/python3.8/site-packages/vlc.py", line 1741, in _callback_handler
    call(event.contents, *args, **kwds)
  File ".../.local/lib/python3.8/site-packages/psychopy/visual/movie2.py", line 142, in _audioTimeCallback
    tm = -event.u.new_time/1000.0
AttributeError: 'Event' object has no attribute 'u'
``` 
Working backward on python-vlc versions, the bug appears with 3.0.12117 , the latest working version being 3.0.11115 . 

The commit that bumped the requirements version is here
https://github.com/psychopy/psychopy/commit/8692b9c6dfc8fc0a573b7bd5fe40f8815873023e 
But there are no mentions for which psychopy features this version is required. 

I don't know what changed in VLC or python-vlc that modified the structure of the events.

**Comment by peircej** [comment]
We were aware that needed limiting in Windows, but are you saying we should be applying that version restriction to other platforms?
In general, we've rather fallen out of love with the VLC engine for movies. What initially looked great for seemingly having higher performance has turned out to bring quite a few hassles. PsychoPy 2022.2 provides a new engine using FFpyPlayer and we think this is a big improvement in all directions on the vlc player

**Comment by bpinsard** [comment]
I don't know if the version should be limited in the other platform, maybe the first step would be reproducing the bug in another setup. (a colleague have the same problem with similar setup, was happening in docker/singularity with clean install too).

We started using MovieStim2 few years ago as it was the best option based on our tests at that time, and thus we kept it.
We acquired a bunch of data with it, are there any specific problems that we should be aware of regarding that player? 

So if I get it right, MovieStim is using FFpyPlayer ? It seems that the code is re-structured to have other backend players instead of duplicating classes.
I must say that the MovieStims duplication and the lack of documentation on each one pros/cons was definitely confusing and that restructuring is much welcomed.

I guess my issue is then maybe pertinent for similar cases with existing scripts using MovieStim2, and users updating psychopy and dependencies might encounter the same problem.
