### ISSUE TITLE
Psychopy Installation Issue (pip install + standalone) 

### ISSUE THREAD

**Issue by sadeabiodun** [psychopy/psychopy#5086]
i'm on a Mac 11.6 trying to install psychopy3 using pip install psychopy with python 3.8.13 inside a fresh conda environment (conda 4.12.0, pip 22.1.2) and I’m getting this error. (I also tried installing the most recent standalone package for Mac, but psychopy crashes immediately after displaying the splash window.) Any idea what might be going wrong?

```
pip install git+https://github.com/psychopy/psychopy.git

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zj/tlwtxx0j0qsgx8p8pkmnlgdr0000gq/T/pip-install-gs62ny_h/wxpython_721d30261ae2414eaef73e2cc689e0eb/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/private/var/folders/zj/tlwtxx0j0qsgx8p8pkmnlgdr0000gq/T/pip-install-gs62ny_h/wxpython_721d30261ae2414eaef73e2cc689e0eb/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

```

**Comment by tab-cmd** [comment]
I'm getting a similar error in my automated builds. The only difference I can tell between when it was passing and started giving me the error @sadeabiodun had was this line:

```Collecting wxPython!=4.0.2,!=4.0.3
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
```

previously it was downloading version 4.1.1.

See https://github.com/CAMBI-tech/BciPy/runs/7842180827?check_suite_focus=true for the full trace. It fails on macOS only python versions 3.7 and 3.8. 

This PR likely would fix: https://github.com/psychopy/psychopy/pull/5087/files
