### ISSUE TITLE
Internal error on launch, built from conda on windows

### ISSUE THREAD

**Issue by Mitchellb16** [psychopy/psychopy#5088]
Hello,
I get the following error in a popup when I open any recent project in builder. Version: 2022.1.4. I'm guessing this may have to do with building with conda (changed python version to 3.7 in yaml file)? 

Traceback (most recent call last):
  File "C:\Users\15093\anaconda3\envs\psychopy\lib\site-packages\psychopy\app\builder\builder.py", line 885, in OnFileHistory
    self.fileOpen(filename=path)
  File "C:\Users\15093\anaconda3\envs\psychopy\lib\site-packages\psychopy\app\builder\builder.py", line 735, in fileOpen
    self.project = pavlovia.getProject(filename)
  File "C:\Users\15093\anaconda3\envs\psychopy\lib\site-packages\psychopy\projects\pavlovia.py", line 1240, in getProject
    "gitpython and a git installation required for getProject()")
psychopy.exceptions.DependencyError: gitpython and a git installation required for getProject()

**Comment by mdtdev** [comment]
Any update on this? It looks like we need to switch to python 3.7...

I get this error:
```
Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\envs\psychopy\Scripts\psychopy-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\USER\miniconda3\envs\psychopy\lib\site-packages\psychopy\app\psychopyApp.py", line 100, in main
    start_app()
  File "C:\Users\USER\miniconda3\envs\psychopy\lib\site-packages\psychopy\app\psychopyApp.py", line 22, in start_app
    from psychopy.app._psychopyApp import PsychoPyApp
  File "C:\Users\USER\miniconda3\envs\psychopy\lib\site-packages\psychopy\app\_psychopyApp.py", line 55, in <module>
    from psychopy import projects
  File "C:\Users\USER\miniconda3\envs\psychopy\lib\site-packages\psychopy\projects\__init__.py", line 11, in <module>
    from . import pavlovia
  File "C:\Users\USER\miniconda3\envs\psychopy\lib\site-packages\psychopy\projects\pavlovia.py", line 30, in <module>
    import gitlab
  File "C:\Users\USER\miniconda3\envs\psychopy\lib\site-packages\gitlab\__init__.py", line 23, in <module>
    from gitlab import utils as _utils
  File "C:\Users\USER\miniconda3\envs\psychopy\lib\site-packages\gitlab\utils.py", line 9, in <module>
    from gitlab import types
  File "C:\Users\USER\miniconda3\envs\psychopy\lib\site-packages\gitlab\types.py", line 1, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
```
I followed the website instructions for `conda` and get the above from running `psychopy` on the command line.

Any ideas/advice welcome!

**Comment by mdtdev** [comment]
UPDATE: Manually updating the `psychopy-env.yml` to Python 3.7 does fix my error.

**Comment by TEParsons** [comment]
This happened when the standalone installer failed to install git, but PsychoPy Studio uses isomorphic git (which is pure JS and doesn't need a local git install) so I'll close this
