### ISSUE TITLE
initialising the experiment 

### ISSUE THREAD

**Issue by narae7058** [psychopy/psychopy#5292]
[initialising the experiment]
Only that screen appears continuously, and the pilot does not run. 
On my computer, the experiment runs completely and seems to be fine. 
The reason why it is not executed online seems to be because there is a problem in the process of converting to JavaScript. But I'm not used to using the code, so it's hard to solve the problem, so I need help.

PsychoPy encountered an unhandled internal error! Please send the report under "Details" to the developers with a description of what you were doing with the software when the error occurred.

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\exceptions.py", line 304, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\mixins.py", line 112, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\client.py", line 662, in http_get
    result = self.http_request(
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\client.py", line 628, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 Project Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\projects\pavlovia.py", line 663, in project
    self._project = self.session.gitlab.projects.get(self.id)
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\v4\objects\projects.py", line 782, in get
    return cast(Project, super().get(id=id, lazy=lazy, **kwargs))
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\exceptions.py", line 306, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 1380, in onPavloviaRun
    pavlovia_ui.syncProject(parent=self, project=self.project)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\pavlovia_ui\project.py", line 743, in syncProject
    if not project.localRoot or not Path(project.localRoot).is_dir():
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\projects\pavlovia.py", line 746, in localRoot
    if self.project.path_with_namespace in knownProjects:
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\projects\pavlovia.py", line 666, in project
    raise KeyError(f"Could not find GitLab project with id {self.id}.")
KeyError: 'Could not find GitLab project with id 271722.'

**Comment by TEParsons** [comment]
I think this is fixed in 2022.2.5, please do reopen if that's not the case though

**Comment by narae7058** [comment]
thank you for helping!! 

I think this problem is caused by using thisIndex. I'm using a PsychoPy Builder and the auto-translate on PsychoPy to generate the javascript of my custom python code.

I designated it as a dictionary of participants' values in the first block. When the same stimulus is presented in the next block, the above work is performed to give feedback if it is different from one previous value.
so

At block1
before experiment → ans_dic = {};
end routine → ans_dic[block1.thisIndex]=key_resp_5.keys
This is how it was constructed.

next
In block2, a feedback <code> was created and the code was entered.
begin experiment →duration=""
begin routine →
if ans_dic[block2.thisIndex]!=key_resp_6.keys:
duration = 0.2
elif ans_dic[block2.thisIndex]==key_resp_6.keys:
duration = 0

Then, redcross.png was entered in the image, and $duration was entered in the duration.

When running in this way, the experiment runs exactly on my computer.
However, it is expected to cause problems because it does not work properly online. How can you solve these problems?

Each participant can enter a different value, there is no set $AnsCorr value.
Is there a way to create and use the value entered by the participant online as a variable for the participant without using the above method?

https://gitlab.pavlovia.org/Narae/nssi
https://pavlovia.org/Narae/nssi
