### ISSUE TITLE
Launch Error MacOS

### ISSUE THREAD

**Issue by christinaferrero** [psychopy/psychopy#5325]
when opening psychopy on mac launch error occurs, this happened after a experiment was shared from a windows computer (with newer version of python and slightly older version of psychopy). we've tried uninstalling and installing psychopy multiple times, going through terminal to find possible sources of errors, and updating python on mac, but the same error keeps coming up.
[](url)
<img width="482" alt="Screen Shot 2023-01-27 at 4 19 25 PM" src="https://user-images.githubusercontent.com/123783757/215229227-3ea678cf-9d1e-4e76-8283-cf3389820424.png">

<img width="1170" alt="Screen Shot 2023-01-27 at 4 18 59 PM" src="https://user-images.githubusercontent.com/123783757/215229200-a27c62b0-1c1f-444c-aa24-548d95bbeb2f.png">

**Comment by jfkominsky** [comment]
I got this error when I installed 2023.1.0 on MacOS Catalina 10.15.7, I had to revert to 2022.2.5. I couldn't launch PsychoPy at all, nevermind open an experiment. Is there an issue with the standalone build for 2023's Mac version?

**Comment by iPsych** [comment]
@jfkominsky @christinaferrero I am experience in same error in High Sierra, but can open the same version in  MacOS Catalina 10.15.7.
It seems not the OS issue, but dependency issue. Possibly path setting...

0.1510 	DEBUG 	Opening message catalog /Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/localization/../app/locale/en_US/LC_MESSAGE/messages.mo for locale en_US
Traceback (most recent call last):
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/__boot__.py", line 258, in <module>
    _run()
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/__boot__.py", line 172, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/psychopyApp.py", line 102, in <module>
    main()
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/psychopyApp.py", line 98, in main
    start_app()
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/psychopyApp.py", line 26, in start_app
    app = startApp(showSplash=showSplash)
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/app/__init__.py", line 84, in startApp
    _psychopyApp = PsychoPyApp(
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/app/_psychopyApp.py", line 236, in __init__
    self.onInit(testMode=testMode, **kwargs)
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/app/_psychopyApp.py", line 453, in onInit
    from [psychopy.app](http://psychopy.app/) import coder, builder, runner, dialogs
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/app/builder/__init__.py", line 5, in <module>
    from .builder import BuilderFrame
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/app/builder/builder.py", line 125, in <module>
    class BuilderFrame(BaseAuiFrame, handlers.ThemeMixin):
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/app/builder/builder.py", line 128, in BuilderFrame
    routineTemplates = TemplateManager()
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/app/builder/builder.py", line 110, in __init__
    self.updateTemplates()
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/app/builder/builder.py", line 117, in updateTemplates
    thisExp = experiment.Experiment()
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/experiment/_experiment.py", line 137, in __init__
    _settingsComp = getComponents(fetchIcons=False)['SettingsComponent']
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/experiment/components/__init__.py", line 218, in getComponents
    module = import_module(explicit_rel_path, package=pkg)
  File "importlib/__init__.pyc", line 127, in import_module
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/experiment/components/microphone/__init__.py", line 15, in <module>
    from psychopy.sound.audiodevice import sampleRateQualityLevels
  File "/Applications/PsychoPy3_2023_1_3.app/Contents/Resources/lib/python3.8/psychopy/sound/__init__.py", line 135, in <module>
    raise DependencyError(
psychopy.exceptions.DependencyError: No sound libs could be loaded. Tried: ['sounddevice', 'PTB', 'pyo', 'pygame']
Check whether the necessary sound libs are installed
5.6356 	WARNING 	The 'psychtoolbox' library cannot be loaded but is required for audio capture (use `pip install psychtoolbox` to get it). Microphone recording will be unavailable this session. Note that opening a microphone stream will raise an error.
6.2546 	ERROR 	Support for the `sounddevice` audio backend is not available this session. Please install `psychopy-sounddevice` and restart the session to enable support.
6.2647 	ERROR 	Support for the `pyo` audio backend is not available this session. Please install `psychopy-pyo` and restart the session to enable support.

**Comment by TEParsons** [comment]
This looks like a problem when trying to import the Microphone Component, as it's getting some values from `psychopy.sound` and then failing to import that module... Those values exist in safer to import modules so I've put in a PR to switch to those for the next version. 

In the meantime, I think the `psychopy.sound` module should load if you either:
- Find your preferences file (should be in Documents/.psychopy3) and remove `sounddevice` and `pyo` from the sound backend preference
OR
- Install `psychopy-sounddevice` and `psychopy-pyo` via the terminal

**Comment by peircej** [comment]
Yes, ultimately I think the issue here is that the user has a sound preference (`sounddevice`) that isn't present because it's now a plugin and the user hasn't installed that plugin

I think in 2023.2.0 this has been addressed in several ways:
1. if an unavailable sound option is requested, then the sound module should now load (and run studies) simply falling back to PTB for sound
2. if any errors are encountered while trying to load an experiment (when the app is launched) then we provide a warning but open a window without loading the experiment
3. for the specific issue above we should be able to load the experiment without loading the sound lib (although that would still error when the experiment was launched if it weren't for solution (1))
