### ISSUE TITLE
pip install does not have `attrdict` in requirements

### ISSUE THREAD

**Issue by rphlypo** [psychopy/psychopy#5362]
When doing a clean install in a new conda environment as such
```bash
conda create -n psychopy python=3.8
conda activate psychopy
pip install psychopy
```
an error pops up with regards to attrdict :
```bash
 error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9afjlm18/wxpython_5c3dfd866bae4413a6f34b8ec0a0285b/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-9afjlm18/wxpython_5c3dfd866bae4413a6f34b8ec0a0285b/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

performing
```bash
conda install attrdict
```
seems to resolve the issue, pointing that this may be missing from the requirement file.

**Comment by lkeegan** [comment]
This is a dependency missing from wxPython: https://github.com/wxWidgets/Phoenix/issues/2225

**Comment by TEParsons** [comment]
Closing as wxPython is no longer a dependency
