### ISSUE TITLE
Errors with display and slider when packaging with pyinstaller

### ISSUE THREAD

**Issue by ratbasketball** [psychopy/psychopy#5485]
I'm trying to distribute my code by packaging it with pyinstaller.  I cannot get it to work!  There's some problem with the psychopy modules / libraries.  The code works just fine before trying to compile it. I could post my full code if needed.  I don't see how it could be but I could.  Here's the output I get:

```
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Warning: display device module could not be imported.
Traceback (most recent call last):
  File "psychopy\iohub\devices\__init__.py", line 956, in <module>
  File "psychopy\iohub\devices\__init__.py", line 933, in import_device
AttributeError: module 'psychopy.iohub.devices.display' has no attribute 'Display'
Traceback (most recent call last):
  File "Main.py", line 201, in <module>
  File "psychopy\contrib\lazy_import.py", line 117, in __call__
  File "psychopy\contrib\lazy_import.py", line 86, in _resolve
  File "psychopy\contrib\lazy_import.py", line 201, in _import
  File "C:\Users\micha\Desktop\installertests\dist\main\psychopy\visual\slider\__init__.py", line 50, in <module>
    class SliderComponent(BaseVisualComponent):
TypeError: module() takes at most 2 arguments (3 given)
[15456] Failed to execute script 'Main' due to unhandled exception!
1.3235  WARNING         We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
6.6846  WARNING         User requested fullscreen with size [1920 1080], but screen is actually [1440, 900]. Using actual size

C:\Users\micha\Desktop\installertests\dist\main>
```

**Comment by peircej** [comment]
I'm afraid we don't provide support for packaging using pyinstaller (we don't use pyinstaller ourselves, and packaging up large set of dependencies is too hard to provide support on). Most likely the issue is to do with a missing required package, but I'm afraid that's as far as I know to help. Sorry
