### ISSUE TITLE
TextBox2 can't load local fonts on win11 in v2022.2.5

### ISSUE THREAD

**Issue by waa4968128** [psychopy/psychopy#5559]
The local fonts can be loaded in TextStim, but fails in TestBox2.
**In particular, the follow codes of  TextStim is ok.**

```
fontpath_aribli = 'C:\\Windows\\Fonts\\ariali.ttf'

endbutton = visual.TextStim(win=win, name='endbutton',
    text='Click here to continue.',s
    font = fontpath_aribli,
    pos=(0, -0.3), height=0.05, wrapWidth=None, ori=0.0, 
    color='white', colorSpace='rgb', opacity=None, 
    languageStyle='LTR',
    depth=-1.0);
```

**But the follow codes of TextBox2 go wrong. It needs to note that these codes run well with "font = ''Arial''".**

```
fontpath_aribli = 'C:\\Windows\\Fonts\\ariali.ttf'

textbox = visual.TextBox2(
     win, text='Type a response.', 
     font = fontpath_aribli,
     # font = 'Arial'
     pos=(0, 0.),     letterHeight=0.05,
     size=(None, None), borderWidth=2.0,
     color='white', colorSpace='rgb',
     opacity=None,
     bold=False, italic=False,
     lineSpacing=1.0,
     padding=0.0, alignment='center',
     anchor='center',
     fillColor=None, borderColor=None,
     flipHoriz=False, flipVert=False, languageStyle='LTR',
     editable=True,
     name='textbox',
     autoLog=True,
)

```
**The error outputs are as follow.**

```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Psychopy test\untitled_lastrun_error_test.py", line 161, in <module>
    textbox = visual.TextBox2(
  File "C:\Software\Psychopy\lib\site-packages\psychopy\visual\textbox2\textbox2.py", line 169, in __init__
    self.font = font
  File "C:\Software\Psychopy\lib\site-packages\psychopy\tools\attributetools.py", line 27, in __set__
    newValue = self.func(obj, value)
  File "C:\Software\Psychopy\lib\site-packages\psychopy\visual\textbox2\textbox2.py", line 341, in font
    self.glFont = allFonts.getFont(
  File "C:\Software\Psychopy\lib\site-packages\psychopy\visual\textbox2\fontmanager.py", line 940, in getFont
    self.addGoogleFont(name)
  File "C:\Software\Psychopy\lib\site-packages\psychopy\visual\textbox2\fontmanager.py", line 834, in addGoogleFont
    repoResp = requests.get(repoURL)
  File "C:\Software\Psychopy\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Software\Psychopy\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Software\Psychopy\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Software\Psychopy\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Software\Psychopy\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='fonts.googleapis.com', port=443): Max retries exceeded with url: /css2?family=C:%5CWindows%5CFonts%5Cariali.ttf&display=swap (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
```

**Comment by tab-cmd** [comment]
👍🏼 I'm also getting this error for installed custom fonts

**Comment by peircej** [comment]
I don't think TextBox2 was ever taught how to load arbitrary files, but I'm sure we can do that. @TEParsons could you add code to check if the `font` arg looks like a filepath before looking for it on google fonts?

The interim solution would be to install the file to your system and then refer to it by name rather than the ttf file. In your case it looks like you're just trying to use arial italic, so I think you can do 
```
textbox = visual.TextBox2(
     win, text='Type a response.',
     font = 'Arial'
     bold=False, italic=True)
```

or does that not work?

**Comment by waa4968128** [comment]
It works after installing the font on the system and utilizing its direct name instead of the file path, thanks.

**Comment by peircej** [comment]
Also fixed for using paths in https://github.com/psychopy/psychopy/pull/5585
