### ISSUE TITLE
launchScan test not working

### ISSUE THREAD

**Issue by saraponti** [psychopy/psychopy#5647]
Hi!
I am new to psychopy and I was trying to simulate my stimulation script with launchScan and 'Test' option but I get a thread error. 
I am using psychopy 2023.1.3 installed with pip and python3.8 in windows 11. I also tried to create a new conda environment and the standalone version but the result is the same. It would be great if you have any suggestions.
Thank you,
Sara

Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\sarap\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\sarap\anaconda3\lib\site-packages\psychopy_mri_emulator\emulator.py", line 133, in run
    core.wait(self.timesleep - self.hogCPU, hogCPUperiod=0)
  File "C:\Users\sarap\anaconda3\lib\site-packages\psychopy\clock.py", line 445, in wait
    _dispatchWindowEvents()
  File "C:\Users\sarap\anaconda3\lib\site-packages\psychopy\clock.py", line 381, in _dispatchWindowEvents
    win.winHandle.dispatch_events()  # pump events
  File "C:\Users\sarap\anaconda3\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in dispatch_events
    app.platform_event_loop.start()
  File "C:\Users\sarap\anaconda3\lib\site-packages\pyglet\app\win32.py", line 92, in start
    raise RuntimeError('EventLoop.run() must be called from the same ' +
RuntimeError: EventLoop.run() must be called from the same thread that imports pyglet.app

**Comment by TEParsons** [comment]
Are you calling launchScan from a secondary thread? As that function includes some `psychopy.visual` calls, it has to run in the main thread of a process to work - as pyglet needs to run in the same thread as it was imported, and pyglet is a requirement of `psychopy.visual`

**Comment by peircej** [comment]
Or possibly launchScan no longer works. It was contributed some years ago by @jeremygray who I think no longer uses PsychoPy and I'm afraid I've never personally used it
