### ISSUE TITLE
[Bug]: SSL error when logging in to pavlovia from PsychoPy

### ISSUE THREAD

**Issue by SolitaryJune** [psychopy/psychopy#5981]
### PsychoPy Version

2023.2.3

### What OS are your PsychoPy running on?

Windows 10

### Bug Description

An error occurred while logging in
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Program Files\PsychoPy\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Program Files\PsychoPy\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Program Files\PsychoPy\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Program Files\PsychoPy\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Program Files\PsychoPy\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Program Files\PsychoPy\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\PsychoPy\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files\PsychoPy\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Program Files\PsychoPy\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Program Files\PsychoPy\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gitlab.pavlovia.org', port=443): Max retries exceeded with url: /api/v4/user (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\pavlovia_ui\_base.py", line 128, in checkForLoginURL
    pavlovia.login(self.tokenInfo['token'])
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\projects\pavlovia.py", line 110, in login
    currentSession.setToken(token)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\projects\pavlovia.py", line 399, in setToken
    self.startSession(token)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\projects\pavlovia.py", line 425, in startSession
    self.gitlab.auth()
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\client.py", line 257, in auth
    self.user = self._objects.CurrentUserManager(self).get()
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\exceptions.py", line 304, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\mixins.py", line 146, in get
    server_data = self.gitlab.http_get(self.path, **kwargs)
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\client.py", line 662, in http_get
    result = self.http_request(
  File "C:\Program Files\PsychoPy\lib\site-packages\gitlab\client.py", line 594, in http_request
    result = self.session.send(prepped, timeout=timeout, **settings)
  File "C:\Program Files\PsychoPy\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\PsychoPy\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='gitlab.pavlovia.org', port=443): Max retries exceeded with url: /api/v4/user (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

### Expected Behaviour

An error occurred while logging in

### Steps to Reproduce

1. logging 
2.success
3.An error occurred while logging in
...

**Comment by peircej** [comment]
We've seen this from a small minority of users, usually at US government institutions or similar. Is that the case for you too? We are actively exploring solutions by using different methods to connect with pavlovia, but I'm not sure what those solutions will be yet

**Comment by peircej** [comment]
OK, we've tracked down 2 issues:
1. some users need to adapt the certificates file that comes with Python to include their own institutional web certificate
2. some users need to use a web proxy

At the moment (1) requires a change to the `cacert.pem` file that is packaged with PsychoPy (or with Python certifi if you use your own installation). That obviously needs doing each time you install PsychoPy and needs admin privs to change, so we'll work on adding something to the PsychoPy preferences so that it can be done just once per user and not requiring admin rights

For (2) the psychopy preference setting already exists (to add your institution proxy server address, in the Connections tab) but we hadn't previously been using that in the connection to gitlab and that [is now resolved](https://github.com/psychopy/psychopy/pull/6236) to be released in the 2024.1.0 release

**Comment by abraver** [comment]
@peircej I'm having this same issue, but both at my university and at home.

Can you share the changes needed to cacert.pem so I can try to troubleshoot on my end?

Thanks.

(For added context, this pops up when I try to "pilot in browser")

Full error below:

```
Traceback (most recent call last):
  File “urllib3/connectionpool.pyc”, line 464, in _make_request
  File “urllib3/connectionpool.pyc”, line 1093, in _validate_conn
  File “urllib3/connection.pyc”, line 741, in connect
  File “urllib3/connection.pyc”, line 920, in _ssl_wrap_socket_and_match_hostname
  File “urllib3/util/ssl_.pyc”, line 460, in ssl_wrap_socket
  File “urllib3/util/ssl_.pyc”, line 504, in _ssl_wrap_socket_impl
  File “ssl.pyc”, line 513, in wrap_socket
  File “ssl.pyc”, line 1071, in _create
  File “ssl.pyc”, line 1342, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File “urllib3/connectionpool.pyc”, line 787, in urlopen
  File “urllib3/connectionpool.pyc”, line 488, in _make_request
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/requests/adapters.py”, line 667, in send
  File “urllib3/connectionpool.pyc”, line 841, in urlopen
  File “urllib3/util/retry.pyc”, line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=‘lib.pavlovia.org’, port=443): Max retries exceeded with url: /psychojs-2025.1.0.css (Caused by SSLError(SSLCertVerificationError(1, ‘[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)’)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/psychopy/app/builder/builder.py”, line 1646, in onPavloviaDebug
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/psychopy/app/runner/runner.py”, line 694, in runOnlineDebug
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/psychopy/app/runner/runner.py”, line 707, in startServer
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/psychopy/app/runner/runner.py”, line 762, in getPsychoJS
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/requests/api.py”, line 73, in get
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/requests/api.py”, line 59, in request
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/requests/sessions.py”, line 589, in request
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/requests/sessions.py”, line 703, in send
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/requests/adapters.py”, line 698, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host=‘lib.pavlovia.org’, port=443): Max retries exceeded with url: /psychojs-2025.1.0.css (Caused by SSLError(SSLCertVerificationError(1, ‘[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)’)))
```
