### ISSUE TITLE
[Bug]: app fails to launch on a server

### ISSUE THREAD

**Issue by SolitaryJune** [psychopy/psychopy#6086]
### PsychoPy Version

2023.2.3

### What OS are your PsychoPy running on?

Windows 10

### Bug Description

My processor is N5105. When I started the software after installing it, the loading interface was displayed and then disappeared, without starting the relevant IDE.

### Expected Behaviour

The IDE should open instead oThe GUI interface of the IDE should be opened instead of disappearing inexplicably or not starting.f disappearing inexplicably

### Steps to Reproduce

1.Installation
2. Start
3. Display the loading interface
4. There is no startup and the loading interface disappears.

**Comment by peircej** [comment]
We need more info about the crash. Could you open a windows explorer and go to the location `%APPDATA%/psychopy3`. In there you'll find a file called `lastAppLoad.log`. Could you upload the contents of that file please so we can see a crash report?

**Comment by 1302557841** [comment]
0.4230 	DEBUG 	Opening message catalog C:\Program Files\PsychoPy\lib\site-packages\psychopy\localization\..\app\locale\zh_CN\LC_MESSAGE\messages.mo for locale zh_CN
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
PTB-INFO: Using modified PortAudio V19.7.0-devel, revision unknown
Error in function GetDevices: 	Usage error
PTB-ERROR: PortAudio can't detect any supported sound device on this system.
PsychPortAudio:GetDevices: Usage:

devices = PsychPortAudio('GetDevices' [, devicetype] [, deviceIndex]);
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\Lib\site-packages\psychopy\app\psychopyApp.py", line 103, in <module>
    main()
  File "C:\Program Files\PsychoPy\Lib\site-packages\psychopy\app\psychopyApp.py", line 99, in main
    start_app()
  File "C:\Program Files\PsychoPy\Lib\site-packages\psychopy\app\psychopyApp.py", line 27, in start_app
    _ = startApp(showSplash=showSplash)  # main loop
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\__init__.py", line 84, in startApp
    _psychopyApp = PsychoPyApp(
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\_psychopyApp.py", line 236, in __init__
    self.onInit(testMode=testMode, **kwargs)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\_psychopyApp.py", line 453, in onInit
    from psychopy.app import coder, builder, runner, dialogs
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\__init__.py", line 5, in <module>
    from .builder import BuilderFrame
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 125, in <module>
    class BuilderFrame(BaseAuiFrame, handlers.ThemeMixin):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 128, in BuilderFrame
    routineTemplates = TemplateManager()
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 110, in __init__
    self.updateTemplates()
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 117, in updateTemplates
    thisExp = experiment.Experiment()
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\experiment\_experiment.py", line 150, in __init__
    _settingsComp = getComponents(fetchIcons=False)['SettingsComponent']
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\experiment\components\__init__.py", line 218, in getComponents
    module = import_module(explicit_rel_path, package=pkg)
  File "C:\Program Files\PsychoPy\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\experiment\components\camera\__init__.py", line 25, in <module>
    micDevices = syst.getAudioCaptureDevices()
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\tools\systemtools.py", line 211, in getAudioCaptureDevices
    allDevices = getAudioDevices()  # gat all devices
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\tools\systemtools.py", line 164, in getAudioDevices
    allDevs = audio.get_devices(device_type=13)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychtoolbox\audio.py", line 70, in get_devices
    return PsychPortAudio('GetDevices', device_type, device_index);
Exception: PTB-ERROR: PortAudio can't detect any supported sound device on this system.
8.1225 	WARNING 	Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
8.3440 	WARNING 	Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
10.0245 	WARNING 	Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
10.2131 	WARNING 	Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
11.3455 	DEBUG 	Looking for Tobii device configuration file...
11.3470 	DEBUG 	No Tobii device configuration file found.
11.3471 	DEBUG 	Looking for SR Research EyeLink device configuration file...
11.3481 	DEBUG 	No SR Research EyeLink device configuration file found.
11.3482 	DEBUG 	Looking for Gazepoint device configuration file...
11.3492 	DEBUG 	No Gazepoint device configuration file found.
11.3493 	DEBUG 	Looking for PupilLabs device configuration file...
11.3509 	DEBUG 	No PupilLabs device configuration file found.
13.0111 	WARNING 	Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
13.1652 	WARNING 	Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
14.7102 	INFO 	Trying to load audio library: PTB
14.8359 	INFO 	Loaded psychtoolbox audio version 3.0.18.606399524
14.8363 	INFO 	sound is using audioLib: ptb

**Comment by SolitaryJune** [comment]
> We need more info about the crash. Could you open a windows explorer and go to the location `%APPDATA%/psychopy3`. In there you'll find a file called `lastAppLoad.log`. Could you upload the contents of that file please so we can see a crash report?

0.4230 DEBUG Opening message catalog C:\Program Files\PsychoPy\lib\site-packages\psychopy\localization..\app\locale\zh_CN\LC_MESSAGE\messages.mo for locale zh_CN
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
PTB-INFO: Using modified PortAudio V19.7.0-devel, revision unknown
Error in function GetDevices: Usage error
PTB-ERROR: PortAudio can't detect any supported sound device on this system.
PsychPortAudio:GetDevices: Usage:

devices = PsychPortAudio('GetDevices' [, devicetype] [, deviceIndex]);
Traceback (most recent call last):
File "C:\Program Files\PsychoPy\Lib\site-packages\psychopy\app\psychopyApp.py", line 103, in
main()
File "C:\Program Files\PsychoPy\Lib\site-packages\psychopy\app\psychopyApp.py", line 99, in main
start_app()
File "C:\Program Files\PsychoPy\Lib\site-packages\psychopy\app\psychopyApp.py", line 27, in start_app
_ = startApp(showSplash=showSplash) # main loop
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app_init_.py", line 84, in startApp
psychopyApp = PsychoPyApp(
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app_psychopyApp.py", line 236, in init
self.onInit(testMode=testMode, **kwargs)
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app_psychopyApp.py", line 453, in onInit
from psychopy.app import coder, builder, runner, dialogs
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder_init.py", line 5, in
from .builder import BuilderFrame
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 125, in
class BuilderFrame(BaseAuiFrame, handlers.ThemeMixin):
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 128, in BuilderFrame
routineTemplates = TemplateManager()
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 110, in init
self.updateTemplates()
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 117, in updateTemplates
thisExp = experiment.Experiment()
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\experiment_experiment.py", line 150, in init
settingsComp = getComponents(fetchIcons=False)['SettingsComponent']
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\experiment\components_init.py", line 218, in getComponents
module = import_module(explicit_rel_path, package=pkg)
File "C:\Program Files\PsychoPy\lib\importlib_init_.py", line 127, in import_module
return _bootstrap.gcd_import(name[level:], package, level)
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\experiment\components\camera_init.py", line 25, in
micDevices = syst.getAudioCaptureDevices()
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\tools\systemtools.py", line 211, in getAudioCaptureDevices
allDevices = getAudioDevices() # gat all devices
File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\tools\systemtools.py", line 164, in getAudioDevices
allDevs = audio.get_devices(device_type=13)
File "C:\Program Files\PsychoPy\lib\site-packages\psychtoolbox\audio.py", line 70, in get_devices
return PsychPortAudio('GetDevices', device_type, device_index);
Exception: PTB-ERROR: PortAudio can't detect any supported sound device on this system.
8.1225 WARNING Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
8.3440 WARNING Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
10.0245 WARNING Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
10.2131 WARNING Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
11.3455 DEBUG Looking for Tobii device configuration file...
11.3470 DEBUG No Tobii device configuration file found.
11.3471 DEBUG Looking for SR Research EyeLink device configuration file...
11.3481 DEBUG No SR Research EyeLink device configuration file found.
11.3482 DEBUG Looking for Gazepoint device configuration file...
11.3492 DEBUG No Gazepoint device configuration file found.
11.3493 DEBUG Looking for PupilLabs device configuration file...
11.3509 DEBUG No PupilLabs device configuration file found.
13.0111 WARNING Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
13.1652 WARNING Font Manager failed to load file C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts\小米兰亭Pro 中粗.ttf
14.7102 INFO Trying to load audio library: PTB
14.8359 INFO Loaded psychtoolbox audio version 3.0.18.606399524
14.8363 INFO sound is using audioLib: ptb

**Comment by peircej** [comment]
OK thanks. I don't think this is anything to do with processor N5105. From the error it looks like you don't have any microphone connected that's causing PsychoPy to fall over (most computers have at least one mic these days). We'l certainly look into why caused it to crash but in the meantime you might be able just to add a mic?

**Comment by SolitaryJune** [comment]
> OK thanks. I don't think this is anything to do with processor N5105. From the error it looks like you don't have any microphone connected that's causing PsychoPy to fall over (most computers have at least one mic these days). We'l certainly look into why caused it to crash but in the meantime you might be able just to add a mic?

Sorry, this is a sever without a microphone. I want psychopy to run the local web version.

**Comment by peircej** [comment]
The local web version? I'm not sure what you mean. PsychoPy doesn't run as a server. It's a desktop application. If you want to run experiments online then you need to use PsychoJS instead (PsychoPy can output a javascript script) but running psychopy on a server is not something we support

**Comment by SolitaryJune** [comment]
> The local web version? I'm not sure what you mean. PsychoPy doesn't run as a server. It's a desktop application. If you want to run experiments online then you need to use PsychoJS instead (PsychoPy can output a javascript script) but running psychopy on a server is not something we support

I want to run studies in PsychoJS on my local browser, not through pavlovia.org. Use NAT to run PsychoJS experiments on other computers.

**Comment by peircej** [comment]
Yes, installing PsychoPy on the server is not a part of getting that to work. PsychoPy in not installed on Pavlovia anywhere. The scripts that are generated by PsychoPy are uploaded there but they don't use PsychoPy to run -by that point they are fully independent of the app

**Comment by SolitaryJune** [comment]
> Yes, installing PsychoPy on the server is not a part of getting that to work. PsychoPy in not installed on Pavlovia anywhere. The scripts that are generated by PsychoPy are uploaded there but they don't use PsychoPy to run -by that point they are fully independent of the app

Please tell me what should I do if I want to run my experiment on my server, thank you
