### ISSUE TITLE
Crashes when System in Russian on Ubuntu 14.04 

### ISSUE THREAD

**Issue by JRMeyer** [psychopy/psychopy#645]
I have a script that works fine when I have Ubuntu in English, but I tried to run the same script after the system langauge had been set to Russian, and it crashes. I changed the langauge back to English, and it works again. I thought it might have been the language, since I recently changed it. 

Here is the complete Error Message:

Welcome to PsychoPy2!
v1.79.01

##### Running: /home/josh/Google Drive/2013_2014_Study/EXPERIMENT/SeqRec_master/from_WAVs_to_experiment.py #####
Unexpected error loading library libopenal.so: libopenal.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога    <---- my translation --->   "not able to open the shared object file: The file or folder doesn't exist"
Traceback (most recent call last):
  File "/home/josh/Google Drive/BeverLab/2013_2014_Study/EXPERIMENT/SeqRec_master/from_WAVs_to_experiment.py", line 369, in <module>
    win = visual.Window(displayRes, fullscr=False, units="pix", allowGUI=True,winType="pyglet")                                      # create the display window for the experiment (an object called 'win') with all the info it needs
  File "/usr/lib/pymodules/python2.7/psychopy/visual/window.py", line 330, in __init__
    self._monitorFrameRate = self.getActualFrameRate()
  File "/usr/lib/pymodules/python2.7/psychopy/visual/window.py", line 1435, in getActualFrameRate
    self.flip()
  File "/usr/lib/pymodules/python2.7/psychopy/visual/window.py", line 502, in flip
    pyglet.media.dispatch_events()  # for sounds to be processed
  File "/usr/lib/pymodules/python2.7/pyglet/__init__.py", line 306, in __getattr__
    __import__(import_name)
  File "/usr/lib/pymodules/python2.7/pyglet/media/__init__.py", line 1338, in <module>
    __import__(driver_name)
  File "/usr/lib/pymodules/python2.7/pyglet/media/drivers/openal/__init__.py", line 42, in <module>
    from pyglet.media.drivers.openal import lib_openal as al
  File "/usr/lib/pymodules/python2.7/pyglet/media/drivers/openal/lib_openal.py", line 57, in <module>
    framework='/System/Library/Frameworks/OpenAL.framework')
  File "/usr/lib/pymodules/python2.7/psychopy/visual/_pygletLibOverload.py", line 113, in load_library
    lib = ctypes.cdll.LoadLibrary(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopenal.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога    <---- my translation --->   "not able to open the shared object file: The file or folder doesn't exist"
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/pymodules/python2.7/psychopy/visual/textbox/font_manager.py", line 29, in my_close_open_files
    for fileh in open_files.keys():
AttributeError: '_FileRegistry' object has no attribute 'keys'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/pymodules/python2.7/psychopy/visual/textbox/font_manager.py", line 29, in my_close_open_files
    for fileh in open_files.keys():
AttributeError: '_FileRegistry' object has no attribute 'keys'
0.4702 	WARNING 	Creating new monitor...
0.4704 	WARNING 	Creating new monitor...

**Comment by hoechenberger** [comment]
@bnicenboim, does this problem still exist for you?

**Comment by bnicenboim** [comment]
sorry, I haven't used psychopy in a long while...

**Comment by hoechenberger** [comment]
Closing for now, please feel free to re-open if the problem occurs again!
