### ISSUE TITLE
[Bug]: Compatibility with numpy 2.0

### ISSUE THREAD

**Issue by mscheltienne** [psychopy/psychopy#6573]
### PsychoPy Version

main

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

`import psychopy` is now failing with `numpy` 2.0, released yesterday.

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/scheltie/git/mscheltienne/psychopy/.venv/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/IPython/__init__.py", line 130, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 317, in start
    self.shell.mainloop()
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 917, in mainloop
    self.interact()
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 910, in interact
    self.run_cell(code, store_history=True)
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/scheltie/git/mscheltienne/psychopy/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-126954d4b6e7>", line 1, in <module>
    import psychopy
  File "/home/scheltie/git/mscheltienne/psychopy/psychopy/__init__.py", line 61, in <module>
    from psychopy.tools.versionchooser import useVersion, ensureMinimal
  File "/home/scheltie/git/mscheltienne/psychopy/psychopy/tools/versionchooser.py", line 19, in <module>
    from psychopy import logging, tools, web, constants, preferences, __version__
  File "/home/scheltie/git/mscheltienne/psychopy/psychopy/logging.py", line 43, in <module>
    from psychopy import clock
  File "/home/scheltie/git/mscheltienne/psychopy/psychopy/clock.py", line 298, in <module>
    monotonicClock = MonotonicClock()
  File "/home/scheltie/git/mscheltienne/psychopy/psychopy/clock.py", line 242, in __init__
    self._timeAtLastReset = getTime()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: _ARRAY_API not found
``` 

Note that the traceback is not very informative.. the `getTime()` call should not be the one raising. `psychtoolbox.GetSecs` which is assigned to `getTime` works corrently.

**Comment by mscheltienne** [comment]
It would be nice to also have a fix in the long run to ensure compatibility with future version. Maybe let's keep the issue open until a long term fix is added?

**Comment by peircej** [comment]
@mscheltienne I guess so. I think the actual fix is in a dependency (maybe psychtoolbox) as psychopy itself doesn't do anything low-level to cause a numpy-based seg fault! That is, I think this is coming from something with a C interface whereas psychopy is pure-python

**Comment by mscheltienne** [comment]
I agree that is likely comes from a dependency, it would be good to identify it.
`psychtoolbox` seems to work, on an environment setup to fail as above, `ptb.GetSecs` was working.

**Comment by peircej** [comment]
Well, when the test suite crashed, caused by numpy==2.0 the _apparent_ error was to do with 
`psychtoolbox.get_version_info`

```
Fatal Python error: Segmentation fault

Current thread 0x0000000114702e00 (most recent call first):
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/psychtoolbox/audio.py", line 48 in get_version_info
  File "/Users/runner/work/psychopy/psychopy/psychopy/sound/backend_ptb.py", line 64 in <module>
  File "<frozen importlib._bootstrap>", line [24](https://github.com/psychopy/psychopy/actions/runs/9553842948/job/26333599329#step:11:25)1 in _call_with_frames_removed
```
https://github.com/psychopy/psychopy/actions/runs/9553842948/job/26333599329
