### ISSUE TITLE
[Bug]: Crash on (french) Windows when attempting to use LSL

### ISSUE THREAD

**Issue by brifsttar** [psychopy/psychopy#6715]
### PsychoPy Version

2024.1.5

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

When creating an LSL `StreamOutlet`, the application can crash on (french) Windows release due to encoding error. This can be reproduced by just using this [sample code](https://github.com/kaczmarj/psychopy-lsl?tab=readme-ov-file#in-your-psychopy-code), however it requires both a french Windows install AND a specific network configuration (more on that later).

Below is the error that can be found in the log, 

```
Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\jobs.py", line 129, in run
    for pipeBytes in iter(self._fdpipe.readline, b''):
  File "C:\Program Files\PsychoPy\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
2024-07-15 15:31:30.014 (   0.009s) [        F224FCF7]      netinterfaces.cpp:36    INFO| netif '{43D91237-3541-4CD1-960C-32759030DDA7}' (status: 2, multicast: 1
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte
```

This is caused by the process assuming that the output will be in `utf-8`, when it's `Windows-1252` on french Windows install.

I was able to fix the issue by replacing `utf-8` by `Windows-1252` in lines 262 and 281 of `app/jobs.py`, as seen below.

https://github.com/psychopy/psychopy/blob/9e11b63ab2481a7e5b3821f12a24574fa2e45a3e/psychopy/app/jobs.py#L262-L282

Obviously, this is a workaround and not a fix, and a more elegant solution could be designed to handle encoding variants. As I'm really unfamiliar with the PsychoPy ecosystem, I don't feel I know enough to submit a PR to fix this, but I can confirm the workaround works. It's very possible only one of the change is enough, but I didn't check that.

To be complete, below is the log produced once the workaround is implemented

```
2024-07-15 14:27:35.179 (   0.005s) [        3C3F2C66]      netinterfaces.cpp:36    INFO| netif '{680A4B90-FB6F-4C8C-BCAA-5D05BA8CF0BC}' (status: 2, multicast: 1
2024-07-15 14:27:35.179 (   0.005s) [        3C3F2C66]      netinterfaces.cpp:36    INFO| netif '{55C0BE1D-27C5-4653-AA90-102E3F537089}' (status: 1, multicast: 1
2024-07-15 14:27:35.179 (   0.005s) [        3C3F2C66]      netinterfaces.cpp:58    INFO| 	IPv6 ifindex 10
2024-07-15 14:27:35.179 (   0.005s) [        3C3F2C66]      netinterfaces.cpp:36    INFO| netif '{13B1D267-E32F-11EC-B273-806E6F6E6963}' (status: 1, multicast: 1
2024-07-15 14:27:35.180 (   0.005s) [        3C3F2C66]      netinterfaces.cpp:58    INFO| 	IPv6 ifindex 1
2024-07-15 14:27:35.180 (   0.005s) [        3C3F2C66]         api_config.cpp:270   INFO| Loaded default config
2024-07-15 14:27:35.180 (   0.006s) [        3C3F2C66]             common.cpp:65    INFO| git:6ca188c266c21f7228dc67077303fa6abaf2e8be/branch:refs/tags/v1.16.2/build:Release/compiler:MSVC-19.0.24245.0/link:SHARED
2024-07-15 14:27:35.182 (   0.008s) [        3C3F2C66]         udp_server.cpp:82    WARN| Could not bind multicast responder for ff02:113d:6fdd:2c17:a643:ffe2:1bd1:3cd2 to interface ::1 (Un argument non valide a été fourni.)
2024-07-15 14:27:35.183 (   0.009s) [        3C3F2C66]         udp_server.cpp:82    WARN| Could not bind multicast responder for ff05:113d:6fdd:2c17:a643:ffe2:1bd1:3cd2 to interface ::1 (Un argument non valide a été fourni.)
```

We can see the culprit on the last two lines, at the end of the multicast warning: `Un argument non valide a été fourni`. `0xe9` is `é` in `Windows-1252`, so this is what is causing the decoding error.

I'm not sure what in the network configuration could produce that warning, but without this warning, the application doesn't crash (tested on another french Windows install).

### Expected Behaviour

The correct behaviour would be for the LSL outlet to be initialized, and the application not crashing.

### Steps to Reproduce

1. Get a french Windows install
2. Somehow mess around with the network settings so that multicast responder can't be bound
3. Create a new PsychoPy projet
4. Add a new code section to be executed at the beginning of the experiment, with the following code ([source](https://github.com/kaczmarj/psychopy-lsl?tab=readme-ov-file#in-your-psychopy-code))
```
# ...
from pylsl import StreamInfo, StreamOutlet
info = StreamInfo(name='my_stream_name', type='Markers', channel_count=1,
                  channel_format='int32', source_id='uniqueid12345')
# Initialize the stream.
outlet = StreamOutlet(info)
# ...
```
5. Run your experiment

The application will then hand/crash. Errors and log are shared above.

**Comment by peircej** [comment]
hmm, we'll need to investigate why that was needed in the first place

@mdcutone can you recall why we needed the change in commit 0c542ba3c from PR #6441 so that we can explore other options without breaking existing behaviour? I'm wondering, for instance, if we should bring in stdout as bytes and then encode it ourselves with a try/except rather than getting subprocess to do the encoding where we're in more trouble if it fails. (I don't actually know what sort of calls are using this to know what text is expected.)

**Comment by hejs9603** [comment]
win 10, psychopy 2024.2.4(py3.10)

you save my life!!!!!!!!!!!!!!!!!!!!!!!!!!!

![Image](https://github.com/user-attachments/assets/717af707-4889-401f-bf3b-b7e53c101278)

**Comment by estherhazy** [comment]
I can only agree with @hejs9603! (Windows 10 and 11, Psychopy 2024.2.4 (py3.10))
The stream is running now with no problems and the psychopy experiment does not abort nor freezes in the end.

Btw I don't know whether this necessarily has to do with the french Windows as I'm working from Germany with German computers.

**Comment by peircej** [comment]
So, if I understand correctly this can be closed? I don't think it's something we've handled explicitly, to be honest, but maybe LSL is now handling codecs better. It's certainly going to be very annoying if we have to change the encoding options for each platform/ language rather than relying on UTF

**Comment by peircej** [comment]
Ah, it's just come up again on the forum, with a user running py3.8 so maybe this is a difference between python versions 3.8 and 3.10. 
https://discourse.psychopy.org/t/broadcasting-lsl-stream-error-message-and-freezing-of-experiment/44821

The good news is that python 3.8 installations will be gradually disappearing (we now set 3.10 as the default in our downloads section but provide 3.8 for users needing further backwards compatibility). It still raises the question of whether we should do some sort of try...except in the code here so that if utf-8 fails we try falling back to `Windows-1252`

**Comment by estherhazy** [comment]
@peircej, epreu is actually me and I'm using py3.10 (I didn't specify, I'm sorry).

**Comment by mcm47** [comment]
It happened to me today in German Windows, and I found this explanation after I posted my message (https://discourse.psychopy.org/t/not-responding-at-the-end-of-the-experiment-with-lsl/44965/2).

**Comment by patricefortin** [comment]
We also encountered this issue on a Windows setup in french.

The command given to `Popen` is psychopy launching a python subprocess to run the compiled task.

Here is a more generic version of the "fix" that could be incorporated in the main psychopy codebase. Tested on Windows (encoding is `cp1252`) and Linux (encoding is `UTF-8`). 

```
        import locale
        encoding = locale.getpreferredencoding(False)
        scriptEnv['PYTHONIOENCODING'] = encoding
        if sys.platform == 'win32':
            scriptEnv['PYTHONLEGACYWINDOWSSTDIO'] = encoding

        try:
            self._process = Popen(
                args=command,
                bufsize=1,
                executable=None,
                stdin=None,
                stdout=PIPE,
                stderr=PIPE,
                preexec_fn=None,
                shell=False,
                cwd=cwd,
                env=scriptEnv,
                # universal_newlines=True,  # gives us back a string instead of bytes
                creationflags=0,
                text=False,
                encoding=encoding
            )
        except FileNotFoundError:
            return -1  # negative PID means failure
```

Of course `import locale` should be at the top of the file, but it is included in the snippet for clarity.
