### ISSUE TITLE
[Bug]: Cannot install packages on MacOS standalone

### ISSUE THREAD

**Issue by domstoppable** [psychopy/psychopy#6734]
### PsychoPy Version

2024.2.0

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

Installing a package in 2024.2.0 standalone via package manager, pip terminal, or from .whl file all fail

Example log from using the package manager to install a plugin:
```>> /Applications/PsychoPy.app/Contents/MacOS/python -m pip install psychopy-crs --user --prefer-binary --no-input --no-color

Could not find platform independent libraries <prefix>


Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/Applications/PsychoPy.app/Contents/MacOS/python'
  isolated = 0
  environment = 1
  user site = 0
  import site = 0
  sys._base_executable = '/Applications/PsychoPy.app/Contents/MacOS/python'
  sys.base_prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.base_exec_prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.executable = '/Applications/PsychoPy.app/Contents/MacOS/python'
  sys.prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.exec_prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.path = [
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000000202e8f240 (most recent call first):
<no Python frame>
ERROR: Exception:
Traceback (most recent call last):
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/resolution/resolvelib/found_candidates.py", line 49, in _iter_built
    for version, func in infos:
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/resolution/resolvelib/factory.py", line 300, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/index/package_finder.py", line 884, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/index/package_finder.py", line 825, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/index/sources.py", line 194, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/index/package_finder.py", line 792, in process_project_url
    package_links = self.evaluate_links(
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/index/package_finder.py", line 772, in evaluate_links
    candidate = self.get_install_candidate(link_evaluator, link)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/index/package_finder.py", line 750, in get_install_candidate
    result, detail = link_evaluator.evaluate_link(link)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/index/package_finder.py", line 201, in evaluate_link
    supported_tags = self._target_python.get_unsorted_tags()
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/models/target_python.py", line 119, in get_unsorted_tags
    self._valid_tags_set = set(self.get_sorted_tags())
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/models/target_python.py", line 103, in get_sorted_tags
    tags = get_supported(
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_internal/utils/compatibility_tags.py", line 142, in get_supported
    supported.extend(
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_vendor/packaging/tags.py", line 224, in cpython_tags
    platforms = list(platforms or platform_tags())
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/pip/_vendor/packaging/tags.py", line 415, in mac_platforms
    version_str = subprocess.run(
  File "subprocess.pyc", line 516, in run
subprocess.CalledProcessError: Command '['/Applications/PsychoPy.app/Contents/MacOS/python', '-sS', '-c', 'import platform; print(platform.mac_ver()[0])']' returned non-zero exit status 1.
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/Applications/PsychoPy.app/Contents/MacOS/python'
  isolated = 0
  environment = 1
  user site = 0
  import site = 0
  sys._base_executable = '/Applications/PsychoPy.app/Contents/MacOS/python'
  sys.base_prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.base_exec_prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.executable = '/Applications/PsychoPy.app/Contents/MacOS/python'
  sys.prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.exec_prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.path = [
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000000204316240 (most recent call first):
<no Python frame>
WARNING: There was an error checking the latest version of pip.



####################### Finished installing psychopy-crs #######################
For more information about the Cambridge Research Systems devices plugin, read the documentation at:
https://psychopy.github.io/psychopy-crs/```

This is on an M2 mac. I have not tested on any other OS or hardware

### Expected Behaviour

Packages should install without error

### Steps to Reproduce

1. Download and install 2024.2.0 standalone
2. Open the package manager
3. Install any package


### Additional context

_No response_

**Comment by domstoppable** [comment]
This appears to be fixed in v2024.2.1
