### ISSUE TITLE
[Bug]: GazePoint Eyetracker not connecting

### ISSUE THREAD

**Issue by Whami007** [psychopy/psychopy#6864]
### PsychoPy Version

2024.2.1

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

I am trying to get GazePoint  GP3 eyetracker to integrate with my PsychoPy experiment, but seem to be running across a bug. I have the GazePoint plugin installed, I have calibration and validation routines on my timeline, and I am also running GazePoint analysis and control when I try this. I will attach a screenshot of the error code I am receiving. After going to the PsychoPy forum, and posting my experiment, I was told I am doing everything correctly and to report a bug to github. Help would be greatly appreciated, thank you. 
![Screenshot 2024-09-19 130601](https://github.com/user-attachments/assets/d24f4121-d2c8-4fa6-b04d-a6c491289ce4)

### Expected Behaviour

The EyeTracker should be connecting to the exp and calibrating at the beginning of the experiment, this is when it crashes. 

### Steps to Reproduce

1.Install GazePoint Plugin
2.Add calibration and validation eyetracking components to the timeline
3.Turn on Gazepoint control and analysis
4. Run the exp file
5. Crash when I get to the calibration routine 
...

**Comment by MichaelWoodc** [comment]
Here is a workaround for you: https://github.com/psychopy/psychopy/issues/7130
you only have to calibrate the eye tracker using the gazepoint software then you're good to go.

**Comment by mdcutone** [comment]
Fixed in the most recent version of PsychoPy and the 0.0.4 release of the GazePoint eyetracker plugin

**Comment by Whami007** [comment]
Hi @mdcutone I have just upgraded to the newest plugin for GazePoint and I am still having trouble getting the eyetracker to integrate. This is the error code I am getting when it crashes

Traceback (most recent call last):
  File "C:\Users\BIKELAB\AppData\Local\Programs\PsychoPy\lib\site-packages\psychopy\iohub\client\__init__.py", line 1099, in _addDeviceView
    dev_import_result = import_device("psychopy.iohub.devices", dev_cls_name)
  File "C:\Users\BIKELAB\AppData\Local\Programs\PsychoPy\lib\site-packages\psychopy\iohub\devices\__init__.py", line 1020, in import_device
    device_class = getattr(module, device_class_name)
AttributeError: module 'psychopy.iohub.devices' has no attribute 'EyeTracker'
Traceback (most recent call last):
  File "C:\Users\BIKELAB\Downloads\EyetrackingExScript\EyetrackingEXScript_lastrun.py", line 1060, in <module>
    run(
  File "C:\Users\BIKELAB\Downloads\EyetrackingExScript\EyetrackingEXScript_lastrun.py", line 596, in run
    calibration.run()
  File "C:\Users\BIKELAB\AppData\Local\Programs\PsychoPy\lib\site-packages\psychopy\hardware\eyetracker.py", line 103, in run
    tracker = self.eyetracker.getIOHubDeviceClass(full=True)
AttributeError: 'NoneType' object has no attribute 'getIOHubDeviceClass'
**1.2647     ERROR     Plugin `psychopy-eyetracker-gazepoint` specified entry point group `psychopy.experiment.components.settings.eyetracking` that does not exist or is unreachable.**

The last 2 bolded lines for this Stdout code are also in red ink. When I originally opened this post up, I was getting all these lines except those last 2. This shows me something is working, I am just not sure what.

I would really appreciate any help with getting the new plugin to work!

**Comment by mdcutone** [comment]
@Whami007 Try using a newer version of PsychoPy if possible. There have been changes to how settings are advertised by plugins that only works with the latest stable release

**Comment by RebeccaHirst** [comment]
@Whami007 just to check 0 are you following the instructions for testing on [this discourse post](https://discourse.psychopy.org/t/gazepoint-and-psychopy-2024-1-5/40495/11?u=becca)? (including updating to newest psychopy release as @mdcutone suggests there but also clearing any old plugins from the installation). 

If you are thanks so much for your testing and feedback - this will be helpful in us getting this going for everyone!

Becca
