### ISSUE TITLE
[Bug]: AttributeError: 'EntryPoints' object has no attribute 'items'

### ISSUE THREAD

**Issue by micwoj92** [psychopy/psychopy#6963]
### PsychoPy Version

2024.2.4

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

Launching psychopy with importlib-metadata>=5.0.0 causes error
```
Traceback (most recent call last):
  File "/usr/bin/psychopy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/psychopy/app/psychopyApp.py", line 105, in main
    start_app()
  File "/usr/lib/python3.12/site-packages/psychopy/app/psychopyApp.py", line 27, in start_app
    _ = startApp(showSplash=showSplash)  # main loop
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/psychopy/app/__init__.py", line 97, in startApp
    _psychopyAppInstance = PsychoPyApp(
                           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/psychopy/app/_psychopyApp.py", line 248, in __init__
    self.onInit(testMode=testMode, startView=startView, **kwargs)
  File "/usr/lib/python3.12/site-packages/psychopy/app/_psychopyApp.py", line 429, in onInit
    from psychopy.app import coder, builder, runner, dialogs
  File "/usr/lib/python3.12/site-packages/psychopy/app/coder/__init__.py", line 8, in <module>
    from .coder import CoderFrame, BaseCodeEditor  # pylint: disable=W0401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/psychopy/app/coder/coder.py", line 44, in <module>
    import psychopy.app.plugin_manager.dialog
  File "/usr/lib/python3.12/site-packages/psychopy/app/plugin_manager/dialog.py", line 9, in <module>
    from psychopy.experiment import getAllElements
  File "/usr/lib/python3.12/site-packages/psychopy/experiment/__init__.py", line 22, in <module>
    from ._experiment import Experiment
  File "/usr/lib/python3.12/site-packages/psychopy/experiment/_experiment.py", line 32, in <module>
    from .exports import IndentingBuffer, NameSpace
  File "/usr/lib/python3.12/site-packages/psychopy/experiment/exports.py", line 26, in <module>
    from .components.settings import _numpyImports, _numpyRandomImports
  File "/usr/lib/python3.12/site-packages/psychopy/experiment/components/settings/__init__.py", line 46, in <module>
    ioDeviceMap = dict(ioUtil.getDeviceNames(device_name="eyetracker.hw"))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/psychopy/iohub/util/__init__.py", line 375, in getDeviceNames
    dconfigs = getDeviceDefaultConfig(device_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/psychopy/iohub/util/__init__.py", line 328, in getDeviceDefaultConfig
    device_paths = getDevicePaths(device_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/psychopy/iohub/util/__init__.py", line 273, in getDevicePaths
    for ep in getEntryPoints('psychopy.iohub.devices.eyetracker', submodules=False, flatten=True):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/psychopy/plugins/util.py", line 25, in getEntryPoints
    for group, points in importlib.metadata.entry_points().items():
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'items'
```

### Expected Behaviour

No such error while launching.

### Steps to Reproduce

1. Install psychopy
~2. Install importlib-metadata>=5.0.0~
3. Launch
4. Error

### Additional context

https://github.com/python/importlib_metadata/issues/409

**Comment by peircej** [comment]
@micwoj92 it looks like you're using Python 3.12 which we don't currently support (haven't tested on). Do you also see this issue with python3.10?

**Comment by micwoj92** [comment]
No, it's not 3.10 has older version of importlib metadata in stdlib.

Also I guess this isn't really issue, because `importlib.metadata` is the one in stdlib. This is just an issue that I ran into while trying to run this on newer python version.


This will only become a problem when 3.12 is supported.
https://github.com/python/importlib_metadata?tab=readme-ov-file#compatibility

**Comment by Lance-Buescher1** [comment]
@micwoj92 I'm looking into this issue but am curious how you installed PsychoPy. I'm currently unable to install psychopy with python 3.12.0. Could you give some details as to how you installed PsychoPy?

**Comment by micwoj92** [comment]
I'm using (currently broken) AUR package: https://aur.archlinux.org/packages/psychopy

**Comment by TEParsons** [comment]
This is now handled I think: https://github.com/TEParsons/psychopy/commit/b7c49f89ec037588dacc6286150e7c0664a7410f
