### ISSUE TITLE
[Bug]: audio play leads to TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by yarikoptic** [psychopy/psychopy#6964]
### PsychoPy Version

2024.2.1

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

echoing 
- https://github.com/psychopy/psychopy/issues/6765

where we run into following exception raised from somewhere deep within psychopy code:

```
❯ tools/reprostim-timesync-stimuli output2.log 1
2024-11-06 13:03:54,724 [INFO] reprostim-timesync-stimuli script started
pygame 2.6.1 (SDL 2.28.4, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
2024-11-06 13:03:58,918 [INFO] main script started
2024-11-06 13:04:00,097 [DEBUG] warming time: 5.393667 sec
2024-11-06 13:04:00,097 [DEBUG] play_beep(480, duration=120, volume=1.0)
Failure: No such entity
Failure: No such entity
Traceback (most recent call last):
  File "/home/yoh/proj/repronim/reprostim/tools/reprostim-timesync-stimuli", line 125, in <module>
    play_beep(480, 120, 1.0)
  File "/home/yoh/proj/repronim/reprostim/tools/reprostim-timesync-stimuli", line 78, in play_beep
    beep = sound.Sound(frequency, secs=duration, volume=volume)
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/sound/backend_ptb.py", line 334, in __init__
    self.setSound(value, secs=self.secs, octave=self.octave,
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/sound/backend_ptb.py", line 423, in setSound
    _SoundBase.setSound(self, value, secs, octave, hamming, log)
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/sound/_base.py", line 189, in setSound
    self._setSndFromFreq(value, secs, hamming=hamming)
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/sound/_base.py", line 264, in _setSndFromFreq
    self._setSndFromArray(outArr)
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/sound/backend_ptb.py", line 497, in _setSndFromArray
    self.track = audio.Slave(self.stream.handle, data=self.sndArr,
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/sound/backend_ptb.py", line 609, in stream
    label, s = streams.getStream(sampleRate=self.sampleRate,
TypeError: cannot unpack non-iterable NoneType object
3.8869 	WARNING 	Monitor specification not found. Creating a temporary one...
3.8928 	WARNING 	Requested an unavailable screen number - using first available.
3.9700 	WARNING 	User requested fullscreen with size [800 600], but screen is actually [3840, 2400]. Using actual size
Failure: No such entity
Failure: No such entity
 tools/reprostim-timesync-stimuli output2.log 1  4.59s user 3.38s system 96% cpu 8.274 total
```

IMHO there should be first assignment of the returned value and then analysis/report on inadequacy and potentially giving a reason (sound device not initialized?  or initialized with insufficient channels? or ... ?) instead of just blowing up into the user's face.

### Expected Behaviour

Perform as expected (play sound) or provide a more informative error 

### Steps to Reproduce

example from
- https://github.com/psychopy/psychopy/issues/6765

works for me too

```
❯  python
Python 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psychtoolbox as ptb
>>> from psychopy import sound

>>> 
>>> mySound = sound.Sound('A')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy_sounddevice/backend_sounddevice.py", line 328, in __init__
    self.setSound(value, secs=self.secs, octave=self.octave,
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy_sounddevice/backend_sounddevice.py", line 382, in setSound
    label, s = streams.getStream(sampleRate=self.sampleRate,
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by psyxw** [comment]
I encountered the exact same issue recently. I resolved it by explicitly setting `stereo=True` (or `stereo=False`, but not the default value `-1`) after selecting the appropriate sound device with `prefs.hardware['audioDevice'] = 'your/output/device/here'`.

**Comment by TEParsons** [comment]
@mdcutone has made all sorts of changes to the sounddevice backend in the last few versions so I think this will no longer apply; please reopen if you still get this bug in the latest version
