### ISSUE TITLE
[Bug]: TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by yarikoptic** [psychopy/psychopy#6965]
### PsychoPy Version

2024.2.1

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

it seems when audio is "tricky" then without first checking if any speaker found, it jumps to comparison

```python
#!/usr/bin/env python3
from time import time, sleep
import os
from datetime import datetime

from psychopy import prefs
print("Changing hardware for audio")
# prefs.hardware['audioLib'] = ['ptb'] # , 'pyo','pygame']
prefs.hardware['audioLib'] = ['pygame']

from psychopy import sound
from psychopy import core 

print("starting")

def beep_4():
    print("play sound with psychopy ptb")
    while True:
        snd = sound.Sound('D', secs=2.0, stereo=True)
        snd.play()
        core.wait(snd.duration)
        print(f'Sound "{snd.sound}" has finished playing.')
        sleep(1)

beep_4()
```

leads on my laptop to

```
❯ python tools/play-sound.py
Changing hardware for audio
pygame 2.6.1 (SDL 2.28.4, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
starting
play sound with psychopy ptb
Traceback (most recent call last):
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/hardware/manager.py", line 250, in addDevice
    device = cls(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/hardware/speaker.py", line 27, in __init__
    if index < 0 or index not in available_index:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoh/proj/repronim/reprostim/tools/play-sound.py", line 25, in <module>
    beep_4()
  File "/home/yoh/proj/repronim/reprostim/tools/play-sound.py", line 19, in beep_4
    snd = sound.Sound('D', secs=2.0, stereo=True)
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/sound/backend_pygame.py", line 156, in __init__
    self.speaker = self._parseSpeaker(speaker)
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/sound/_base.py", line 132, in _parseSpeaker
    device = DeviceManager.addDevice(
  File "/home/yoh/miniconda3/envs/psychopy-2024.2.1/lib/python3.10/site-packages/psychopy/hardware/manager.py", line 253, in addDevice
    raise ManagedDeviceError(
psychopy.hardware.manager.ManagedDeviceError: '<' not supported between instances of 'NoneType' and 'int'
0.8583 	WARNING 	We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['pygame'] (in that order).

```

whenever I have 

<details>
<summary>ptb.get_devices()</summary> 

```shell
>>> from pprint import pprint
>>> import psychtoolbox.audio as ptb
*>>> pprint(ptb.get_devices())
[{'DefaultSampleRate': 44100.0,
  'DeviceIndex': 0.0,
  'DeviceName': 'HDA NVidia: HDMI 0 (hw:0,3)',
  'HighInputLatency': -1.0,
  'HighOutputLatency': 0.034829931972789115,
  'HostAudioAPIId': 8.0,
  'HostAudioAPIName': 'ALSA',
  'LowInputLatency': -1.0,
  'LowOutputLatency': 0.008707482993197279,
  'NrInputChannels': 0.0,
  'NrOutputChannels': 8.0},
 {'DefaultSampleRate': 44100.0,
  'DeviceIndex': 1.0,
  'DeviceName': 'HDA NVidia: HDMI 1 (hw:0,7)',
  'HighInputLatency': -1.0,
  'HighOutputLatency': 0.034829931972789115,
  'HostAudioAPIId': 8.0,
  'HostAudioAPIName': 'ALSA',
  'LowInputLatency': -1.0,
  'LowOutputLatency': 0.008707482993197279,
  'NrInputChannels': 0.0,
  'NrOutputChannels': 8.0},
 {'DefaultSampleRate': 44100.0,
  'DeviceIndex': 2.0,
  'DeviceName': 'HDA NVidia: HDMI 2 (hw:0,8)',
  'HighInputLatency': -1.0,
  'HighOutputLatency': 0.034829931972789115,
  'HostAudioAPIId': 8.0,
  'HostAudioAPIName': 'ALSA',
  'LowInputLatency': -1.0,
  'LowOutputLatency': 0.008707482993197279,
  'NrInputChannels': 0.0,
  'NrOutputChannels': 8.0},
 {'DefaultSampleRate': 44100.0,
  'DeviceIndex': 3.0,
  'DeviceName': 'HDA NVidia: HDMI 3 (hw:0,9)',
  'HighInputLatency': -1.0,
  'HighOutputLatency': 0.034829931972789115,
  'HostAudioAPIId': 8.0,
  'HostAudioAPIName': 'ALSA',
  'LowInputLatency': -1.0,
  'LowOutputLatency': 0.008707482993197279,
  'NrInputChannels': 0.0,
  'NrOutputChannels': 8.0},
 {'DefaultSampleRate': 48000.0,
  'DeviceIndex': 4.0,
  'DeviceName': 'sof-hda-dsp: - (hw:1,0)',
  'HighInputLatency': 0.032,
  'HighOutputLatency': 0.032,
  'HostAudioAPIId': 8.0,
  'HostAudioAPIName': 'ALSA',
  'LowInputLatency': 0.008,
  'LowOutputLatency': 0.008,
  'NrInputChannels': 2.0,
  'NrOutputChannels': 2.0},
 {'DefaultSampleRate': 48000.0,
  'DeviceIndex': 5.0,
  'DeviceName': 'sof-hda-dsp: - (hw:1,3)',
  'HighInputLatency': -1.0,
  'HighOutputLatency': 0.032,
  'HostAudioAPIId': 8.0,
  'HostAudioAPIName': 'ALSA',
  'LowInputLatency': -1.0,
  'LowOutputLatency': 0.008,
  'NrInputChannels': 0.0,
  'NrOutputChannels': 2.0},
 {'DefaultSampleRate': 48000.0,
  'DeviceIndex': 6.0,
  'DeviceName': 'sof-hda-dsp: - (hw:1,4)',
  'HighInputLatency': -1.0,
  'HighOutputLatency': 0.032,
  'HostAudioAPIId': 8.0,
  'HostAudioAPIName': 'ALSA',
  'LowInputLatency': -1.0,
  'LowOutputLatency': 0.008,
  'NrInputChannels': 0.0,
  'NrOutputChannels': 2.0},
 {'DefaultSampleRate': 48000.0,
  'DeviceIndex': 7.0,
  'DeviceName': 'sof-hda-dsp: - (hw:1,5)',
  'HighInputLatency': -1.0,
  'HighOutputLatency': 0.032,
  'HostAudioAPIId': 8.0,
  'HostAudioAPIName': 'ALSA',
  'LowInputLatency': -1.0,
  'LowOutputLatency': 0.008,
  'NrInputChannels': 0.0,
  'NrOutputChannels': 2.0},
 {'DefaultSampleRate': 16000.0,
  'DeviceIndex': 8.0,
  'DeviceName': 'sof-hda-dsp: - (hw:1,7)',
  'HighInputLatency': 0.096,
  'HighOutputLatency': -1.0,
  'HostAudioAPIId': 8.0,
  'HostAudioAPIName': 'ALSA',
  'LowInputLatency': 0.024,
  'LowOutputLatency': -1.0,
  'NrInputChannels': 2.0,
  'NrOutputChannels': 0.0},
 {'DefaultSampleRate': 48000.0,
  'DeviceIndex': 9.0,
  'DeviceName': 'sof-hda-dsp: - (hw:1,31)',
  'HighInputLatency': -1.0,
  'HighOutputLatency': 0.032,
  'HostAudioAPIId': 8.0,
  'HostAudioAPIName': 'ALSA',
  'LowInputLatency': -1.0,
  'LowOutputLatency': 0.008,
  'NrInputChannels': 0.0,
  'NrOutputChannels': 2.0}]

```
</details>

and even more fun

```
>>> from psychopy.hardware import speaker

>>> for profile in speaker.SpeakerDevice.getAvailableDevices():
...     print(profile)
... 
{'deviceName': 'Unknown Microphone', 'index': None}
```

full output of `pactl list` is http://www.oneukrainian.com/tmp/pactl-list-20241106.txt where you can search for "Speaker".

related to my case:
- https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/852

### Expected Behaviour

play sound 

### Steps to Reproduce

run above script on my laptop

**Comment by TEParsons** [comment]
I think this is fixed now - we now have code handling when a Speaker index is None
