### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by saraasz** [psychopy/psychopy#7011]
### PsychoPy Version

2022.2.5

### What OS are your PsychoPy running on?

Windows 10

### Bug Description

The program suggested contacting the developers, dropping this message. Instead of running the experiment as before, a blank grey screen is presented for a few seconds, then it all crashes.

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\dialogs\__init__.py", line 1705, in onOK
    self.refreshConditions()
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\dialogs\__init__.py", line 1672, in refreshConditions
    self.conditions = data.importConditions(
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\data\utils.py", line 356, in importConditions
    wb = load_workbook(filename=fileName, data_only=True)
  File "C:\Program Files\PsychoPy\lib\site-packages\openpyxl\reader\excel.py", line 315, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
  File "C:\Program Files\PsychoPy\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "C:\Program Files\PsychoPy\lib\site-packages\openpyxl\reader\excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "C:\Program Files\PsychoPy\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'C:/Users/saraa/OneDrive - Aarhus universitet/Thesis/Experiment/troubleshooting.xlsx'

### Expected Behaviour

Looping through a conditions file displaying different images. 

### Steps to Reproduce

1.
2.
3.
...

**Comment by peircej** [comment]
And you can actually open that file from the windows file explorer? Puzzling that there would be a permissions problem. Oh, the file is in your onedrive. Have you set that folder to be "always available offline"? Maybe the file is only on the onedrive server so PsychoPy thinks it's denied permission when actually the file just isn't currently available
