### ISSUE TITLE
psychopyApp.py not found by pkg_resources when installed by conda

### ISSUE THREAD

**Issue by kastman** [psychopy/psychopy#702]
After installing psychopy using conda and trying to run the psychopyApp.py script, pkg_resources is unable to find it:

``` bash
$ python /Users/kastman/anaconda/bin/psychopyApp.py
Traceback (most recent call last):
  File "/Users/kastman/anaconda/bin/psychopyApp.py", line 5, in <module>
    pkg_resources.run_script('PsychoPy==1.80.01', 'psychopyApp.py')
  File "/Users/kastman/anaconda/lib/python2.7/site-packages/setuptools-2.2-py2.7.egg/pkg_resources.py", line 488, in run_script
  File "/Users/kastman/anaconda/lib/python2.7/site-packages/setuptools-2.2-py2.7.egg/pkg_resources.py", line 1348, in run_script
pkg_resources.ResolutionError: No script named 'psychopyApp.py'
```

We need to figure out why pkg_resources is missing this and fix the distribution if possible.

**Comment by dengsauve** [comment]
@kastman I was routed here from codetriage, saw your project and thought it would be a cool one to help out on. This issue is almost two years old; has this been resolved, or is it even relevant?

Thanks

**Comment by kastman** [comment]
Wasn't familiar with codetriage before - what a great idea. AFAIK this issue never got resolved - I'll verify with a current build in the morning, but always happy to have any help we can get. I'll check and comment back. Thanks!

**Comment by hoechenberger** [comment]
Cannot reproduce on a Mac with the latest PsychoPy version. @kastman, can you still observe this problem?

**Comment by kastman** [comment]
Yes, just verified this again on 10.10 w/ a fresh psycohpy install from conda. Can you list the steps that worked for you? This is still broken for me:

    $ conda create -n psychopy-2016Oct psychopy
    $ source activate psychopy-2016Oct psychopy
    $ which pythonw 
    /Users/kastman/miniconda/envs/psychopy-2016Oct/bin/pythonw
    
    $ pythonw /Users/kastman/miniconda/envs/psychopy-2016Oct/bin/psychopyApp.py 
    Traceback (most recent call last):
      File "/Users/kastman/miniconda/envs/psychopy-2016Oct/bin/psychopyApp.py", line 5, in <module>
        pkg_resources.run_script('PsychoPy==1.80.01', 'psychopyApp.py')
      File "/Users/kastman/miniconda/envs/psychopy-2016Oct/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
    
      File "/Users/kastman/miniconda/envs/psychopy-2016Oct/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1491, in run_script
    
    pkg_resources.ResolutionError: No script named 'psychopyApp.py'

**Comment by hoechenberger** [comment]
Sorry, my mistake, I used the wrong conda environment and accidentally checked with a pip-installed PsychoPy. Conda install broken for me too.

**Comment by peircej** [comment]
I suggest we have a new issue about supporting conda install #1814
