### ISSUE TITLE
PsychoPy freezes at the end of the experiment when using IO Labs Button Box

### ISSUE THREAD

**Issue by astasenk** [psychopy/psychopy#769]
Hello,

I am having issues with an IO Lab response box and PsychoPy freezing at the end of the experiment. Specifically, I've tried using the latest version of PsychoPY ( PsychoPy 1.8) on both windows and MAC mode, and at the last trial, PsychoPy freezes and I have to force quit it. However, it seems that this only happens at the very last trial, and the responses and button box output are all saved and are not negatively affected. It's just that I have to force quit the program at the end. Below is the error it throws at the end:

##### Running: script.py #####
Unhandled exception in thread started by <bound method CallbackLoop.__bootstrap of <CallbackLoop(Thread-1, stopped daemon -1336307712)>>
Traceback (most recent call last):
  File "threading.pyc", line 524, in __bootstrap
  File "threading.pyc", line 564, in __bootstrap_inner
  File "traceback.pyc", line 241, in format_exc
  File "traceback.pyc", line 141, in format_exception
  File "traceback.pyc", line 76, in format_tb
  File "traceback.pyc", line 101, in extract_tb
  File "linecache.pyc", line 14, in getline
  File "linecache.pyc", line 40, in getlines
  File "linecache.pyc", line 111, in updatecache
TypeError: 'NoneType' object is not iterable
Unhandled exception in thread started by <bound method CallbackLoop.__bootstrap of <CallbackLoop(Thread-2, stopped daemon -1329442816)>>
Traceback (most recent call last):
  File "threading.pyc", line 524, in __bootstrap
  File "threading.pyc", line 564, in __bootstrap_inner
  File "traceback.pyc", line 241, in format_exc
  File "traceback.pyc", line 141, in format_exception
  File "traceback.pyc", line 76, in format_tb
  File "traceback.pyc", line 101, in extract_tb
  File "linecache.pyc", line 14, in getline
  File "linecache.pyc", line 40, in getlines
  File "linecache.pyc", line 108, in updatecache
TypeError: 'NoneType' object is not callable

Also to go along with this possibly button-box related issue, there is an error at the beginning which doesn't let me run the experiment. But when I run it for the 2nd time, it works fine. Also not sure how to fix this bug. Here is the error at the start of the experiment:

##### Running: script.py #####
Traceback (most recent call last):
  File "/Users/Shared/Experiments/Alena/PsychoPy_DigitNaming/DigitName_MAC.py", line 44, in <module>
    iolab.ButtonBox().standby()
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/hardware/iolab.py", line 50, in __init__
    ioLabs.USBBox.__init__(self)
  File "ioLabs.pyc", line 804, in __init__
  File "ioLabs.pyc", line 949, in reset_box
  File "ioLabs.pyc", line 937, in disable_loopback
AttributeError: 'NoneType' object has no attribute 'port2_bits'
Exception AttributeError: "'ButtonBox' object has no attribute 'remove_callback'" in <bound method ButtonBox.__del__ of <psychopy.hardware.iolab.ButtonBox object at 0x9ccddb0>> ignored

I appreciate your help with this issue.

Best,
Alena

**Comment by hoechenberger** [comment]
Hi Alena, was this problem ever resolved?

**Comment by astasenk** [comment]
Hello,

It was (I think by adding an extra line to the script) and I believe it isn't an issue with the new versions of psycho py. Thanks!

**Comment by hoechenberger** [comment]
All right, closing this issue for now. Feel free to re-open if this problem shows up again.
