### ISSUE TITLE
class experiment.ExpFile: issues with deepcopy

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#968]
I am trying to develop the ExpFile class, and have put together some of (by no means all necessary) wx code to support it. I can add it the the Flow, and browse for a file. However, whenever an action is added to the undo list (e.g., removing an ExpFile instance from the Flow, adding a loop around it), the app fails:

    Traceback (most recent call last):
      File "/Users/jgray/code/psychopy/psychopy/app/builder/builder.py", line 850, in onContextSelect
        self.frame.addToUndoStack("REMOVE `%s` from Flow" %component.params['name'])
      File "/Users/jgray/code/psychopy/psychopy/app/builder/builder.py", line 4943, in addToUndoStack
        state=copy.deepcopy(self.exp)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 334, in _reconstruct
        state = deepcopy(state, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 334, in _reconstruct
        state = deepcopy(state, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 334, in _reconstruct
        state = deepcopy(state, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 334, in _reconstruct
        state = deepcopy(state, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 334, in _reconstruct
        state = deepcopy(state, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/Users/jgray/anaconda/lib/python2.7/copy.py", line 329, in _reconstruct
        y = callable(*args)
      File "/Users/jgray/anaconda/lib/python2.7/copy_reg.py", line 93, in __newobj__
        return cls.__new__(cls, *args)
    TypeError: object.__new__(PySwigObject) is not safe, use PySwigObject.__new__()

I am confused as to why it should fail, since it is modeled closely on class Routine; both inherit from class list. The only thing I could think of was the loadExp method, which references Experiment:

    def loadExp(self):
        #fetch the file
        self.expObject = Experiment()
        self.expObject.loadFromXML(self.filename)
        self.flow = self.expObject.flow

But I get the crash even if I delete that part of the code from the class.

I did get a alternative version working, based around a new ExpFile component and hacking the `Experiment.writeScript()` method to behave a little differently for embedded scripts. This seems to work well, but the code is not as nice and its a little cumbersome to use.

**Comment by TEParsons** [comment]
Re-labelling this as enhancement as ExpFile isn't in use
